import {type MigrateUpArgs,type MigrateDownArgs,sql} from '@payloadcms/db-sqlite'
// Schema-only migration. No records from the uploaded development database.
const statements=[
  "CREATE TABLE `_blog_posts_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_slug` text,\n\t`version_cover_id` integer,\n\t`version_author` text DEFAULT 'CodeMaster',\n\t`version_published_at` text,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\t`autosave` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_cover_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_blog_posts_v_locales` (\n\t`version_title` text,\n\t`version_excerpt` text,\n\t`version_seo_title` text,\n\t`version_seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_blog_posts_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_blog_posts_v_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`blog_posts_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `_blog_posts_v`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`blog_posts_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_blog_posts_v_version_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`body` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_blog_posts_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_blog_posts_v_version_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_blog_posts_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_faqs_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_order` numeric DEFAULT 1,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_faqs_v_locales` (\n\t`version_question` text,\n\t`version_answer` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_faqs_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_homepage_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `_homepage_v_locales` (\n\t`version_services_kicker` text,\n\t`version_services_title` text,\n\t`version_services_description` text,\n\t`version_projects_kicker` text,\n\t`version_projects_title` text,\n\t`version_projects_description` text,\n\t`version_process_kicker` text,\n\t`version_process_title` text,\n\t`version_process_description` text,\n\t`version_contact_kicker` text,\n\t`version_contact_title` text,\n\t`version_contact_description` text,\n\t`version_about_kicker` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_homepage_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_homepage_v_version_conversation` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`side` text NOT NULL,\n\t`text` text NOT NULL,\n\t`stage` numeric NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_homepage_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_homepage_v_version_stages` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text NOT NULL,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_homepage_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_homepage_v_version_trust_items` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`text` text NOT NULL,\n\t`description` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_homepage_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_industries_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `industries`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_industries_v_locales` (\n\t`version_name` text,\n\t`version_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_industries_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_projects_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_order` numeric DEFAULT 1,\n\t`version_slug` text,\n\t`version_visual_style` text DEFAULT 'dashboard',\n\t`version_concept` integer DEFAULT true,\n\t`version_client` text,\n\t`version_featured` integer DEFAULT true,\n\t`version_image_id` integer,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\t`autosave` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_projects_v_locales` (\n\t`version_title` text,\n\t`version_category` text,\n\t`version_summary` text,\n\t`version_result` text,\n\t`version_seo_title` text,\n\t`version_seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_projects_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_projects_v_version_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`body` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_projects_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_projects_v_version_technologies` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`_uuid` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_projects_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_services_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_order` numeric DEFAULT 1,\n\t`version_visual_style` text DEFAULT 'dashboard',\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `services`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_services_v_locales` (\n\t`version_title` text,\n\t`version_description` text,\n\t`version_short_label` text,\n\t`version_outcome` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_services_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_site_settings_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`version_brand_name` text DEFAULT 'CodeMaster',\n\t`version_brand_suffix` text DEFAULT 'Software House',\n\t`version_founder_name` text DEFAULT 'Piotr Montewka',\n\t`version_email` text NOT NULL,\n\t`version_phone` text,\n\t`version_founder_photo_id` integer,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`version_founder_photo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_site_settings_v_locales` (\n\t`version_founder_role` text,\n\t`version_announcement` text,\n\t`version_hero_eyebrow` text,\n\t`version_hero_title` text,\n\t`version_hero_lead` text,\n\t`version_primary_c_t_a` text,\n\t`version_secondary_c_t_a` text,\n\t`version_trust_headline` text,\n\t`version_trust_copy` text,\n\t`version_about_copy` text,\n\t`version_seo_title` text,\n\t`version_seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_site_settings_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_technologies_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `technologies`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_technologies_v_locales` (\n\t`version_name` text,\n\t`version_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_technologies_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `_testimonials_v` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`parent_id` integer,\n\t`version_name` text,\n\t`version_company` text,\n\t`version_avatar_id` integer,\n\t`version_logo_id` integer,\n\t`version_video_u_r_l` text,\n\t`version_featured` integer DEFAULT true,\n\t`version_updated_at` text,\n\t`version_created_at` text,\n\t`version__status` text DEFAULT 'draft',\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`snapshot` integer,\n\t`published_locale` text,\n\t`latest` integer, `version_rating` numeric,\n\tFOREIGN KEY (`parent_id`) REFERENCES `testimonials`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_avatar_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`version_logo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `_testimonials_v_locales` (\n\t`version_role` text,\n\t`version_quote` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `_testimonials_v`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `blog_posts` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`slug` text,\n\t`cover_id` integer,\n\t`author` text DEFAULT 'CodeMaster',\n\t`published_at` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft',\n\tFOREIGN KEY (`cover_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `blog_posts_locales` (\n\t`title` text,\n\t`excerpt` text,\n\t`seo_title` text,\n\t`seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `blog_posts_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`blog_posts_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`blog_posts_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `blog_posts_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`body` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `blog_posts_tags` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `contact_settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`legal_name` text,\n\t`legal_address` text,\n\t`hosting_provider` text,\n\t`privacy_reviewed` integer DEFAULT false,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `contact_settings_locales` (\n\t`retention_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `contact_settings`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `faqs` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` numeric DEFAULT 1,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft'\n)",
  "CREATE TABLE `faqs_locales` (\n\t`question` text,\n\t`answer` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `footer` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `footer_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text NOT NULL,\n\t`href` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `footer`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `footer_locales` (\n\t`statement` text,\n\t`footnote` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `footer`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `form_attempts` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text NOT NULL,\n\t`expires_at` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `homepage` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `homepage_conversation` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`side` text NOT NULL,\n\t`text` text NOT NULL,\n\t`stage` numeric NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `homepage`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `homepage_locales` (\n\t`services_kicker` text,\n\t`services_title` text,\n\t`services_description` text,\n\t`projects_kicker` text,\n\t`projects_title` text,\n\t`projects_description` text,\n\t`process_kicker` text,\n\t`process_title` text,\n\t`process_description` text,\n\t`contact_kicker` text,\n\t`contact_title` text,\n\t`contact_description` text,\n\t`about_kicker` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `homepage`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `homepage_stages` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `homepage`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `homepage_trust_items` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text NOT NULL,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `homepage`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `industries` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft'\n)",
  "CREATE TABLE `industries_locales` (\n\t`name` text,\n\t`description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `industries`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `installation_state` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`content_initialized_at` text,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `leads` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`submission_key` text NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`company` text,\n\t`phone` text,\n\t`topic` text NOT NULL,\n\t`message` text NOT NULL,\n\t`timeline` text,\n\t`budget` text,\n\t`nda` integer,\n\t`privacy_accepted` integer DEFAULT false NOT NULL,\n\t`privacy_version` text DEFAULT '2026-09-29',\n\t`locale` text DEFAULT 'pl',\n\t`source` text DEFAULT 'contact',\n\t`attachment_id` integer,\n\t`status` text DEFAULT 'new',\n\t`internal_notes` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`attachment_id`) REFERENCES `private_files`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `media` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`url` text,\n\t`thumbnail_u_r_l` text,\n\t`filename` text,\n\t`mime_type` text,\n\t`filesize` numeric,\n\t`width` numeric,\n\t`height` numeric,\n\t`focal_x` numeric,\n\t`focal_y` numeric,\n\t`sizes_thumbnail_url` text,\n\t`sizes_thumbnail_width` numeric,\n\t`sizes_thumbnail_height` numeric,\n\t`sizes_thumbnail_mime_type` text,\n\t`sizes_thumbnail_filesize` numeric,\n\t`sizes_thumbnail_filename` text,\n\t`sizes_large_url` text,\n\t`sizes_large_width` numeric,\n\t`sizes_large_height` numeric,\n\t`sizes_large_mime_type` text,\n\t`sizes_large_filesize` numeric,\n\t`sizes_large_filename` text\n)",
  "CREATE TABLE `media_locales` (\n\t`alt` text NOT NULL,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `navigation` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `navigation_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text NOT NULL,\n\t`href` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `navigation`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `navigation_locales` (\n\t`cta` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `navigation`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `payload_kv` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text NOT NULL,\n\t`data` text NOT NULL\n)",
  "CREATE TABLE `payload_locked_documents` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`global_slug` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `payload_locked_documents_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`users_id` integer,\n\t`media_id` integer,\n\t`services_id` integer,\n\t`projects_id` integer,\n\t`testimonials_id` integer,\n\t`leads_id` integer,\n\t`private_files_id` integer,\n\t`form_attempts_id` integer,\n\t`blog_posts_id` integer,\n\t`faqs_id` integer,\n\t`technologies_id` integer,\n\t`industries_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `payload_locked_documents`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`users_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`services_id`) REFERENCES `services`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`projects_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`testimonials_id`) REFERENCES `testimonials`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`leads_id`) REFERENCES `leads`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`private_files_id`) REFERENCES `private_files`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`form_attempts_id`) REFERENCES `form_attempts`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`blog_posts_id`) REFERENCES `blog_posts`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`technologies_id`) REFERENCES `technologies`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`industries_id`) REFERENCES `industries`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `payload_preferences` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text,\n\t`value` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `payload_migrations` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`batch` numeric,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `payload_preferences_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`users_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `payload_preferences`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`users_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `private_files` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`submission_key` text NOT NULL,\n\t`sha256` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`url` text,\n\t`thumbnail_u_r_l` text,\n\t`filename` text,\n\t`mime_type` text,\n\t`filesize` numeric,\n\t`width` numeric,\n\t`height` numeric,\n\t`focal_x` numeric,\n\t`focal_y` numeric\n)",
  "CREATE TABLE `projects` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` numeric DEFAULT 1,\n\t`slug` text,\n\t`visual_style` text DEFAULT 'dashboard',\n\t`concept` integer DEFAULT true,\n\t`client` text,\n\t`featured` integer DEFAULT true,\n\t`image_id` integer,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft',\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `projects_locales` (\n\t`title` text,\n\t`category` text,\n\t`summary` text,\n\t`result` text,\n\t`seo_title` text,\n\t`seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `projects_sections` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`heading` text,\n\t`body` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `projects_technologies` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `seo` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`og_image_id` integer,\n\t`updated_at` text,\n\t`created_at` text,\n\tFOREIGN KEY (`og_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `seo_locales` (\n\t`title` text,\n\t`description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `seo`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `services` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` numeric DEFAULT 1,\n\t`visual_style` text DEFAULT 'dashboard',\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft'\n)",
  "CREATE TABLE `services_locales` (\n\t`title` text,\n\t`description` text,\n\t`short_label` text,\n\t`outcome` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `services`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `site_settings` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`brand_name` text DEFAULT 'CodeMaster',\n\t`brand_suffix` text DEFAULT 'Software House',\n\t`founder_name` text DEFAULT 'Piotr Montewka',\n\t`email` text NOT NULL,\n\t`phone` text,\n\t`founder_photo_id` integer,\n\t`updated_at` text,\n\t`created_at` text,\n\tFOREIGN KEY (`founder_photo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `site_settings_locales` (\n\t`founder_role` text,\n\t`announcement` text,\n\t`hero_eyebrow` text,\n\t`hero_title` text,\n\t`hero_lead` text,\n\t`primary_c_t_a` text,\n\t`secondary_c_t_a` text,\n\t`trust_headline` text,\n\t`trust_copy` text,\n\t`about_copy` text,\n\t`seo_title` text,\n\t`seo_description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `site_settings`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `social_links` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text,\n\t`created_at` text\n)",
  "CREATE TABLE `social_links_links` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`_locale` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`label` text NOT NULL,\n\t`href` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `social_links`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `technologies` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft'\n)",
  "CREATE TABLE `technologies_locales` (\n\t`name` text,\n\t`description` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `technologies`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `testimonials` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`company` text,\n\t`avatar_id` integer,\n\t`logo_id` integer,\n\t`video_u_r_l` text,\n\t`featured` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`_status` text DEFAULT 'draft', `rating` numeric,\n\tFOREIGN KEY (`avatar_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`logo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `testimonials_locales` (\n\t`role` text,\n\t`quote` text,\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`_locale` text NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `testimonials`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `users` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`email` text NOT NULL,\n\t`reset_password_token` text,\n\t`reset_password_expiration` text,\n\t`salt` text,\n\t`hash` text,\n\t`login_attempts` numeric DEFAULT 0,\n\t`lock_until` text\n)",
  "CREATE TABLE `users_sessions` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` text,\n\t`expires_at` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE INDEX `_blog_posts_v_autosave_idx` ON `_blog_posts_v` (`autosave`)",
  "CREATE INDEX `_blog_posts_v_created_at_idx` ON `_blog_posts_v` (`created_at`)",
  "CREATE INDEX `_blog_posts_v_latest_idx` ON `_blog_posts_v` (`latest`)",
  "CREATE UNIQUE INDEX `_blog_posts_v_locales_locale_parent_id_unique` ON `_blog_posts_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_blog_posts_v_parent_idx` ON `_blog_posts_v` (`parent_id`)",
  "CREATE INDEX `_blog_posts_v_published_locale_idx` ON `_blog_posts_v` (`published_locale`)",
  "CREATE INDEX `_blog_posts_v_rels_blog_posts_id_idx` ON `_blog_posts_v_rels` (`blog_posts_id`)",
  "CREATE INDEX `_blog_posts_v_rels_order_idx` ON `_blog_posts_v_rels` (`order`)",
  "CREATE INDEX `_blog_posts_v_rels_parent_idx` ON `_blog_posts_v_rels` (`parent_id`)",
  "CREATE INDEX `_blog_posts_v_rels_path_idx` ON `_blog_posts_v_rels` (`path`)",
  "CREATE INDEX `_blog_posts_v_snapshot_idx` ON `_blog_posts_v` (`snapshot`)",
  "CREATE INDEX `_blog_posts_v_updated_at_idx` ON `_blog_posts_v` (`updated_at`)",
  "CREATE INDEX `_blog_posts_v_version_sections_locale_idx` ON `_blog_posts_v_version_sections` (`_locale`)",
  "CREATE INDEX `_blog_posts_v_version_sections_order_idx` ON `_blog_posts_v_version_sections` (`_order`)",
  "CREATE INDEX `_blog_posts_v_version_sections_parent_id_idx` ON `_blog_posts_v_version_sections` (`_parent_id`)",
  "CREATE INDEX `_blog_posts_v_version_tags_order_idx` ON `_blog_posts_v_version_tags` (`_order`)",
  "CREATE INDEX `_blog_posts_v_version_tags_parent_id_idx` ON `_blog_posts_v_version_tags` (`_parent_id`)",
  "CREATE INDEX `_blog_posts_v_version_version__status_idx` ON `_blog_posts_v` (`version__status`)",
  "CREATE INDEX `_blog_posts_v_version_version_cover_idx` ON `_blog_posts_v` (`version_cover_id`)",
  "CREATE INDEX `_blog_posts_v_version_version_created_at_idx` ON `_blog_posts_v` (`version_created_at`)",
  "CREATE INDEX `_blog_posts_v_version_version_slug_idx` ON `_blog_posts_v` (`version_slug`)",
  "CREATE INDEX `_blog_posts_v_version_version_updated_at_idx` ON `_blog_posts_v` (`version_updated_at`)",
  "CREATE INDEX `_faqs_v_created_at_idx` ON `_faqs_v` (`created_at`)",
  "CREATE INDEX `_faqs_v_latest_idx` ON `_faqs_v` (`latest`)",
  "CREATE UNIQUE INDEX `_faqs_v_locales_locale_parent_id_unique` ON `_faqs_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_faqs_v_parent_idx` ON `_faqs_v` (`parent_id`)",
  "CREATE INDEX `_faqs_v_published_locale_idx` ON `_faqs_v` (`published_locale`)",
  "CREATE INDEX `_faqs_v_snapshot_idx` ON `_faqs_v` (`snapshot`)",
  "CREATE INDEX `_faqs_v_updated_at_idx` ON `_faqs_v` (`updated_at`)",
  "CREATE INDEX `_faqs_v_version_version__status_idx` ON `_faqs_v` (`version__status`)",
  "CREATE INDEX `_faqs_v_version_version_created_at_idx` ON `_faqs_v` (`version_created_at`)",
  "CREATE INDEX `_faqs_v_version_version_updated_at_idx` ON `_faqs_v` (`version_updated_at`)",
  "CREATE INDEX `_homepage_v_created_at_idx` ON `_homepage_v` (`created_at`)",
  "CREATE UNIQUE INDEX `_homepage_v_locales_locale_parent_id_unique` ON `_homepage_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_homepage_v_updated_at_idx` ON `_homepage_v` (`updated_at`)",
  "CREATE INDEX `_homepage_v_version_conversation_locale_idx` ON `_homepage_v_version_conversation` (`_locale`)",
  "CREATE INDEX `_homepage_v_version_conversation_order_idx` ON `_homepage_v_version_conversation` (`_order`)",
  "CREATE INDEX `_homepage_v_version_conversation_parent_id_idx` ON `_homepage_v_version_conversation` (`_parent_id`)",
  "CREATE INDEX `_homepage_v_version_stages_locale_idx` ON `_homepage_v_version_stages` (`_locale`)",
  "CREATE INDEX `_homepage_v_version_stages_order_idx` ON `_homepage_v_version_stages` (`_order`)",
  "CREATE INDEX `_homepage_v_version_stages_parent_id_idx` ON `_homepage_v_version_stages` (`_parent_id`)",
  "CREATE INDEX `_homepage_v_version_trust_items_locale_idx` ON `_homepage_v_version_trust_items` (`_locale`)",
  "CREATE INDEX `_homepage_v_version_trust_items_order_idx` ON `_homepage_v_version_trust_items` (`_order`)",
  "CREATE INDEX `_homepage_v_version_trust_items_parent_id_idx` ON `_homepage_v_version_trust_items` (`_parent_id`)",
  "CREATE INDEX `_industries_v_created_at_idx` ON `_industries_v` (`created_at`)",
  "CREATE INDEX `_industries_v_latest_idx` ON `_industries_v` (`latest`)",
  "CREATE UNIQUE INDEX `_industries_v_locales_locale_parent_id_unique` ON `_industries_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_industries_v_parent_idx` ON `_industries_v` (`parent_id`)",
  "CREATE INDEX `_industries_v_published_locale_idx` ON `_industries_v` (`published_locale`)",
  "CREATE INDEX `_industries_v_snapshot_idx` ON `_industries_v` (`snapshot`)",
  "CREATE INDEX `_industries_v_updated_at_idx` ON `_industries_v` (`updated_at`)",
  "CREATE INDEX `_industries_v_version_version__status_idx` ON `_industries_v` (`version__status`)",
  "CREATE INDEX `_industries_v_version_version_created_at_idx` ON `_industries_v` (`version_created_at`)",
  "CREATE INDEX `_industries_v_version_version_updated_at_idx` ON `_industries_v` (`version_updated_at`)",
  "CREATE INDEX `_projects_v_autosave_idx` ON `_projects_v` (`autosave`)",
  "CREATE INDEX `_projects_v_created_at_idx` ON `_projects_v` (`created_at`)",
  "CREATE INDEX `_projects_v_latest_idx` ON `_projects_v` (`latest`)",
  "CREATE UNIQUE INDEX `_projects_v_locales_locale_parent_id_unique` ON `_projects_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_projects_v_parent_idx` ON `_projects_v` (`parent_id`)",
  "CREATE INDEX `_projects_v_published_locale_idx` ON `_projects_v` (`published_locale`)",
  "CREATE INDEX `_projects_v_snapshot_idx` ON `_projects_v` (`snapshot`)",
  "CREATE INDEX `_projects_v_updated_at_idx` ON `_projects_v` (`updated_at`)",
  "CREATE INDEX `_projects_v_version_sections_locale_idx` ON `_projects_v_version_sections` (`_locale`)",
  "CREATE INDEX `_projects_v_version_sections_order_idx` ON `_projects_v_version_sections` (`_order`)",
  "CREATE INDEX `_projects_v_version_sections_parent_id_idx` ON `_projects_v_version_sections` (`_parent_id`)",
  "CREATE INDEX `_projects_v_version_technologies_order_idx` ON `_projects_v_version_technologies` (`_order`)",
  "CREATE INDEX `_projects_v_version_technologies_parent_id_idx` ON `_projects_v_version_technologies` (`_parent_id`)",
  "CREATE INDEX `_projects_v_version_version__status_idx` ON `_projects_v` (`version__status`)",
  "CREATE INDEX `_projects_v_version_version_created_at_idx` ON `_projects_v` (`version_created_at`)",
  "CREATE INDEX `_projects_v_version_version_image_idx` ON `_projects_v` (`version_image_id`)",
  "CREATE INDEX `_projects_v_version_version_slug_idx` ON `_projects_v` (`version_slug`)",
  "CREATE INDEX `_projects_v_version_version_updated_at_idx` ON `_projects_v` (`version_updated_at`)",
  "CREATE INDEX `_services_v_created_at_idx` ON `_services_v` (`created_at`)",
  "CREATE INDEX `_services_v_latest_idx` ON `_services_v` (`latest`)",
  "CREATE UNIQUE INDEX `_services_v_locales_locale_parent_id_unique` ON `_services_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_services_v_parent_idx` ON `_services_v` (`parent_id`)",
  "CREATE INDEX `_services_v_published_locale_idx` ON `_services_v` (`published_locale`)",
  "CREATE INDEX `_services_v_snapshot_idx` ON `_services_v` (`snapshot`)",
  "CREATE INDEX `_services_v_updated_at_idx` ON `_services_v` (`updated_at`)",
  "CREATE INDEX `_services_v_version_version__status_idx` ON `_services_v` (`version__status`)",
  "CREATE INDEX `_services_v_version_version_created_at_idx` ON `_services_v` (`version_created_at`)",
  "CREATE INDEX `_services_v_version_version_updated_at_idx` ON `_services_v` (`version_updated_at`)",
  "CREATE INDEX `_site_settings_v_created_at_idx` ON `_site_settings_v` (`created_at`)",
  "CREATE UNIQUE INDEX `_site_settings_v_locales_locale_parent_id_unique` ON `_site_settings_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_site_settings_v_updated_at_idx` ON `_site_settings_v` (`updated_at`)",
  "CREATE INDEX `_site_settings_v_version_version_founder_photo_idx` ON `_site_settings_v` (`version_founder_photo_id`)",
  "CREATE INDEX `_technologies_v_created_at_idx` ON `_technologies_v` (`created_at`)",
  "CREATE INDEX `_technologies_v_latest_idx` ON `_technologies_v` (`latest`)",
  "CREATE UNIQUE INDEX `_technologies_v_locales_locale_parent_id_unique` ON `_technologies_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_technologies_v_parent_idx` ON `_technologies_v` (`parent_id`)",
  "CREATE INDEX `_technologies_v_published_locale_idx` ON `_technologies_v` (`published_locale`)",
  "CREATE INDEX `_technologies_v_snapshot_idx` ON `_technologies_v` (`snapshot`)",
  "CREATE INDEX `_technologies_v_updated_at_idx` ON `_technologies_v` (`updated_at`)",
  "CREATE INDEX `_technologies_v_version_version__status_idx` ON `_technologies_v` (`version__status`)",
  "CREATE INDEX `_technologies_v_version_version_created_at_idx` ON `_technologies_v` (`version_created_at`)",
  "CREATE INDEX `_technologies_v_version_version_updated_at_idx` ON `_technologies_v` (`version_updated_at`)",
  "CREATE INDEX `_testimonials_v_created_at_idx` ON `_testimonials_v` (`created_at`)",
  "CREATE INDEX `_testimonials_v_latest_idx` ON `_testimonials_v` (`latest`)",
  "CREATE UNIQUE INDEX `_testimonials_v_locales_locale_parent_id_unique` ON `_testimonials_v_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `_testimonials_v_parent_idx` ON `_testimonials_v` (`parent_id`)",
  "CREATE INDEX `_testimonials_v_published_locale_idx` ON `_testimonials_v` (`published_locale`)",
  "CREATE INDEX `_testimonials_v_snapshot_idx` ON `_testimonials_v` (`snapshot`)",
  "CREATE INDEX `_testimonials_v_updated_at_idx` ON `_testimonials_v` (`updated_at`)",
  "CREATE INDEX `_testimonials_v_version_version__status_idx` ON `_testimonials_v` (`version__status`)",
  "CREATE INDEX `_testimonials_v_version_version_avatar_idx` ON `_testimonials_v` (`version_avatar_id`)",
  "CREATE INDEX `_testimonials_v_version_version_created_at_idx` ON `_testimonials_v` (`version_created_at`)",
  "CREATE INDEX `_testimonials_v_version_version_logo_idx` ON `_testimonials_v` (`version_logo_id`)",
  "CREATE INDEX `_testimonials_v_version_version_updated_at_idx` ON `_testimonials_v` (`version_updated_at`)",
  "CREATE INDEX `blog_posts__status_idx` ON `blog_posts` (`_status`)",
  "CREATE INDEX `blog_posts_cover_idx` ON `blog_posts` (`cover_id`)",
  "CREATE INDEX `blog_posts_created_at_idx` ON `blog_posts` (`created_at`)",
  "CREATE UNIQUE INDEX `blog_posts_locales_locale_parent_id_unique` ON `blog_posts_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `blog_posts_rels_blog_posts_id_idx` ON `blog_posts_rels` (`blog_posts_id`)",
  "CREATE INDEX `blog_posts_rels_order_idx` ON `blog_posts_rels` (`order`)",
  "CREATE INDEX `blog_posts_rels_parent_idx` ON `blog_posts_rels` (`parent_id`)",
  "CREATE INDEX `blog_posts_rels_path_idx` ON `blog_posts_rels` (`path`)",
  "CREATE INDEX `blog_posts_sections_locale_idx` ON `blog_posts_sections` (`_locale`)",
  "CREATE INDEX `blog_posts_sections_order_idx` ON `blog_posts_sections` (`_order`)",
  "CREATE INDEX `blog_posts_sections_parent_id_idx` ON `blog_posts_sections` (`_parent_id`)",
  "CREATE UNIQUE INDEX `blog_posts_slug_idx` ON `blog_posts` (`slug`)",
  "CREATE INDEX `blog_posts_tags_order_idx` ON `blog_posts_tags` (`_order`)",
  "CREATE INDEX `blog_posts_tags_parent_id_idx` ON `blog_posts_tags` (`_parent_id`)",
  "CREATE INDEX `blog_posts_updated_at_idx` ON `blog_posts` (`updated_at`)",
  "CREATE UNIQUE INDEX `contact_settings_locales_locale_parent_id_unique` ON `contact_settings_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `faqs__status_idx` ON `faqs` (`_status`)",
  "CREATE INDEX `faqs_created_at_idx` ON `faqs` (`created_at`)",
  "CREATE UNIQUE INDEX `faqs_locales_locale_parent_id_unique` ON `faqs_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `faqs_updated_at_idx` ON `faqs` (`updated_at`)",
  "CREATE INDEX `footer_links_locale_idx` ON `footer_links` (`_locale`)",
  "CREATE INDEX `footer_links_order_idx` ON `footer_links` (`_order`)",
  "CREATE INDEX `footer_links_parent_id_idx` ON `footer_links` (`_parent_id`)",
  "CREATE UNIQUE INDEX `footer_locales_locale_parent_id_unique` ON `footer_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `form_attempts_created_at_idx` ON `form_attempts` (`created_at`)",
  "CREATE INDEX `form_attempts_expires_at_idx` ON `form_attempts` (`expires_at`)",
  "CREATE UNIQUE INDEX `form_attempts_key_idx` ON `form_attempts` (`key`)",
  "CREATE INDEX `form_attempts_updated_at_idx` ON `form_attempts` (`updated_at`)",
  "CREATE INDEX `homepage_conversation_locale_idx` ON `homepage_conversation` (`_locale`)",
  "CREATE INDEX `homepage_conversation_order_idx` ON `homepage_conversation` (`_order`)",
  "CREATE INDEX `homepage_conversation_parent_id_idx` ON `homepage_conversation` (`_parent_id`)",
  "CREATE UNIQUE INDEX `homepage_locales_locale_parent_id_unique` ON `homepage_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `homepage_stages_locale_idx` ON `homepage_stages` (`_locale`)",
  "CREATE INDEX `homepage_stages_order_idx` ON `homepage_stages` (`_order`)",
  "CREATE INDEX `homepage_stages_parent_id_idx` ON `homepage_stages` (`_parent_id`)",
  "CREATE INDEX `homepage_trust_items_locale_idx` ON `homepage_trust_items` (`_locale`)",
  "CREATE INDEX `homepage_trust_items_order_idx` ON `homepage_trust_items` (`_order`)",
  "CREATE INDEX `homepage_trust_items_parent_id_idx` ON `homepage_trust_items` (`_parent_id`)",
  "CREATE INDEX `industries__status_idx` ON `industries` (`_status`)",
  "CREATE INDEX `industries_created_at_idx` ON `industries` (`created_at`)",
  "CREATE UNIQUE INDEX `industries_locales_locale_parent_id_unique` ON `industries_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `industries_updated_at_idx` ON `industries` (`updated_at`)",
  "CREATE INDEX `leads_attachment_idx` ON `leads` (`attachment_id`)",
  "CREATE INDEX `leads_created_at_idx` ON `leads` (`created_at`)",
  "CREATE UNIQUE INDEX `leads_submission_key_idx` ON `leads` (`submission_key`)",
  "CREATE INDEX `leads_updated_at_idx` ON `leads` (`updated_at`)",
  "CREATE INDEX `media_created_at_idx` ON `media` (`created_at`)",
  "CREATE UNIQUE INDEX `media_filename_idx` ON `media` (`filename`)",
  "CREATE UNIQUE INDEX `media_locales_locale_parent_id_unique` ON `media_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `media_sizes_large_sizes_large_filename_idx` ON `media` (`sizes_large_filename`)",
  "CREATE INDEX `media_sizes_thumbnail_sizes_thumbnail_filename_idx` ON `media` (`sizes_thumbnail_filename`)",
  "CREATE INDEX `media_updated_at_idx` ON `media` (`updated_at`)",
  "CREATE INDEX `navigation_links_locale_idx` ON `navigation_links` (`_locale`)",
  "CREATE INDEX `navigation_links_order_idx` ON `navigation_links` (`_order`)",
  "CREATE INDEX `navigation_links_parent_id_idx` ON `navigation_links` (`_parent_id`)",
  "CREATE UNIQUE INDEX `navigation_locales_locale_parent_id_unique` ON `navigation_locales` (`_locale`,`_parent_id`)",
  "CREATE UNIQUE INDEX `payload_kv_key_idx` ON `payload_kv` (`key`)",
  "CREATE INDEX `payload_locked_documents_created_at_idx` ON `payload_locked_documents` (`created_at`)",
  "CREATE INDEX `payload_locked_documents_global_slug_idx` ON `payload_locked_documents` (`global_slug`)",
  "CREATE INDEX `payload_locked_documents_rels_blog_posts_id_idx` ON `payload_locked_documents_rels` (`blog_posts_id`)",
  "CREATE INDEX `payload_locked_documents_rels_faqs_id_idx` ON `payload_locked_documents_rels` (`faqs_id`)",
  "CREATE INDEX `payload_locked_documents_rels_form_attempts_id_idx` ON `payload_locked_documents_rels` (`form_attempts_id`)",
  "CREATE INDEX `payload_locked_documents_rels_industries_id_idx` ON `payload_locked_documents_rels` (`industries_id`)",
  "CREATE INDEX `payload_locked_documents_rels_leads_id_idx` ON `payload_locked_documents_rels` (`leads_id`)",
  "CREATE INDEX `payload_locked_documents_rels_media_id_idx` ON `payload_locked_documents_rels` (`media_id`)",
  "CREATE INDEX `payload_locked_documents_rels_order_idx` ON `payload_locked_documents_rels` (`order`)",
  "CREATE INDEX `payload_locked_documents_rels_parent_idx` ON `payload_locked_documents_rels` (`parent_id`)",
  "CREATE INDEX `payload_locked_documents_rels_path_idx` ON `payload_locked_documents_rels` (`path`)",
  "CREATE INDEX `payload_locked_documents_rels_private_files_id_idx` ON `payload_locked_documents_rels` (`private_files_id`)",
  "CREATE INDEX `payload_locked_documents_rels_projects_id_idx` ON `payload_locked_documents_rels` (`projects_id`)",
  "CREATE INDEX `payload_locked_documents_rels_services_id_idx` ON `payload_locked_documents_rels` (`services_id`)",
  "CREATE INDEX `payload_locked_documents_rels_technologies_id_idx` ON `payload_locked_documents_rels` (`technologies_id`)",
  "CREATE INDEX `payload_locked_documents_rels_testimonials_id_idx` ON `payload_locked_documents_rels` (`testimonials_id`)",
  "CREATE INDEX `payload_locked_documents_rels_users_id_idx` ON `payload_locked_documents_rels` (`users_id`)",
  "CREATE INDEX `payload_locked_documents_updated_at_idx` ON `payload_locked_documents` (`updated_at`)",
  "CREATE INDEX `payload_preferences_created_at_idx` ON `payload_preferences` (`created_at`)",
  "CREATE INDEX `payload_preferences_key_idx` ON `payload_preferences` (`key`)",
  "CREATE INDEX `payload_preferences_rels_order_idx` ON `payload_preferences_rels` (`order`)",
  "CREATE INDEX `payload_preferences_rels_parent_idx` ON `payload_preferences_rels` (`parent_id`)",
  "CREATE INDEX `payload_preferences_rels_path_idx` ON `payload_preferences_rels` (`path`)",
  "CREATE INDEX `payload_preferences_rels_users_id_idx` ON `payload_preferences_rels` (`users_id`)",
  "CREATE INDEX `payload_migrations_updated_at_idx` ON `payload_migrations` (`updated_at`)",
  "CREATE INDEX `payload_migrations_created_at_idx` ON `payload_migrations` (`created_at`)",
  "CREATE INDEX `payload_preferences_updated_at_idx` ON `payload_preferences` (`updated_at`)",
  "CREATE INDEX `private_files_created_at_idx` ON `private_files` (`created_at`)",
  "CREATE UNIQUE INDEX `private_files_filename_idx` ON `private_files` (`filename`)",
  "CREATE UNIQUE INDEX `private_files_submission_key_idx` ON `private_files` (`submission_key`)",
  "CREATE INDEX `private_files_updated_at_idx` ON `private_files` (`updated_at`)",
  "CREATE INDEX `projects__status_idx` ON `projects` (`_status`)",
  "CREATE INDEX `projects_created_at_idx` ON `projects` (`created_at`)",
  "CREATE INDEX `projects_image_idx` ON `projects` (`image_id`)",
  "CREATE UNIQUE INDEX `projects_locales_locale_parent_id_unique` ON `projects_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `projects_sections_locale_idx` ON `projects_sections` (`_locale`)",
  "CREATE INDEX `projects_sections_order_idx` ON `projects_sections` (`_order`)",
  "CREATE INDEX `projects_sections_parent_id_idx` ON `projects_sections` (`_parent_id`)",
  "CREATE UNIQUE INDEX `projects_slug_idx` ON `projects` (`slug`)",
  "CREATE INDEX `projects_technologies_order_idx` ON `projects_technologies` (`_order`)",
  "CREATE INDEX `projects_technologies_parent_id_idx` ON `projects_technologies` (`_parent_id`)",
  "CREATE INDEX `projects_updated_at_idx` ON `projects` (`updated_at`)",
  "CREATE UNIQUE INDEX `seo_locales_locale_parent_id_unique` ON `seo_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `seo_og_image_idx` ON `seo` (`og_image_id`)",
  "CREATE INDEX `services__status_idx` ON `services` (`_status`)",
  "CREATE INDEX `services_created_at_idx` ON `services` (`created_at`)",
  "CREATE UNIQUE INDEX `services_locales_locale_parent_id_unique` ON `services_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `services_updated_at_idx` ON `services` (`updated_at`)",
  "CREATE INDEX `site_settings_founder_photo_idx` ON `site_settings` (`founder_photo_id`)",
  "CREATE UNIQUE INDEX `site_settings_locales_locale_parent_id_unique` ON `site_settings_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `social_links_links_locale_idx` ON `social_links_links` (`_locale`)",
  "CREATE INDEX `social_links_links_order_idx` ON `social_links_links` (`_order`)",
  "CREATE INDEX `social_links_links_parent_id_idx` ON `social_links_links` (`_parent_id`)",
  "CREATE INDEX `technologies__status_idx` ON `technologies` (`_status`)",
  "CREATE INDEX `technologies_created_at_idx` ON `technologies` (`created_at`)",
  "CREATE UNIQUE INDEX `technologies_locales_locale_parent_id_unique` ON `technologies_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `technologies_updated_at_idx` ON `technologies` (`updated_at`)",
  "CREATE INDEX `testimonials__status_idx` ON `testimonials` (`_status`)",
  "CREATE INDEX `testimonials_avatar_idx` ON `testimonials` (`avatar_id`)",
  "CREATE INDEX `testimonials_created_at_idx` ON `testimonials` (`created_at`)",
  "CREATE UNIQUE INDEX `testimonials_locales_locale_parent_id_unique` ON `testimonials_locales` (`_locale`,`_parent_id`)",
  "CREATE INDEX `testimonials_logo_idx` ON `testimonials` (`logo_id`)",
  "CREATE INDEX `testimonials_updated_at_idx` ON `testimonials` (`updated_at`)",
  "CREATE INDEX `users_created_at_idx` ON `users` (`created_at`)",
  "CREATE UNIQUE INDEX `users_email_idx` ON `users` (`email`)",
  "CREATE INDEX `users_sessions_order_idx` ON `users_sessions` (`_order`)",
  "CREATE INDEX `users_sessions_parent_id_idx` ON `users_sessions` (`_parent_id`)",
  "CREATE INDEX `users_updated_at_idx` ON `users` (`updated_at`)"
]
export async function up({db}:MigrateUpArgs):Promise<void>{for(const statement of statements)await db.run(sql.raw(statement))}
export async function down(_args:MigrateDownArgs):Promise<void>{throw new Error('Destructive schema rollback is disabled. Restore the matching verified backup and image instead.')}
