import type {Article,Locale} from '@/types/site'
const sharedDate='2026-09-23T10:00:00.000Z'
export const defaultArticles:Record<Locale,Article[]>={pl:[
 {id:'first-note',slug:'od-problemu-do-dobrego-systemu',title:'Zanim powstanie system, nazwij problem.',excerpt:'Najlepszym początkiem projektu nie jest lista funkcji. Jest nim zrozumienie pracy, która dzisiaj zabiera za dużo czasu.',author:'CodeMaster',publishedAt:sharedDate,sections:[
  {heading:'Zacznij od jednego dnia pracy',body:'Opisz konkretny proces od początku do końca. Kto go rozpoczyna? Jakie dane są potrzebne? Gdzie informacje trzeba wpisać drugi raz? W którym miejscu ktoś czeka na decyzję? Taka rozmowa często mówi o potrzebnym systemie więcej niż długa lista ekranów.'},
  {heading:'Oddziel problem od pierwszego pomysłu',body:'„Potrzebujemy aplikacji” to propozycja rozwiązania. „Nie wiemy, która wersja dokumentu jest aktualna” to problem, który można sprawdzić. Wybór powinien wynikać z kontekstu, a nie z atrakcyjności technologii.'},
  {heading:'Pokaż kierunek przed pełną realizacją',body:'Wersja demonstracyjna pozwala rozmawiać o konkretnych zachowaniach: co widzi pracownik, jak zatwierdza się dokument i co dzieje się po błędzie. Demo nie jest jeszcze produkcyjnym systemem. Jego zadaniem jest sprawdzenie wspólnego zrozumienia.'},
  {heading:'Uzgodnij, co oznacza gotowe',body:'W zakresie powinny znaleźć się nie tylko ekrany, lecz także role, dane, integracje, obsługa błędów, sposób wdrożenia i odbioru. Warto ustalić odpowiedzialność za hosting, kopie zapasowe i monitoring.'},
  {heading:'Oceniaj rezultat, nie liczbę funkcji',body:'Właściwe pytanie brzmi: czy praca stała się prostsza? Kryterium może być mniej ręcznego przepisywania danych, krótszy czas odpowiedzi albo mniej pomyłek.'}
 ]},
 {id:'approval-note',slug:'agent-ai-i-human-approval',title:'Dobry agent AI wie, kiedy zapytać.',excerpt:'Automatyzacja nie musi oznaczać utraty kontroli. Human approval, audit trail i jasne granice są częścią projektu produktu.',author:'CodeMaster',publishedAt:'2026-09-20T10:00:00.000Z',sections:[
  {heading:'Najpierw klasyfikuj ryzyko',body:'Nie każda akcja wymaga takiego samego poziomu kontroli. Odczyt danych, przygotowanie szkicu i wykonanie nieodwracalnej operacji to trzy różne klasy ryzyka.'},
  {heading:'Oddziel propozycję od wykonania',body:'Agent może zebrać kontekst i przygotować rekomendację. Wykonanie może pozostać za świadomą decyzją użytkownika. Dzięki temu automatyzacja przyspiesza pracę bez ukrywania odpowiedzialności.'},
  {heading:'Pokaż kontekst decyzji',body:'Ekran approval powinien jasno pokazać, co agent chce zrobić, z jakich danych korzysta i jaki będzie efekt. Użytkownik nie powinien zatwierdzać „magicznego” przycisku bez informacji.'},
  {heading:'Zapisuj audit trail',body:'Kto zaproponował akcję, kto ją zatwierdził i co faktycznie wykonano — te informacje są niezbędne w procesach biznesowych.'},
  {heading:'Automatyzacja to produkt, nie demo modelu',body:'Największa wartość powstaje wtedy, gdy agent jest częścią realnego workflow: kolejki, uprawnień, danych, błędów i obsługi wyjątków.'}
 ]},
 {id:'demo-note',slug:'demo-przed-realizacja',title:'Nie kupuj obietnicy. Sprawdź kierunek.',excerpt:'Funkcjonalne demo zmienia rozmowę z „jak to sobie wyobrażamy” na „czy właśnie tak powinien działać produkt”.',author:'CodeMaster',publishedAt:'2026-09-17T10:00:00.000Z',sections:[
  {heading:'Demo ma odpowiedzieć na konkretne pytanie',body:'Dobre demo nie próbuje udawać całego produktu. Powinno sprawdzić najważniejszy przepływ i decyzje, które są kosztowne do zmiany później.'},
  {heading:'Klikalne znaczy więcej niż ładne',body:'Statyczny ekran potrafi wyglądać świetnie, a mimo to nie odpowiadać na pytania o stany, błędy, uprawnienia czy zachowanie na telefonie. Funkcjonalny prototyp ujawnia te rzeczy szybciej.'},
  {heading:'Oddziel demo od produkcji',body:'Demo powinno być jasno oznaczone. Nie należy udawać produkcyjnej integracji, danych klienta ani wdrożenia, jeżeli ich nie ma.'},
  {heading:'Zbieraj feedback w kontekście',body:'Komentarz do konkretnego widoku lub wersji jest bardziej użyteczny niż ogólne „podoba mi się”. Warto zapisywać decyzje i pokazywać, co zmieniło się między wersjami.'},
  {heading:'Dopiero potem zamykaj zakres',body:'Gdy kierunek jest wspólnie rozumiany, łatwiej ustalić zakres, ryzyka, harmonogram i kryteria odbioru.'}
 ]}
],en:[
 {id:'first-note',slug:'od-problemu-do-dobrego-systemu',title:'Before building a system, name the problem.',excerpt:'The best place to start is not a feature list. It is understanding the work that currently takes too much effort.',author:'CodeMaster',publishedAt:sharedDate,sections:[{heading:'Start with an ordinary working day',body:'Follow one process from beginning to end. Who starts it? Which data is required? Where is the same information entered twice?'},{heading:'Separate the problem from the first idea',body:'“We need an app” is a proposed solution. “We cannot tell which document is current” is a problem that can be investigated.'},{heading:'Make the direction tangible',body:'A demonstration lets the team discuss specific behaviour before committing to the full build.'},{heading:'Agree on what done means',body:'Scope should include permissions, data, integrations, errors, deployment and acceptance, not just screens.'},{heading:'Evaluate the result, not the feature count',body:'The useful question is whether work became easier and more reliable.'}]},
 {id:'approval-note',slug:'agent-ai-i-human-approval',title:'A good AI agent knows when to ask.',excerpt:'Automation does not have to mean losing control. Human approval, an audit trail and explicit boundaries are product decisions.',author:'CodeMaster',publishedAt:'2026-09-20T10:00:00.000Z',sections:[{heading:'Classify risk first',body:'Reading data, preparing a draft and executing an irreversible action are different risk classes.'},{heading:'Separate proposal from execution',body:'An agent can gather context and prepare a recommendation while execution stays behind a conscious user decision.'},{heading:'Expose decision context',body:'Approval UI should show what will happen, which data was used and what the outcome will be.'},{heading:'Keep an audit trail',body:'Record who proposed, approved and executed each action.'},{heading:'Automation is a product workflow',body:'Value comes from integrating the agent with queues, permissions, data, errors and exceptions.'}]},
 {id:'demo-note',slug:'demo-przed-realizacja',title:'Do not buy a promise. Test the direction.',excerpt:'A functional demo changes the conversation from “how we imagine it” to “should the product behave like this?”.',author:'CodeMaster',publishedAt:'2026-09-17T10:00:00.000Z',sections:[{heading:'A demo should answer a question',body:'Do not imitate the whole product. Test the most important flow and expensive decisions.'},{heading:'Clickable reveals more than pretty',body:'A static screen cannot expose states, errors, permissions or mobile behaviour.'},{heading:'Separate demo from production',body:'Clearly label demonstration data and integrations.'},{heading:'Collect feedback in context',body:'Feedback attached to a concrete view or version is much more actionable.'},{heading:'Lock the scope afterwards',body:'Once direction is shared, scope, risks and acceptance criteria become much clearer.'}]}
]}
