'use client'

import {useEffect,useState} from 'react'
import type {ProjectProps} from '../../project-data'
import './velo.css'

type ModelKey='AERO 01'|'ALLROAD 02'|'CITY 03'
type FinishKey='acid'|'silver'|'carbon'
const models:{id:ModelKey;price:number;image:string;type:{pl:string;en:string};desc:{pl:string;en:string};spec:string}[]=[
 {id:'AERO 01',price:18900,image:'/images/showcase/velo-bike.jpg',type:{pl:'SZOSA / WYŚCIG',en:'ROAD / RACE'},desc:{pl:'Czysta prędkość. Każda linia stworzona, by przecinać powietrze.',en:'Pure velocity. Every line shaped to cut through air.'},spec:'8.1 KG'},
 {id:'ALLROAD 02',price:16500,image:'/images/showcase/velo-allroad.jpg',type:{pl:'GRAVEL / ODKRYWANIE',en:'GRAVEL / EXPLORE'},desc:{pl:'Asfalt się kończy. Możliwości dopiero się zaczynają.',en:'The tarmac ends. The possibilities begin.'},spec:'9.4 KG'},
 {id:'CITY 03',price:12900,image:'/images/showcase/velo-city.jpg',type:{pl:'MIASTO / RUCH',en:'CITY / MOTION'},desc:{pl:'Codzienna droga, która nigdy nie jest zwyczajna.',en:'The everyday journey, never ordinary.'},spec:'10.2 KG'},
]
const finishes:{id:FinishKey;hex:string;label:{pl:string;en:string};extra:number;bg:string;filter:string}[]=[
 {id:'acid',hex:'#d8ff45',label:{pl:'Volt / limonka',en:'Volt / citron'},extra:0,bg:'#d8ff45',filter:'none'},
 {id:'silver',hex:'#b9beb7',label:{pl:'Surowe srebro',en:'Raw silver'},extra:350,bg:'#c7cec8',filter:'grayscale(1) contrast(.95)'},
 {id:'carbon',hex:'#252b29',label:{pl:'Nocny karbon',en:'Night carbon'},extra:690,bg:'#a4aaa0',filter:'grayscale(1) brightness(.64) contrast(1.25)'},
]
const copy={
 pl:{nav:['Kolekcja','Filozofia','Konfigurator'],navCta:'Zbuduj swój rower',heroTop:'STWORZONE DO RUCHU / 2026',hero:'JEDŹ PO SWOJEMU.',heroSub:'Nie czekaj na idealne warunki. Zrób z każdej drogi swoją.',heroLink:'Odkryj kolekcję',ticker:'SZYBKOŚĆ JEST WYBOREM',introLabel:'01 / NASZA IDEA',introA:'DALEJ.',introB:'SZYBCIEJ.',introC:'PO SWOJEMU.',introText:'Projektujemy rowery dla tych, którzy wolą poczuć drogę niż patrzeć na nią z boku. Precyzja inżynierii. Wolność w każdym zakręcie.',collection:'MASZYNY RUCHU.',collectionSub:'Trzy charaktery. Jeden powód, by wyjść z domu.',from:'OD',discover:'Konfiguruj',manifestoLabel:'02 / POZA PLANEM',manifestoA:'DROGA NIE',manifestoB:'MA KOŃCA.',manifestoText:'Wierzymy w poranki bez celu, podjazdy bez wymówek i ten moment, kiedy ciało nadąża za myślami. Mniej granic. Więcej kilometrów.',manifestoLink:'Zbuduj swój zestaw',configLabel:'03 / TWOJA MASZYNA',config:'USTAW TEMPO.',configSub:'Wybierz bazę. Dopasuj rozmiar. Nadaj jej własny kolor. Reszta należy do drogi.',configNo:'WERSJA',choose:'Zacznij od wyboru',model:'Model',size:'Rozmiar ramy',sizeNote:'Przykładowy dobór: 52 (163–172 cm), 54 (170–180 cm), 56 (178–188 cm), 58 (185–195 cm). Ostateczne dopasowanie wymaga profesjonalnego bike fittingu.',finish:'Wykończenie',summary:'Twój zestaw',base:'Rower bazowy',finishCost:'Wykończenie',total:'Cena orientacyjna',priceNote:'To demonstracyjna konfiguracja i cena orientacyjna, bez składania zamówienia ani płatności.',save:'Zapisz w przeglądarce',download:'Pobierz specyfikację ↓',saved:'Zestaw zapisany na tym urządzeniu.',restored:'Przywrócono zapisany zestaw.',specLabel:'04 / DLACZEGO VÉLO',spec:'KAŻDY DETAL MA ZNACZENIE.',specItems:[['01','Geometria, która odpowiada na każdy ruch.'],['02','Materiały wybrane dla lekkości i wytrzymałości.'],['03','Prosta forma. Niczego więcej nie potrzebujesz.']],endLabel:'TWOJA DROGA ZACZYNA SIĘ TUTAJ',endA:'RUSZAJ.',endB:'TERAZ.',endText:'Nie ma lepszego momentu niż ten, w którym jesteś.',endLink:'Skonfiguruj rower',footer:'VÉLO / ATELIER RUCHU',top:'Do góry ↑',currency:'zł',menu:'Menu',close:'Zamknij'},
 en:{nav:['Collection','Philosophy','Configurator'],navCta:'Build your bike',heroTop:'BUILT FOR MOTION / 2026',hero:'RIDE YOUR OWN WAY.',heroSub:'Stop waiting for perfect conditions. Make every road yours.',heroLink:'Explore the collection',ticker:'SPEED IS A CHOICE',introLabel:'01 / OUR IDEA',introA:'FURTHER.',introB:'FASTER.',introC:'YOUR WAY.',introText:'We make bikes for those who would rather feel the road than watch from the sidelines. Engineering precision. Freedom in every turn.',collection:'MOTION MACHINES.',collectionSub:'Three personalities. One reason to get out there.',from:'FROM',discover:'Configure',manifestoLabel:'02 / BEYOND THE PLAN',manifestoA:'THE ROAD',manifestoB:'GOES ON.',manifestoText:'We believe in mornings without a destination, climbs without excuses, and that moment when your body catches up with your thoughts. Fewer limits. More miles.',manifestoLink:'Build your setup',configLabel:'03 / YOUR MACHINE',config:'SET YOUR PACE.',configSub:'Pick your base. Find your fit. Give it your own finish. The rest belongs to the road.',configNo:'EDITION',choose:'Make your choices',model:'Model',size:'Frame size',sizeNote:'Illustrative fit: 52 (163–172 cm), 54 (170–180 cm), 56 (178–188 cm), 58 (185–195 cm). Final sizing requires a professional bike fitting.',finish:'Finish',summary:'Your setup',base:'Base bike',finishCost:'Finish',total:'Illustrative price',priceNote:'This is a demonstration configuration and illustrative price. No order or payment is placed.',save:'Save on this device',download:'Download specification ↓',saved:'Setup saved on this device.',restored:'Your saved setup was restored.',specLabel:'04 / WHY VÉLO',spec:'EVERY DETAIL COUNTS.',specItems:[['01','Geometry that responds to every move.'],['02','Materials chosen for strength and lightness.'],['03','Nothing unnecessary. Everything essential.']],endLabel:'YOUR ROAD STARTS HERE',endA:'MOVE.',endB:'NOW.',endText:'There is no better moment than the one you are in.',endLink:'Configure your bike',footer:'VÉLO / ATELIER OF MOTION',top:'Back to top ↑',currency:'PLN',menu:'Menu',close:'Close'}
}

function ArrowLink({href,children}:{href:string;children:string}){return <a className="v-arrow-link" href={href}><span>{children}</span><span aria-hidden="true">↗</span></a>}

export function VeloSite({locale}:ProjectProps){
 const lang=locale==='pl'?'pl':'en', t=copy[lang]
 const [model,setModel]=useState<ModelKey>('AERO 01')
 const [size,setSize]=useState('54')
 const [finish,setFinish]=useState<FinishKey>('acid')
 const [status,setStatus]=useState('')
 const [menuOpen,setMenuOpen]=useState(false)
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('velo-configuration')||'null');if(saved&&models.some(m=>m.id===saved.model)&&['52','54','56','58'].includes(saved.size)&&finishes.some(f=>f.id===saved.finish)){setModel(saved.model);setSize(saved.size);setFinish(saved.finish);setStatus(copy[lang].restored)}}catch{/* Invalid or unavailable storage: start fresh. */}},[lang])
 const selectedModel=models.find(m=>m.id===model)!, selectedFinish=finishes.find(f=>f.id===finish)!
 const formatPrice=(value:number)=>new Intl.NumberFormat(lang==='pl'?'pl-PL':'en-US').format(value)+' '+t.currency
 const chooseModel=(id:ModelKey)=>{setModel(id);setStatus('');document.getElementById('velo-configurator')?.scrollIntoView({behavior:'smooth'})}
 const save=()=>{try{localStorage.setItem('velo-configuration',JSON.stringify({model,size,finish}));setStatus(t.saved)}catch{setStatus(lang==='pl'?'Nie udało się zapisać na tym urządzeniu.':'Unable to save on this device.')}}
 const download=()=>{const lines=[`VÉLO — ${t.summary}`,`${t.model}: ${model}`,`${t.size}: ${size}`,`${t.finish}: ${selectedFinish.label[lang]}`,`${t.base}: ${formatPrice(selectedModel.price)}`,`${t.finishCost}: ${formatPrice(selectedFinish.extra)}`,`${t.total}: ${formatPrice(selectedModel.price+selectedFinish.extra)}`,'',t.priceNote];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`velo-${model.toLowerCase().replaceAll(' ','-')}-spec.txt`;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main className="project-site velo-site">
  <header className="v-header"><a href="#velo-top" className="v-logo" aria-label="VÉLO — top">VÉLO<span>.</span></a><button className="v-menu v-mono" type="button" aria-expanded={menuOpen} aria-controls="velo-nav" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?t.close:t.menu} {menuOpen?'×':'☰'}</button><nav className="v-nav" id="velo-nav" data-open={menuOpen} aria-label={lang==='pl'?'Nawigacja główna':'Main navigation'}><a onClick={()=>setMenuOpen(false)} href="#velo-collection">{t.nav[0]}</a><a onClick={()=>setMenuOpen(false)} href="#velo-philosophy">{t.nav[1]}</a><a onClick={()=>setMenuOpen(false)} href="#velo-configurator">{t.nav[2]}</a><a onClick={()=>setMenuOpen(false)} className="v-nav-cta" href="#velo-configurator">{t.navCta} ↗</a></nav></header>
  <section className="v-hero" id="velo-top"><div className="v-hero-content"><div className="v-mono v-hero-top">{t.heroTop}</div><h1 className="v-head">{t.hero}</h1><div className="v-hero-bottom"><p>{t.heroSub}</p><ArrowLink href="#velo-collection">{t.heroLink}</ArrowLink></div></div></section>
  <div className="v-ticker" aria-hidden="true"><div className="v-ticker-track">{Array.from({length:12},(_,i)=><span key={i}>{t.ticker} &nbsp; <b>✳</b></span>)}</div></div>
  <section className="v-intro v-container"><div className="v-mono v-label">{t.introLabel}</div><div><h2 className="v-head">{t.introA}<br/>{t.introB}<br/><em>{t.introC}</em></h2><p>{t.introText}</p></div></section>
  <section className="v-collection v-container" id="velo-collection"><div className="v-section-head"><div><div className="v-mono">01—03 / VÉLO COLLECTION</div><h2 className="v-head">{t.collection}</h2></div><p>{t.collectionSub}</p></div><div className="v-model-grid">{models.map((item,index)=><article className="v-model" key={item.id}><div className="v-model-image"><img src={item.image} alt={`${item.id} performance bicycle side profile`} loading="lazy"/></div><div className="v-model-info"><div className="v-model-line"><h3>{item.id}</h3><span className="v-mono">0{index+1} / 03</span></div><span className="v-mono">{item.type[lang]}</span><p className="v-model-desc">{item.desc[lang]}</p><div className="v-model-foot"><span className="v-mono">{t.from} {formatPrice(item.price)}</span><button type="button" onClick={()=>chooseModel(item.id)}>{t.discover} ↗</button></div></div></article>)}</div></section>
  <section className="v-manifesto" id="velo-philosophy"><div className="v-manifesto-image" role="img" aria-label={lang==='pl'?'Kolarz na pustej drodze o zachodzie słońca':'Cyclist on an open road at sunset'}/><div className="v-manifesto-content"><div className="v-mono">{t.manifestoLabel}</div><div><h2 className="v-head">{t.manifestoA}<br/><span>{t.manifestoB}</span></h2><p>{t.manifestoText}</p><ArrowLink href="#velo-configurator">{t.manifestoLink}</ArrowLink></div></div></section>
  <section className="v-config" id="velo-configurator"><div className="v-container"><div className="v-config-head"><span className="v-mono">{t.configLabel}</span><h2 className="v-head">{t.config}</h2><p>{t.configSub}</p></div><div className="v-config-layout"><div className="v-config-visual" style={{'--v-config-bg':selectedFinish.bg,'--v-bike-filter':selectedFinish.filter} as React.CSSProperties}><span className="v-mono">{model} / {selectedModel.type[lang]}</span><span className="v-config-no" aria-hidden="true">{model.slice(-2)}</span><img key={model} src={selectedModel.image} alt={`${model}, ${selectedFinish.label[lang]}`} /><div className="v-visual-foot v-mono"><span>VÉLO / {selectedModel.spec}</span><span>{size} CM / {selectedFinish.label[lang]}</span></div></div><div className="v-config-panel"><h3>{t.choose}</h3><fieldset className="v-fieldset"><legend>01 / {t.model}</legend><div className="v-options">{models.map(item=><button key={item.id} type="button" className="v-option" aria-pressed={model===item.id} onClick={()=>{setModel(item.id);setStatus('')}}>{item.id}</button>)}</div></fieldset><fieldset className="v-fieldset"><legend>02 / {t.size}</legend><div className="v-options">{['52','54','56','58'].map(value=><button key={value} type="button" className="v-option" aria-pressed={size===value} onClick={()=>{setSize(value);setStatus('')}}>{value} cm</button>)}</div><p className="v-summary-note">{t.sizeNote}</p></fieldset><fieldset className="v-fieldset"><legend>03 / {t.finish}</legend><div className="v-swatches">{finishes.map(item=><button key={item.id} type="button" className="v-swatch" style={{'--swatch':item.hex} as React.CSSProperties} aria-label={item.label[lang]} title={item.label[lang]} aria-pressed={finish===item.id} onClick={()=>{setFinish(item.id);setStatus('')}}><span/></button>)}</div><span className="v-swatch-label">{selectedFinish.label[lang]} {selectedFinish.extra>0?`(+${formatPrice(selectedFinish.extra)})`:''}</span></fieldset><div className="v-summary" aria-live="polite"><div className="v-mono" style={{marginBottom:18}}>{t.summary}</div><div className="v-summary-row"><span>{model} / {size} cm</span><span>{formatPrice(selectedModel.price)}</span></div><div className="v-summary-row"><span>{selectedFinish.label[lang]}</span><span>{selectedFinish.extra?`+ ${formatPrice(selectedFinish.extra)}`:'—'}</span></div><div className="v-summary-total"><span>{t.total}</span><span>{formatPrice(selectedModel.price+selectedFinish.extra)}</span></div><p className="v-summary-note">{t.priceNote}</p><button type="button" className="v-save" onClick={save}>{t.save} ↗</button><button type="button" className="v-save" onClick={download} style={{marginTop:8,background:'transparent',color:'#171b19',border:'1px solid #171b19'}}>{t.download}</button><p className="v-save-status" role="status">{status}</p></div></div></div></div></section>
  <section className="v-spec"><div className="v-container"><div className="v-mono">{t.specLabel}</div><h2 className="v-head">{t.spec}</h2><div className="v-spec-grid">{t.specItems.map(([number,text])=><div className="v-spec-item" key={number}><span className="v-mono">VÉLO / {number}</span><strong>{number}</strong><p>{text}</p></div>)}</div></div></section>
  <section className="v-end"><div className="v-container"><span className="v-mono">{t.endLabel}</span><h2 className="v-head">{t.endA}<br/><span>{t.endB}</span></h2><div className="v-end-bottom"><p>{t.endText}</p><ArrowLink href="#velo-configurator">{t.endLink}</ArrowLink></div></div></section>
  <footer className="v-footer"><span>{t.footer} © 2026</span><a href="#velo-top">{t.top}</a></footer>
 </main>
}