'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ProjectVisual } from '@/components/ProjectVisual'
import { Icon } from '@/components/common/Icon'
import { pagePath,pick } from '@/lib/i18n'
import { trackEvent } from '@/lib/analytics'
import type { Project,Locale } from '@/types/site'
export function ProjectShowcase({projects,locale}:{projects:Project[];locale:Locale}) {
 const [active,setActive]=useState(0)
 if(!projects.length)return <div className="empty-state"><p className="eyebrow">{pick(locale,'W PRZYGOTOWANIU','COMING SOON')}</p><h3>{pick(locale,'Pracujemy nad kolejnymi przykładami.','More examples are on their way.')}</h3><p>{pick(locale,'W międzyczasie możesz sprawdzić działające dema i zobaczyć, jak myślimy o produktach.','Meanwhile, explore working demos and see how we approach digital products.')}</p><Link href={`${locale==='en'?'/en':''}/demos/operations`} className="inline-link">{pick(locale,'Otwórz demo systemu','Explore the system demo')}<Icon name="arrow" size={16}/></Link></div>
 const p=projects[active%projects.length],image=p.image&&typeof p.image==='object'?p.image:null
 return <div className="project-showcase"><div className="project-selector">{projects.map((project,i)=><button key={project.id} onClick={()=>setActive(i)} aria-pressed={active===i}><span>0{i+1}</span>{project.category.split('/')[0]}<span className="selector-dot"/></button>)}</div><article className="featured-project"><div className="project-story" key={`story-${p.id}`}><div className="project-category"><span className="status-dot"/>{p.concept?pick(locale,'PROJEKT KONCEPCYJNY','CONCEPT PROJECT'):pick(locale,'REALIZACJA','CLIENT PROJECT')}</div><h3>{p.title}</h3><p>{p.summary}</p><div className="project-result"><Icon name="check" size={16}/>{p.result}</div><Link className="project-link" href={pagePath(locale,'projects',p.slug)} onClick={()=>trackEvent('project_open',{slug:p.slug})}>{pick(locale,'Zobacz projekt','Explore the project')}<span><Icon name="external" size={20}/></span></Link></div><div className="project-visual-link"><div key={`visual-${p.id}`} className="visual-transition"><ProjectVisual style={p.visualStyle} image={image} locale={locale}/></div><span className="project-preview-note">{p.concept?pick(locale,'AUTORSKI INTERFEJS · DANE DEMONSTRACYJNE','ORIGINAL INTERFACE · SAMPLE DATA'):p.category}</span></div></article><div className="project-bottom"><Link href={pagePath(locale,'projects')} className="inline-link">{pick(locale,'Wszystkie projekty','All projects')}<Icon name="external" size={14}/></Link><div className="carousel-controls"><button className="icon-button" onClick={()=>setActive((active-1+projects.length)%projects.length)} aria-label={pick(locale,'Poprzedni projekt','Previous project')}><Icon name="arrow" style={{transform:'rotate(180deg)'}} size={18}/></button><span aria-live="polite">0{active+1}<i>/</i>0{projects.length}</span><button className="icon-button" onClick={()=>setActive((active+1)%projects.length)} aria-label={pick(locale,'Następny projekt','Next project')}><Icon name="arrow" size={18}/></button></div></div></div>
}
