 'use client'
import { useState } from 'react'
import type { DemoState, DemoAction, TaskStatus } from '@/lib/demo-state'
import { cartSummary } from '@/lib/demo-state'
import type { Locale } from '@/types/site'
import { pick } from '@/lib/i18n'

type Props = { state: DemoState; dispatch: (action: DemoAction) => void; locale: Locale; query: string }
export const uid = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`
export const money = (cents: number, locale: Locale) => new Intl.NumberFormat(locale === 'pl' ? 'pl-PL' : 'en-GB', { style: 'currency', currency: 'PLN' }).format(cents / 100)
const matches = (text: string, query: string) => text.toLocaleLowerCase().includes(query.toLocaleLowerCase())
function Empty({ children }: { children: import('react').ReactNode }) { return <p className="workspace-empty">{children}</p> }
export function OperationsPanel({ state, dispatch, locale, query }: Props) {
 const [title, setTitle] = useState(''), [filter, setFilter] = useState('all')
 const statuses: TaskStatus[] = ['planned','active','done']
 const labels = locale === 'pl' ? ['Planowane','W toku','Gotowe'] : ['Planned','In progress','Done']
 const tasks = state.tasks.filter(t => (filter === 'all' || t.status === filter) && matches(t.title,query))
 return <>
  <form className="workspace-add" onSubmit={e => { e.preventDefault(); if(title.trim().length < 3)return; dispatch({ type:'task.add', id:uid(), title }); setTitle('') }}>
   <label>{pick(locale,'Nowe zadanie','New task')}<input name="task" required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder={pick(locale,'Co trzeba zrobić?','What needs to be done?')}/></label>
   <button className="workspace-primary" disabled={state.tasks.length>=100}>{pick(locale,'Dodaj zadanie','Add task')} <span aria-hidden="true">+</span></button>
  </form>
  <div className="workspace-filters" role="group" aria-label={pick(locale,'Status zadania','Task status')}>
   {['all',...statuses].map((s,i)=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{i===0?pick(locale,'Wszystkie','All'):labels[i-1]} <small>{state.tasks.filter(t=>s==='all'||t.status===s).length}</small></button>)}
  </div>
   <div className="workspace-section-intro"><strong>{pick(locale,'Rejestr zadań','Task register')}</strong><span>{pick(locale,'Zmień status bezpośrednio w wierszu.','Update status directly in each row.')}</span></div>
   <div className="workspace-table"><div className="workspace-table-head"><span>{pick(locale,'Zadanie / projekt','Task / project')}</span><span>{pick(locale,'Osoba','Owner')}</span><span>{pick(locale,'Status','Status')}</span></div>
    {tasks.map((task)=><div className="workspace-task" key={task.id}><div><small>{task.id.startsWith('t')&&/^t\d+$/.test(task.id)?`CM-${task.id.slice(1).padStart(3,'0')}`:pick(locale,'NOWE ZADANIE','NEW TASK')}</small><strong>{task.title}</strong></div><span className="workspace-avatar" title={`${pick(locale,'Właściciel','Owner')}: ${task.owner}`}>{task.owner}</span><label className="workspace-status-label"><span className="sr-only">{pick(locale,'Status: ','Status: ')}{task.title}</span><select aria-label={`${pick(locale,'Status','Status')}: ${task.title}`} value={task.status} onChange={e=>dispatch({type:'task.status',id:task.id,status:e.target.value as TaskStatus})}>{statuses.map((s,i)=><option key={s} value={s}>{labels[i]}</option>)}</select></label></div>)}
   {!tasks.length&&<Empty>{pick(locale,'Brak zadań spełniających filtr.','No tasks match your filter.')}</Empty>}
  </div>
 </>
}
export function ApprovalPanel({ state, dispatch, locale, query }: Props) {
 const [selected,setSelected]=useState('a1')
 const rows=state.proposals.filter(p=>matches(p.title,query)), proposal=rows.find(p=>p.id===selected)||rows[0]
 const status=(s:string)=>s==='pending'?pick(locale,'Do decyzji','Pending'):s==='approved'?pick(locale,'Zatwierdzono','Approved'):pick(locale,'Odrzucono','Rejected')
  return <div className="workspace-approval"><div className="workspace-inbox"><div className="workspace-inbox-title">{pick(locale,'Kolejka do przeglądu','Review queue')} <span>{rows.length}</span></div>{rows.map(p=><button aria-pressed={proposal?.id===p.id} key={p.id} onClick={()=>setSelected(p.id)}><small>{status(p.decision)}</small><strong>{p.title}</strong><span>{pick(locale,'Otwórz dokument','Open document')} ↗</span></button>)}{!rows.length&&<Empty>{pick(locale,'Brak wyników.','No results.')}</Empty>}</div>
   {proposal&&<article className="workspace-proposal"><div className="workspace-panel-kicker">{pick(locale,'DOKUMENT DO DECYZJI','DOCUMENT FOR REVIEW')} / {proposal.id.toUpperCase()}</div><h2>{proposal.title}</h2><div className="workspace-document-meta"><span>{pick(locale,'Typ','Type')}: {pick(locale,'Przegląd człowieka','Human review')}</span><span>{pick(locale,'Stan','State')}: {status(proposal.decision)}</span></div><h3>{pick(locale,'Materiał źródłowy i kontekst','Source material & context')}</h3><p>{proposal.context}</p><div className="workspace-proposed"><h3>{pick(locale,'Proponowany następny krok','Proposed next step')}</h3><p>{proposal.action}</p></div><p className="workspace-caption">{pick(locale,'Gotowy scenariusz demonstracyjny. Zatwierdzenie zapisuje jedynie decyzję lokalnie — nie uruchamia AI, wiadomości ani płatności.','Preset demonstration scenario. Approval records a local decision only — it does not run AI, send messages or process payments.')}</p>
   {proposal.decision==='pending'?<div className="workspace-actions"><button className="workspace-primary" onClick={()=>dispatch({type:'proposal.decide',id:proposal.id,decision:'approved'})}>{pick(locale,'Zatwierdź propozycję','Approve proposal')}</button><button onClick={()=>dispatch({type:'proposal.decide',id:proposal.id,decision:'rejected'})}>{pick(locale,'Odrzuć','Reject')}</button></div>:<p className="workspace-decision" role="status">{status(proposal.decision)} · {pick(locale,'Decyzja zapisana w historii demo.','Decision saved in demo history.')}</p>}
  </article>}
 </div>
}
export function CommercePanel({ state, dispatch, locale, query }: Props) {
 const summary=cartSummary(state),products=state.products.filter(p=>matches(p.name,query))
  return <><div className="workspace-commerce"><div className="workspace-products"><div className="workspace-section-intro"><strong>{pick(locale,'Katalog i stany','Catalogue & stock')}</strong><span>{pick(locale,'Dodaj pozycje do koszyka lub uzupełnij zapas.','Add items to the cart or replenish stock.')}</span></div>{products.map((p)=><article className="workspace-product" key={p.id}><div><small>SKU / {p.id.toUpperCase()}</small><h2>{p.name}</h2><strong>{money(p.price,locale)}</strong><p>{pick(locale,'Dostępne sztuki','Units available')}: {p.stock}</p></div><div className="workspace-quantity"><button aria-label={`${pick(locale,'Usuń z koszyka','Remove from cart')}: ${p.name}`} disabled={!state.cart[p.id]} onClick={()=>dispatch({type:'cart.change',id:p.id,delta:-1})}>−</button><output aria-label={`${pick(locale,'W koszyku','In cart')}: ${p.name}`}>{state.cart[p.id]||0}</output><button aria-label={`${pick(locale,'Dodaj do koszyka','Add to cart')}: ${p.name}`} disabled={(state.cart[p.id]||0)>=p.stock} onClick={()=>dispatch({type:'cart.change',id:p.id,delta:1})}>+</button></div><button className="workspace-text-button" disabled={p.stock>=999} onClick={()=>dispatch({type:'stock.add',id:p.id})}>{pick(locale,'Dostawa +5 szt.','Restock +5')}</button></article>)}{!products.length&&<Empty>{pick(locale,'Brak produktów.','No products.')}</Empty>}</div>
  <aside className="workspace-checkout"><p className="workspace-panel-kicker">CHECKOUT / DEMO</p><h2>{pick(locale,'Podsumowanie','Summary')}</h2><div><span>{pick(locale,'Liczba produktów','Items')}</span><strong>{summary.quantity}</strong></div><div><span>{pick(locale,'Wartość','Total')}</span><strong>{money(summary.total,locale)}</strong></div><button className="workspace-primary" disabled={!summary.quantity||state.orders.length>=100} onClick={()=>dispatch({type:'order.create',id:uid()})}>{pick(locale,'Utwórz zamówienie demo','Create demo order')}</button><p className="workspace-caption">{pick(locale,'Bez płatności i danych klienta. Zamówienie zmniejsza stan magazynu wyłącznie w tym demo.','No payments or customer data. The order updates stock in this demo only.')}</p></aside>
 </div><div className="workspace-order-list"><h2>{pick(locale,'Zamówienia','Orders')}</h2>{state.orders.map((o,i)=><div key={o.id}><span>CM-{state.orders.length-i}</span><strong>{money(o.total,locale)}</strong><span>{o.quantity} {pick(locale,'szt.','items')}</span>{o.status==='new'?<button onClick={()=>dispatch({type:'order.ship',id:o.id})}>{pick(locale,'Oznacz jako wysłane','Mark shipped')}</button>:<span className="workspace-badge">{pick(locale,'Wysłane','Shipped')}</span>}</div>)}{!state.orders.length&&<Empty>{pick(locale,'Dodaj produkty do koszyka i utwórz pierwsze zamówienie.','Add products to your cart and create the first order.')}</Empty>}</div></>
}
export function PortalPanel({ state, dispatch, locale, query }: Props) {
 const [note,setNote]=useState(''),[fileError,setFileError]=useState('')
 const notes=state.notes.filter(n=>matches(n.text,query))
  return <div className="workspace-portal"><article><div className="workspace-panel-kicker">{pick(locale,'PRZEGLĄD ETAPU / WERSJA 03','MILESTONE REVIEW / VERSION 03')}</div><h2>{pick(locale,'Portal dokumentów — przegląd','Document portal — review')}</h2><p>{pick(locale,'Przykładowy etap do oceny: ekran udostępniania dokumentów i zbierania decyzji od klienta. Przejrzyj zakres, dopisz konkretne uwagi lub zaakceptuj bieżącą wersję.','Sample milestone for review: the document-sharing screen and client decision flow. Review the scope, leave specific feedback or approve the current version.')}</p><div className="workspace-milestones">{[pick(locale,'Kierunek','Direction'),pick(locale,'Prototyp','Prototype'),pick(locale,'Review','Review'),pick(locale,'Akceptacja','Approval')].map((label,i)=><div key={label} className={i<3||state.portalApproved?'complete':''}><span>{i<3||state.portalApproved?'✓':String(i+1)}</span>{label}</div>)}</div><div className="workspace-review-list"><strong>{pick(locale,'Co obejmuje przegląd','Review checklist')}</strong><ul><li>{pick(locale,'Widok listy dokumentów i stany akceptacji','Document list and approval states')}</li><li>{pick(locale,'Dostęp opiekuna projektu i klienta','Project-owner and client access')}</li><li>{pick(locale,'Informacja zwrotna przypisana do wersji','Feedback attached to this version')}</li></ul></div><p>{pick(locale,'Nowa uwaga lub informacja o pliku ponownie otwiera etap do przeglądu.','New feedback or file metadata reopens this milestone for review.')}</p><button className="workspace-primary" disabled={state.portalApproved} onClick={()=>dispatch({type:'portal.approve'})}>{state.portalApproved?pick(locale,'Etap zatwierdzony','Milestone approved'):pick(locale,'Zatwierdź etap','Approve milestone')}</button>
  <div className="workspace-file-panel"><label>{pick(locale,'Załącznik demo','Demo attachment')}<input type="file" accept=".pdf,.txt,.png,.jpg,.jpeg" disabled={state.files.length>=100} onChange={e=>{const file=e.target.files?.[0]; if(!file)return; if(file.size>5242880||!/\.(pdf|txt|png|jpe?g)$/i.test(file.name)){setFileError(pick(locale,'Do 5 MB: PDF, TXT, PNG lub JPG.','Up to 5 MB: PDF, TXT, PNG or JPG.'));e.target.value='';return}setFileError('');dispatch({type:'file.add',id:uid(),name:file.name,size:file.size});e.target.value=''}}/></label><p className="workspace-caption">{pick(locale,'Zapisywane są tylko nazwa i rozmiar. Plik nie jest odczytywany ani wysyłany.','Only the name and size are saved. The file is not read or uploaded.')}</p>{fileError&&<p role="alert">{fileError}</p>}{state.files.map(f=><div className="workspace-file" key={f.id}><span>{f.name}</span><small>{Math.ceil(f.size/1024)} KB</small></div>)}</div>
  </article><section className="workspace-feedback"><div className="workspace-panel-kicker">{pick(locale,'KOMENTARZE DO WERSJI','VERSION COMMENTS')}</div><h2>{pick(locale,'Uwagi do przeglądu','Review feedback')}</h2><p>{pick(locale,'Zapisane uwagi zostają przy tym etapie. Dodanie komentarza cofa akceptację, aby można było ponownie ocenić zmiany.','Feedback stays with this milestone. Adding a comment reopens the review so changes can be considered again.')}</p><form onSubmit={e=>{e.preventDefault();if(note.trim().length<3)return;dispatch({type:'note.add',id:uid(),text:note});setNote('')}}><label>{pick(locale,'Twoja uwaga','Your feedback')}<textarea required minLength={3} maxLength={1000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder={pick(locale,'Np. uściślić, kto może zatwierdzić dokument…','E.g. clarify who can approve a document…')}/></label><button className="workspace-primary" disabled={state.notes.length>=100}>{pick(locale,'Zapisz uwagę','Save feedback')}</button></form><div className="workspace-feedback-thread"><strong>{pick(locale,'Zapisane uwagi','Saved feedback')} · {notes.length}</strong>{notes.map(n=><div key={n.id} className="workspace-note"><span className="workspace-avatar">{pick(locale,'TY','YOU')}</span><p>{n.text}</p></div>)}{!notes.length&&<Empty>{query?pick(locale,'Brak uwag dla tego wyszukiwania.','No feedback matches this search.'):pick(locale,'Brak uwag. Dodaj pierwszy komentarz do wersji.','No feedback yet. Add the first comment on this version.')}</Empty>}</div></section></div>
}
export function ActivityPanel({state,locale}:{state:DemoState;locale:Locale}) {
 const labels:Record<string,string>=locale==='pl'?{'task.add':'Dodano zadanie','task.status':'Zmieniono status zadania','proposal.decide':'Zapisano decyzję','cart.change':'Zmieniono koszyk','order.create':'Utworzono zamówienie demo','order.ship':'Oznaczono wysyłkę','stock.add':'Zwiększono stan','note.add':'Dodano uwagę','file.add':'Dodano informację o pliku','portal.approve':'Zaakceptowano etap'}:{'task.add':'Task added','task.status':'Task status updated','proposal.decide':'Decision saved','cart.change':'Cart updated','order.create':'Demo order created','order.ship':'Order marked shipped','stock.add':'Stock replenished','note.add':'Feedback added','file.add':'File metadata added','portal.approve':'Milestone approved'}
 return <div className="workspace-activity"><h2>{pick(locale,'Historia tego demo','Demo activity')}</h2><p className="workspace-caption">{pick(locale,'Ostatnie 100 działań w tej przeglądarce. Nie jest to serwerowy audyt.','The last 100 actions in this browser. This is not a server-side audit.')}</p>{state.audit.map(a=><div key={a.id}><span className="workspace-activity-dot"/><strong>{labels[a.event]||a.event}</strong><time dateTime={a.at}>{Number.isNaN(Date.parse(a.at))?'—':new Intl.DateTimeFormat(locale==='pl'?'pl-PL':'en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(a.at))}</time></div>)}{!state.audit.length&&<Empty>{pick(locale,'Wykonaj pierwszą operację, aby zobaczyć historię.','Perform your first action to see the activity log.')}</Empty>}</div>
}
