import {readFile} from 'node:fs/promises'
import {test,expect} from '@playwright/test'

test('PL residence filters lead to an actual detail and a local-only reservation persisted after reload and across locales',async({page})=>{
 await page.goto('/demos/real-estate')
 const app=page.locator('main.forma-app')
 await expect(app.getByRole('heading',{name:'Mieszkania z przestrzenią na więcej.'})).toBeVisible()
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await app.getByRole('combobox',{name:'Liczba pokoi'}).selectOption('2')
 await app.getByRole('combobox',{name:'Piętro'}).selectOption('1')
 await app.getByRole('combobox',{name:'Dostępność'}).selectOption('available')
 await expect(app.locator('.f-card')).toHaveCount(1)
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 await app.locator('.f-card').getByRole('button',{name:'Zobacz'}).click()
 const detail=app.getByRole('dialog',{name:'Apartament A-03'})
  await expect(detail.getByRole('img',{name:/Poglądowy plan mieszkania A-03: 2 pokoje/})).toBeVisible()
 await expect(detail).toContainText('CENA')
 await detail.getByRole('button',{name:'Zarezerwuj w demo'}).click()
 const confirmation=app.getByRole('dialog',{name:'Potwierdź rezerwację'})
 await expect(confirmation).toContainText('nie tworzy rzeczywistej rezerwacji')
 await confirmation.getByRole('button',{name:'Potwierdź w demo'}).click()
 await expect(app.locator('.f-empty')).toBeVisible()
 await app.getByRole('combobox',{name:'Dostępność'}).selectOption('reserved')
 await expect(app.locator('.f-card')).toHaveCount(1)
 await expect(app.locator('.f-card .f-status')).toHaveText(['Zarezerwowane'])
 await page.reload()
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await expect(app.locator('.f-card .f-status')).toHaveText(['Zarezerwowane'])
 await page.goto('/en/demos/real-estate')
 const english=page.locator('main.forma-app')
 await english.getByRole('searchbox',{name:'Search residence number'}).fill('A-03')
 await expect(english.locator('.f-card .f-status')).toHaveText(['Reserved'])
})

test('EN residence filters, favorites and detail work in the public experience',async({page})=>{
 await page.goto('/en/demos/real-estate')
 const app=page.locator('main.forma-app')
 await expect(app.getByRole('heading',{name:'A different way to live.'})).toBeVisible()
 await app.getByRole('searchbox',{name:'Search residence number'}).fill('A-03')
 await app.getByRole('combobox',{name:'Number of rooms'}).selectOption('2')
 await app.getByRole('combobox',{name:'Floor'}).selectOption('1')
 await app.getByRole('combobox',{name:'Availability'}).selectOption('available')
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 await app.getByRole('button',{name:'Save A-03'}).click()
 await app.getByRole('button',{name:/^Saved/}).click()
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 await page.reload()
 await app.getByRole('button',{name:/^Saved/}).click()
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 await app.locator('.f-card').getByRole('button',{name:'View'}).click()
 await expect(app.getByRole('dialog',{name:'Residence A-03'})).toContainText('Illustrative plan; not architectural documentation.')
 await app.getByRole('dialog',{name:'Residence A-03'}).getByRole('button',{name:'Close'}).click()
 await app.getByRole('button',{name:'Remove A-03 from saved'}).click()
 await expect(app.locator('.f-empty')).toContainText('Nothing saved yet.')
})

test('sales status and note persist; CSV is a real filtered download; reset requires confirmation',async({page})=>{
 await page.goto('/demos/real-estate')
 const app=page.locator('main.forma-app')
 await app.getByRole('button',{name:'Sprzedaż'}).click()
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await expect(app.locator('.f-roster tbody tr')).toHaveCount(1)
 await app.getByRole('combobox',{name:'A-03: status'}).selectOption('sold')
 await expect(app.getByRole('combobox',{name:'A-03: status'})).toHaveValue('sold')
 await app.locator('.f-roster tbody tr').getByRole('button',{name:'Otwórz'}).click()
 const detail=app.getByRole('dialog',{name:'Apartament A-03'})
 await detail.getByRole('textbox',{name:'Notatka zespołu sprzedaży'}).fill('Kontakt po prezentacji lokalu.')
 await detail.getByRole('button',{name:'Zapisz notatkę'}).click()
 const downloadPromise=page.waitForEvent('download')
 await app.getByRole('button',{name:/Eksport CSV/}).click()
 const download=await downloadPromise
 expect(download.suggestedFilename()).toBe('forma-apartments.csv')
 const csv=await readFile(await download.path(),'utf8')
 expect(csv).toContain('"A-03"')
 expect(csv).toContain('"sold"')
 expect(csv).toContain('"Kontakt po prezentacji lokalu."')
 expect(csv).not.toContain('"A-04"')
 await page.reload()
 await app.getByRole('button',{name:'Sprzedaż'}).click()
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await expect(app.getByRole('combobox',{name:'A-03: status'})).toHaveValue('sold')
 await app.locator('.f-roster tbody tr').getByRole('button',{name:'Otwórz'}).click()
 await expect(app.getByRole('textbox',{name:'Notatka zespołu sprzedaży'})).toHaveValue('Kontakt po prezentacji lokalu.')
 await app.getByRole('dialog',{name:'Apartament A-03'}).getByRole('button',{name:'Zamknij'}).click()
 await app.getByRole('button',{name:'Przywróć próbkę'}).click()
 const reset=app.getByRole('dialog',{name:'Przywrócić dane?'})
 await expect(reset).toContainText('Wszystkie zmiany statusów, notatki')
 await reset.getByRole('button',{name:'Anuluj'}).click()
 await expect(app.getByRole('combobox',{name:'A-03: status'})).toHaveValue('sold')
 await app.getByRole('button',{name:'Przywróć próbkę'}).click()
 await app.getByRole('dialog',{name:'Przywrócić dane?'}).getByRole('button',{name:'Przywróć próbkę'}).click()
 await expect(app.getByRole('combobox',{name:'A-03: status'})).toHaveValue('available')
 await app.locator('.f-roster tbody tr').getByRole('button',{name:'Otwórz'}).click()
 await expect(app.getByRole('textbox',{name:'Notatka zespołu sprzedaży'})).toHaveValue('')
})

test('no-match filters offer a working reset',async({page})=>{
 await page.goto('/demos/real-estate')
 const app=page.locator('main.forma-app')
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-999')
 await expect(app.locator('.f-empty')).toContainText('Brak mieszkań w tym wyborze.')
 await app.getByRole('button',{name:'Pokaż wszystkie'}).click()
 await expect(app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'})).toHaveValue('')
 await expect(app.locator('.f-card')).toHaveCount(6)
})

test('Bot SVG opens and closes the real brief dialog without submitting',async({page})=>{
 await page.goto('/')
 const launcher=page.getByRole('button',{name:'Otwórz czat CodeMaster'})
 await expect(launcher.locator('svg.robot-bot-icon')).toBeVisible()
 await launcher.click()
 const dialog=page.getByRole('dialog',{name:'Asystent CodeMaster — kreator briefu'})
 await expect(dialog).toBeVisible()
 await expect(dialog).toContainText('KREATOR BRIEFU')
 await dialog.getByRole('button',{name:'Zamknij asystenta'}).click()
 await expect(dialog).not.toBeVisible()
 await expect(launcher).toHaveAttribute('aria-expanded','false')
})

test('390px and reduced motion preserve usable FORMA content without page overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/demos/real-estate')
 await expect(page.locator('html')).toHaveAttribute('data-motion','off')
 const app=page.locator('main.forma-app')
 await expect(app.getByRole('heading',{name:'Mieszkania z przestrzenią na więcej.'})).toBeVisible()
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('mobile full-page native modal traps focus, escapes and restores the trigger',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/demos/real-estate')
 const app=page.locator('main.forma-app')
 await app.getByRole('searchbox',{name:'Szukaj numeru mieszkania'}).fill('A-03')
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 const trigger=app.getByRole('button',{name:'Zobacz'})
 await trigger.click()
 const dialog=app.getByRole('dialog',{name:'Apartament A-03'})
 await expect(dialog).toBeVisible()
 await expect(dialog).toHaveJSProperty('open',true)
 await expect(dialog.getByRole('img',{name:/Poglądowy plan mieszkania A-03/})).toBeVisible()
 await page.keyboard.press('Shift+Tab')
 await expect(dialog.locator('select,button').last()).toBeFocused()
 await page.keyboard.press('Escape')
 await expect(dialog).toHaveCount(0)
 await expect(trigger).toBeFocused()
 await app.getByRole('button',{name:'Wybrane'}).click()
 await expect(app.getByRole('heading',{level:1,name:'Wybrane mieszkania'})).toBeVisible()
 await expect(app.getByRole('heading',{level:1})).toHaveCount(1)
})

test('EN mobile full-page detail is keyboard modal and returns focus',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/en/demos/real-estate')
 const app=page.locator('main.forma-app')
 await app.getByRole('searchbox',{name:'Search residence number'}).fill('A-03')
 await expect(app.locator('.f-card h3')).toHaveText(['A-03'])
 const trigger=app.getByRole('button',{name:'View'})
 await trigger.click()
 const dialog=app.getByRole('dialog',{name:'Residence A-03'})
 await expect(dialog).toBeVisible()
 await expect(dialog).toHaveJSProperty('open',true)
 await expect(dialog).toBeInViewport()
 await expect(dialog.getByText('Illustrative plan; not architectural documentation.')).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(dialog).toHaveCount(0)
 await expect(trigger).toBeFocused()
 await expect(app.getByRole('heading',{level:1})).toHaveCount(1)
})
