const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const ts=require(process.env.TYPESCRIPT_PATH||'typescript'),root=path.resolve(__dirname,'..');
function loader(overrides={}){
 const cache={};function load(relative){const file=path.resolve(root,relative);if(cache[file])return cache[file].exports;
  const m=new Module(file,module);cache[file]=m;m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const original=m.require.bind(m);
  m.require=name=>Object.hasOwn(overrides,name)?overrides[name]:name.startsWith('@/')?load('src/'+name.slice(2)+'.ts'):name.startsWith('.')?load(path.relative(root,path.resolve(path.dirname(file),name))+'.ts'):original(name);
  m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
 return load;
}
const load=loader(),body=load('src/lib/http-body.ts'),policy=load('src/lib/submission-policy.ts'),sec=load('src/lib/form-security.ts'),{assertPassivePDF}=load('src/lib/pdf-policy.ts');
function request(body,headers={}){return new Request('https://studio.example/api/contact',{method:'POST',body,headers,...(body instanceof ReadableStream?{duplex:'half'}:{})})}
test('body: exact limit accepted and mismatch rejected',async()=>{assert.equal((await body.readBody(request('hello',{'content-length':'5'}),5)).toString(),'hello');await assert.rejects(body.readBody(request('hello',{'content-length':'4'}),9),e=>e.code==='LENGTH_MISMATCH')});
for(const length of ['-1','NaN','1.2','Infinity','9007199254740992'])test('body: malformed length '+length,async()=>{await assert.rejects(body.readBody(request('x',{'content-length':length}),10),e=>e.code==='INVALID_LENGTH')});
test('body: missing Content-Length does not bypass cap',async()=>{await assert.rejects(body.readBody(request('123456'),5),e=>e.status===413)});
test('body: declared over-limit rejected before consuming',async()=>{await assert.rejects(body.readBody(request('123',{'content-length':'100'}),5),e=>e.status===413)});
test('body: slow stream is bounded and cancelled',async()=>{let cancelled=false;const stream=new ReadableStream({cancel(){cancelled=true}});await assert.rejects(body.readBody(request(stream),10,20),e=>e.status===408);assert.equal(cancelled,true)});
test('body: empty stream input is rejected',async()=>await assert.rejects(body.readBody(new Request('https://studio.example',{method:'POST'}),10),e=>e.code==='EMPTY_BODY'));
test('form: duplicate and unknown keys rejected',()=>{let f=new FormData();f.append('name','A');assert.equal(body.oneValuePerField(f,new Set(['name'])),true);f.append('name','B');assert.equal(body.oneValuePerField(f,new Set(['name'])),false);f=new FormData();f.set('__proto__','x');assert.equal(body.oneValuePerField(f,new Set(['name'])),false)});
test('idempotency: old authentic token validates recovery, not new creation',()=>{const token=sec.signToken('secret',1700000000000);assert.equal(sec.verifyToken(token,'secret',1700003600000).ok,false);assert.equal(sec.verifyToken(token,'secret',1700003600000,policy.TOKEN_RECOVERY_MAX_AGE).ok,true);assert.equal(sec.verifyToken(token,'secret',1700086400001,policy.TOKEN_RECOVERY_MAX_AGE).ok,false)});
test('uniqueness: generic CHECK and FK violations are not duplicate receipts',()=>{for(const error of [{code:'SQLITE_CONSTRAINT',message:'CHECK constraint failed'},{code:'SQLITE_CONSTRAINT_FOREIGNKEY'}])assert.equal(sec.isUniqueConflict(error),false);assert.equal(sec.isUniqueConflict({cause:{code:'SQLITE_CONSTRAINT_UNIQUE'}}),true)});
test('uniqueness: cyclic errors terminate',()=>{const error={code:'OTHER'};error.cause=error;assert.equal(sec.isUniqueConflict(error),false)});
test('password: passphrases accepted; weak and control-character values blocked',()=>{assert.equal(policy.passwordProblem('long unique sample passphrase'),undefined);for(const x of ['short',' '.repeat(20),'a'.repeat(129),'a'.repeat(20)+'\n',null])assert.equal(typeof policy.passwordProblem(x),'string')});
test('sameLead: retry requires same whitelisted values',()=>{const incoming={name:'Ada',nda:false,company:'',message:'same'};assert.equal(policy.sameLead({...incoming,company:null,id:22},incoming),true);assert.equal(policy.sameLead({...incoming,message:'changed'},incoming),false)});
for(const name of ['/JS','/JavaScript','/AA','/OpenAction','/EmbeddedFile','/XFA','/Filespec','/Launch','/SubmitForm'])test('PDF passive policy blocks '+name,()=>assert.throws(()=>assertPassivePDF({qpdf:[{}, {'obj:1 0 R':{value:{[name]:'x'}}}]}),/ATTACHMENT_ACTIVE_PDF/));
test('PDF: passive dictionary accepted; malformed structure rejected',()=>{assert.doesNotThrow(()=>assertPassivePDF({qpdf:[{}, {value:{'/Type':'/Pages'}}]}));assert.throws(()=>assertPassivePDF({}),/ATTACHMENT_INVALID/)});
const href=load('src/lib/i18n.ts').safeHref;
for(const value of ['java\tscript:alert(1)','https://good.example@evil.example','/\\evil.example','/path%0d%0aInjected','https://x.example/ bad'])test('URL sanitizer rejects '+JSON.stringify(value),()=>assert.equal(href(value,'/fallback'),'/fallback'));
test('URL sanitizer retains ordinary external and internal navigation',()=>{for(const v of ['https://example.com/demo?a=1','/en/projects/demo','#contact','mailto:hello@example.com','tel:+48123456789'])assert.equal(href(v,'fallback'),v)});
const zero={info:0,low:0,moderate:0,high:0,critical:0,total:0};
test('audit: empty valid report passes both installed scopes',async()=>{const {assessAudit}=await import('../docker/audit-policy.mjs');assert.deepEqual(assessAudit({metadata:{vulnerabilities:zero}},0),zero)});
for(const severity of ['moderate','high','critical'])test('audit: release blocked for '+severity,async()=>{const {assessAudit}=await import('../docker/audit-policy.mjs');assert.throws(()=>assessAudit({metadata:{vulnerabilities:{...zero,[severity]:1,total:1}}},1),/release blocked/)});
test('audit: missing/negative/inconsistent counters and error statuses fail closed',async()=>{const {assessAudit}=await import('../docker/audit-policy.mjs');for(const [r,e] of [[{},0],[{error:'offline'},1],[{metadata:{vulnerabilities:{...zero,total:1}}},0],[{metadata:{vulnerabilities:{...zero,low:-1}}},1],[{metadata:{vulnerabilities:zero}},2]])assert.throws(()=>assessAudit(r,e));assert.equal(assessAudit({metadata:{vulnerabilities:{...zero,low:1,total:1}}},1).low,1)});
// Execute real route handlers; only Payload storage/provider boundaries are contract doubles.
const secret='unit-test-secret'.repeat(8),origin='https://studio.example';
process.env.PAYLOAD_SECRET=secret;process.env.SERVER_URL=origin;
function cmsStub(){const tables={'leads':[],'private-files':[],'testimonials':[]};return {tables,
 find:async({collection,where})=>{const key=where?.submissionKey?.equals;const docs=tables[collection].filter(d=>!key||d.submissionKey===key);return {docs:structuredClone(docs),totalDocs:docs.length,totalPages:1}},
 findByID:async({collection,id})=>{const doc=tables[collection].find(d=>d.id===id);if(!doc)throw new Error('Not found');return structuredClone(doc)},
 create:async({collection,data})=>{if(tables[collection].some(d=>d.submissionKey===data.submissionKey)){const e=new Error('unique constraint');e.code='SQLITE_CONSTRAINT_UNIQUE';throw e}const doc={...data,id:tables[collection].length+1};tables[collection].push(doc);return structuredClone(doc)} };
}
function routes(cms,{rate=true,challenge=true}={}){return loader({'@/lib/site-data':{getCMS:async()=>cms},'@/lib/rate-limit':{claimRateSlot:async()=>rate},'@/lib/turnstile':{verifyChallenge:async()=>challenge},'@/lib/attachment-security':{inspectAttachment:async()=>({mime:'text/plain',extension:'txt'})}})}
const valid={name:'Ada Lovelace',email:'ada@example.com',message:'Please create a web application for our company.',topic:'web',privacyAccepted:'true',locale:'pl',source:'contact'};
const newToken=()=>sec.signToken(secret,Date.now()-1000);
function contactRequest(token,changes={},options={}){const form=new FormData();for(const [k,v] of Object.entries({...valid,...changes}))form.set(k,String(v));if(options.file)form.set('attachment',new File([options.file],'brief.txt',{type:'text/plain'}));if(options.duplicate)form.append('name','Duplicated');return new Request(origin+'/api/contact',{method:'POST',body:form,headers:{origin:options.origin||origin,'x-form-token':token}})}
test('contact route: committed receipt survives retry with no second lead',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/contact/route.ts'),token=newToken();const a=await POST(contactRequest(token)),b=await POST(contactRequest(token));assert.equal(a.status,200);assert.deepEqual(await a.json(),await b.json());assert.equal(cms.tables.leads.length,1);assert.equal(cms.tables.leads[0].notificationStatus,'pending');assert.equal(cms.tables.leads[0].privacyVersion,policy.PRIVACY_VERSION)});
test('contact route: content change under same token is 409, not false success',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/contact/route.ts'),token=newToken();await POST(contactRequest(token));const response=await POST(contactRequest(token,{message:'A materially different project description goes here.'}));assert.equal(response.status,409);assert.equal(cms.tables.leads.length,1)});
test('contact route: duplicate fields and off-origin requests rejected',async()=>{const {POST}=routes(cmsStub())('src/app/api/contact/route.ts');assert.equal((await POST(contactRequest(newToken(),{}, {duplicate:true}))).status,422);assert.equal((await POST(contactRequest(newToken(),{}, {origin:'https://evil.example'}))).status,403)});
test('contact route: challenge/rate failure cannot create a lead',async()=>{for(const options of [{rate:false},{challenge:false}]){const cms=cmsStub(),{POST}=routes(cms,options)('src/app/api/contact/route.ts');assert.equal((await POST(contactRequest(newToken()))).status,options.rate===false?429:403);assert.equal(cms.tables.leads.length,0)}});
test('contact route: signed stale token cannot create new submission',async()=>{const {POST}=routes(cmsStub())('src/app/api/contact/route.ts');const response=await POST(contactRequest(sec.signToken(secret,Date.now()-31*60000)));assert.equal(response.status,403);assert.equal((await response.json()).code,'TOKEN_EXPIRED')});
test('contact route: same attachment reused; changed attachment conflicts',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/contact/route.ts'),token=newToken();assert.equal((await POST(contactRequest(token,{}, {file:'Brief example'}))).status,200);assert.equal((await POST(contactRequest(token,{}, {file:'Brief example'}))).status,200);assert.equal((await POST(contactRequest(token,{}, {file:'Modified brief'}))).status,409);assert.equal(cms.tables['private-files'].length,1);assert.equal(cms.tables.leads.length,1)});
test('contact route: concurrent duplicate requests commit at most one lead',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/contact/route.ts'),token=newToken();const results=await Promise.all([POST(contactRequest(token)),POST(contactRequest(token))]);assert.equal(cms.tables.leads.length,1);assert.deepEqual(results.map(x=>x.status),[200,200])});
function reviewRequest(token,change={}){return new Request(origin+'/api/reviews',{method:'POST',headers:{origin,'content-type':'application/json','x-form-token':token},body:JSON.stringify({name:'Ada Lovelace',quote:'The project communication was clear and the result matched expectations.',rating:5,consent:true,locale:'pl',challengeToken:'test',...change})})}
test('reviews: accepted input remains DRAFT with private consent provenance',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/reviews/route.ts');assert.equal((await POST(reviewRequest(newToken()))).status,201);const doc=cms.tables.testimonials[0];assert.equal(doc._status,'draft');assert.equal(doc.consentVersion,policy.PRIVACY_VERSION);assert.ok(doc.consentAcceptedAt)});
test('reviews: retry once, conflict on different text, no consent rejection',async()=>{const cms=cmsStub(),{POST}=routes(cms)('src/app/api/reviews/route.ts'),token=newToken();await POST(reviewRequest(token));assert.equal((await POST(reviewRequest(token))).status,200);assert.equal((await POST(reviewRequest(token,{rating:2}))).status,409);assert.equal((await POST(reviewRequest(newToken(),{consent:false}))).status,422);assert.equal(cms.tables.testimonials.length,1)});
test('reviews: oversized JSON rejected by body reader, not Content-Length only',async()=>{const {POST}=routes(cmsStub())('src/app/api/reviews/route.ts');assert.equal((await POST(reviewRequest(newToken(),{quote:'x'.repeat(12001)}))).status,413)});
test('reviews: public response whitelists fields, never submission token/proof',async()=>{const cms=cmsStub();cms.tables.testimonials.push({id:1,name:'Author',quote:'Public review text',rating:5,submissionKey:'private',consentVersion:'private'});const {GET}=routes(cms)('src/app/api/reviews/route.ts');const data=await(await GET(new Request(origin+'/api/reviews'))).json();assert.equal('submissionKey' in data.reviews[0],false);assert.equal('consentVersion' in data.reviews[0],false)});
const {notifyLead}=load('src/lib/lead-notification.ts');
function outbox(status='pending',failure=false){const row={id:1,notificationStatus:status,notificationAttempts:0};const sent=[];return {row,sent,findByID:async()=>({...row}),update:async({data})=>Object.assign(row,data),sendEmail:async(data)=>{if(failure)throw new Error('SMTP unavailable');sent.push(data)}}}
process.env.LEAD_NOTIFY_EMAIL='owner@example.com';
test('notification outbox: SMTP failure persists retry state, not lost work',async()=>{const cms=outbox('pending',true);assert.equal(await notifyLead(cms,1,1700000000000),'retry');assert.equal(cms.row.notificationAttempts,1);assert.equal(cms.row.notificationStatus,'pending');assert.ok(cms.row.notificationNextAttemptAt)});
test('notification outbox: future attempt is deferred and success is not resent',async()=>{const cms=outbox();assert.equal(await notifyLead(cms,1,1700000000000),'sent');assert.equal(await notifyLead(cms,1,1700000001000),'skipped');assert.equal(cms.sent.length,1);assert.equal(cms.row.notificationNextAttemptAt,null);const future=outbox();future.row.notificationNextAttemptAt=new Date(1700000200000).toISOString();assert.equal(await notifyLead(future,1,1700000000000),'skipped')});
test('notification outbox: legacy imports and permanent failures do not send',async()=>{for(const status of ['legacy','failed']){const cms=outbox(status);assert.equal(await notifyLead(cms,1),'skipped');assert.equal(cms.sent.length,0)}});
test('notification outbox: attempt eight records terminal failure',async()=>{const cms=outbox('pending',true);cms.row.notificationAttempts=7;assert.equal(await notifyLead(cms,1),'failed');assert.equal(cms.row.notificationStatus,'failed')});
test('notification email uses CMS reference, not private enquiry content',async()=>{const cms=outbox();cms.row.message='sensitive body';cms.row.email='lead@example.com';await notifyLead(cms,1);assert.equal(cms.sent[0].text.includes('sensitive'),false);assert.equal(cms.sent[0].text.includes('lead@example'),false);assert.ok(cms.sent[0].text.includes('/admin/collections/leads/1'))});
test('seed: prior globals are preserved even when content collections are empty',async()=>{const {seedContent}=load('src/lib/seed.ts'),updates=[];const cms={findGlobal:async({slug})=>slug==='site-settings'?{email:'real@example.com',heroTitle:'Owner content'}:{},count:async()=>({totalDocs:0}),updateGlobal:async x=>updates.push(x),logger:{info:()=>{}},db:{beginTransaction:async()=>assert.fail('must not reseed')}};await seedContent(cms);assert.equal(updates.length,1);assert.equal(updates[0].slug,'installation-state')});
test('SEO: language alternates pair localized routes and preserve encoded slugs',()=>{const {languagePaths}=load('src/lib/i18n.ts');assert.deepEqual(languagePaths('/en/projects/project%20one'),{pl:'/realizacje/project%20one',en:'/en/projects/project%20one'});assert.deepEqual(languagePaths('/kontakt'),{pl:'/kontakt',en:'/en/contact'});assert.equal(languagePaths('/not-a-real-route'),undefined)});
test('SEO: metadata canonical and hreflang use one configured domain',()=>{const {pageMetadata}=load('src/lib/metadata.ts');const meta=pageMetadata('Title','Description','/en/contact','en');assert.equal(meta.alternates.canonical,'https://studio.example/en/contact');assert.equal(meta.alternates.languages.pl,'https://studio.example/kontakt')});
