const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),net=require('node:net');
const ts=require(process.env.TYPESCRIPT_PATH||'typescript'),root=path.resolve(__dirname,'..');
function load(relative){const file=path.join(root,relative),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const original=m.require.bind(m);m.require=name=>name.startsWith('.')?load(path.relative(root,path.resolve(path.dirname(file),name))+'.ts'):original(name);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);return m.exports;}
const {scanBytes}=load('src/lib/antivirus.ts'),{verifyChallenge}=load('src/lib/turnstile.ts');
async function clamReply(reply,callback){const server=net.createServer(socket=>{let bytes=Buffer.alloc(0);socket.on('data',chunk=>{bytes=Buffer.concat([bytes,chunk]);if(bytes.length>=14){socket.end(reply);}});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{return await callback(server.address().port);}finally{await new Promise(resolve=>server.close(resolve));}}
test('antivirus accepts only explicit clean response',async()=>assert.equal(await clamReply('stream: OK\0',port=>scanBytes(Buffer.from('test'),'127.0.0.1',port)),'CLEAN'));
test('antivirus infected response cannot become CLEAN',async()=>assert.equal(await clamReply('stream: Eicar-Test-Signature FOUND\0',port=>scanBytes(Buffer.from('test'),'127.0.0.1',port)),'INFECTED'));
test('antivirus scanner errors fail closed',async()=>assert.equal(await clamReply('stream: size limit exceeded ERROR\0',port=>scanBytes(Buffer.from('test'),'127.0.0.1',port)),'ERROR'));
test('antivirus truncated reply fails closed',async()=>assert.equal(await clamReply('stream: OK',port=>scanBytes(Buffer.from('test'),'127.0.0.1',port)),'ERROR'));
test('antivirus missing host/invalid port/oversize fail closed',async()=>{assert.equal(await scanBytes(Buffer.from('a'),''),'ERROR');assert.equal(await scanBytes(Buffer.from('a'),'127.0.0.1',-1),'ERROR');assert.equal(await scanBytes(Buffer.alloc(5*1024*1024+1),'127.0.0.1'),'ERROR');});
async function withEnv(values,callback){const before={...process.env};try{Object.assign(process.env,values);return await callback();}finally{for(const key of Object.keys(process.env))if(!(key in before))delete process.env[key];Object.assign(process.env,before);}}
const botEnv={TURNSTILE_SECRET_KEY:'synthetic-unit-secret',SERVER_URL:'https://studio.example',ALLOW_HTTP_LOCAL:''};
test('Turnstile verifies success, exact hostname and action',()=>withEnv(botEnv,async()=>{assert.equal(await verifyChallenge('token','contact',async()=>Response.json({success:true,hostname:'studio.example',action:'contact'})),true);for(const data of [{success:false},{success:true,hostname:'evil.example',action:'contact'},{success:true,hostname:'studio.example',action:'review'}])assert.equal(await verifyChallenge('token','contact',async()=>Response.json(data)),false);}));
test('Turnstile outage and malformed JSON fail closed',()=>withEnv(botEnv,async()=>{assert.equal(await verifyChallenge('token','contact',async()=>{throw Error('offline');}),false);assert.equal(await verifyChallenge('token','contact',async()=>new Response('not JSON')),false);}));
test('Turnstile missing/oversized tokens rejected before fetch',()=>withEnv(botEnv,async()=>{for(const token of [undefined,'','x'.repeat(2049)])assert.equal(await verifyChallenge(token,'contact',async()=>{assert.fail('must not fetch');}),false);}));
test('official dummy key cannot bypass hostname validation on public origin',()=>withEnv({...botEnv,TURNSTILE_SECRET_KEY:'1x0000000000000000000000000000000AA',ALLOW_HTTP_LOCAL:'true'},async()=>assert.equal(await verifyChallenge('token','contact',async()=>Response.json({success:true,hostname:'dummy'})),false)));
test('public startup rejects missing secrets and test keys',async()=>{const {validateEnvironment}=await import('../docker/env-validation.mjs');const env={PAYLOAD_SECRET:'a'.repeat(96),SERVER_URL:'https://studio.example',ALLOW_SQLITE_PRODUCTION:'single-node',DATABASE_URL:'file:/data/codemaster.db',SEED_CONTENT:'false',PAYLOAD_DROP_DATABASE:'false',SMTP_HOST:'mail.example',SMTP_USER:'user',SMTP_PASS:'synthetic',SMTP_FROM:'from@example.test',LEAD_NOTIFY_EMAIL:'operator@example.test',SITE_CONTACT_EMAIL:'contact@example.test',TURNSTILE_SITE_KEY:'valid-site',TURNSTILE_SECRET_KEY:'valid-secret',CLAMAV_HOST:'clamav',SMTP_PORT:'587',TRUSTED_CLIENT_IP_HEADER:'x-real-ip'};assert.equal(validateEnvironment(env).local,false);for(const key of ['PAYLOAD_SECRET','SMTP_PASS','TURNSTILE_SECRET_KEY','CLAMAV_HOST'])assert.throws(()=>validateEnvironment({...env,[key]:''}));assert.throws(()=>validateEnvironment({...env,TURNSTILE_SITE_KEY:'1x00000000000000000000AA'}));assert.throws(()=>validateEnvironment({...env,ALLOW_HTTP_LOCAL:'true'}));});
test('startup allows only explicit loopback testing, not arbitrary HTTP hosts',async()=>{const {validateEnvironment}=await import('../docker/env-validation.mjs');const env={PAYLOAD_SECRET:'a'.repeat(96),SERVER_URL:'http://127.0.0.1:3001',ALLOW_HTTP_LOCAL:'true',ALLOW_SQLITE_PRODUCTION:'single-node',DATABASE_URL:'file:/data/test.db',SEED_CONTENT:'false',PAYLOAD_DROP_DATABASE:'false'};assert.equal(validateEnvironment(env).local,true);assert.throws(()=>validateEnvironment({...env,SERVER_URL:'http://studio.example'}));});
test('production image uses standalone server and separate ops target',()=>{const docker=fs.readFileSync(path.join(root,'Dockerfile.production'),'utf8');assert.match(docker,/FROM base AS app/);assert.match(docker,/FROM base AS ops/);assert.match(docker,/"server.js"/);assert.doesNotMatch(docker,/next.*start/);const app=docker.split('FROM base AS app')[1].split('FROM base AS ops')[0];assert.doesNotMatch(app,/\/app\/node_modules|\/app\/src|\/app\/tests/);});
test('GraphQL disabled without removing REST route',()=>{assert.match(fs.readFileSync(path.join(root,'src/payload.config.ts'),'utf8'),/graphQL:\{disable:true\}/);assert.equal(fs.existsSync(path.join(root,'src/app/(payload)/api/graphql/route.ts')),false);assert.equal(fs.existsSync(path.join(root,'src/app/(payload)/api/[...slug]/route.ts')),true);});
test('migration source and reviewed SQL are exactly equivalent',()=>{for(const name of ['20260928_001_initial','20260928_002_password_reset','20260929_003_submission_delivery']){const source=fs.readFileSync(path.join(root,'src/migrations/sqlite',name+'.ts'),'utf8');const encoded=source.split('const statements=')[1].split('\nexport async')[0];const statements=JSON.parse(encoded);const sql=fs.readFileSync(path.join(root,'src/migrations/sqlite',name+'.sql'),'utf8');assert.equal(statements.join(';\n\n').replace(/\s/g,'')+';',sql.replace(/\s/g,''));}});
