const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const ts=require(process.env.TYPESCRIPT_PATH||'typescript');
const root=path.resolve(__dirname,'..'),cache={};
function load(relative){const file=path.join(root,relative);if(cache[file])return cache[file].exports;const source=fs.readFileSync(file,'utf8'),out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const m=new Module(file,module);cache[file]=m;m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));const original=m.require.bind(m);m.require=name=>name.startsWith('.')?load(path.relative(root,path.resolve(path.dirname(file),name))+'.ts'):name.startsWith('@/')?load('src/'+name.slice(2)+'.ts'):original(name);m._compile(out,file);return m.exports}
const {validateLead,TOPICS}=load('src/lib/lead-validation.ts');
const security=load('src/lib/form-security.ts'),{claimRateSlot}=load('src/lib/rate-limit.ts'),{safeHref,pagePath}=load('src/lib/i18n.ts'),{privateAccess,publishedOnly}=load('src/lib/access.ts'),{Users}=load('src/collections/Users.ts');
const valid={name:'Piotr',email:'piotr@example.com',message:'A custom project with document management.',topic:'system',privacyAccepted:true,locale:'pl'};
test('valid lead accepted and normalized',()=>{const r=validateLead({...valid,name:' Piotr '});assert.equal(r.ok,true);assert.equal(r.data.name,'Piotr');assert.equal(r.data.source,'contact')});
for(const [field,value] of [['email','test\r\nBcc:hacker@example.com'],['email','not-email'],['name','A'],['name','x'.repeat(101)],['message','too short'],['message','x'.repeat(5001)],['company','x'.repeat(161)],['phone','javascript:evil'],['budget','x'.repeat(101)],['timeline','x'.repeat(161)],['topic','admin'],['privacyAccepted',false],['name','x\x00y']])test(`reject invalid ${field}: ${String(value).slice(0,24)}`,()=>{assert.equal(validateLead({...valid,[field]:value}).ok,false)});
test('reject null and arrays',()=>{for(const x of [null,[],0,'text'])assert.equal(validateLead(x).ok,false)});
test('input object is whitelisted; no ACL/status/attachment escalation',()=>{const r=validateLead({...valid,role:'admin',status:'closed',submissionKey:'attacker',attachment:77});assert.equal(r.ok,true);for(const key of ['role','status','submissionKey','attachment'])assert.equal(key in r.data,false)});
test('all topic options accepted',()=>{for(const topic of TOPICS)assert.equal(validateLead({...valid,topic}).ok,true)});
test('booleans normalize from FormData',()=>{const r=validateLead({...valid,privacyAccepted:'on',nda:'on'});assert.equal(r.ok,true);assert.equal(r.data.nda,true)});
test('valid signed token accepted only after minimum delay',()=>{const token=security.signToken('a'.repeat(48),1700000000000);assert.equal(security.verifyToken(token,'a'.repeat(48),1700000001000).ok,true);assert.equal(security.verifyToken(token,'a'.repeat(48),1700000000200).ok,false)});
test('tampered token / wrong secret / future / expiry rejected',()=>{const secret='a'.repeat(48),now=1700000000000,token=security.signToken(secret,now);for(const [t,s,n] of [[token.slice(0,-1)+'x',secret,now+1000],[token,'b'.repeat(48),now+1000],[token,secret,now-1000],[token,secret,now+1800001],['',secret,now+1000]])assert.equal(security.verifyToken(t,s,n).ok,false)});
test('token key is stable but nonce makes distinct requests',()=>{const s='a'.repeat(48),a=security.signToken(s,1700000000000),b=security.signToken(s,1700000000000);assert.notEqual(a,b);assert.deepEqual(security.verifyToken(a,s,1700000001000),security.verifyToken(a,s,1700000002000))});
test('strict origin equality rejects off-site, opaque, missing and prefix origins',()=>{const url='https://studio.example';assert.equal(security.originAllowed(new Headers({origin:url}),url),true);for(const origin of ['https://studio.example.attacker.test','null','https://attacker.test','http://studio.example'])assert.equal(security.originAllowed(new Headers({origin}),url),false);assert.equal(security.originAllowed(new Headers(),url),false)});
test('PDF signature and extension required',()=>{assert.equal(security.fileType(Buffer.from('%PDF-1.7\n'),'brief.pdf').mime,'application/pdf');assert.equal(security.fileType(Buffer.from('<svg/>'),'brief.pdf'),null);assert.equal(security.fileType(Buffer.from('%PDF-1.7'),'brief.svg'),null)});
test('PNG/JPEG magic checked; SVG and HTML uploads rejected',()=>{assert.equal(security.fileType(Buffer.from([137,80,78,71,13,10,26,10]),'photo.png').mime,'image/png');assert.equal(security.fileType(Buffer.from([255,216,255,224]),'photo.jpg').mime,'image/jpeg');for(const name of ['x.svg','x.html','x.exe'])assert.equal(security.fileType(Buffer.from('<script>bad</script>'),name),null)});
test('text files reject binary/control and malformed UTF-8',()=>{assert.equal(security.fileType(Buffer.from('Ordinary notes\n'),'brief.txt').mime,'text/plain');assert.equal(security.fileType(Buffer.from([0,1,2]),'brief.txt'),null);assert.equal(security.fileType(Buffer.from([255,255]),'brief.txt'),null)});
test('untrusted forwarded IP cannot bypass global fallback',()=>{delete process.env.TRUSTED_CLIENT_IP_HEADER;assert.equal(security.actorKey(new Headers({'x-forwarded-for':'1.2.3.4'}),'secret'),security.actorKey(new Headers({'x-forwarded-for':'5.6.7.8'}),'secret'))});
test('configured trusted header hashes addresses and rejects malformed values',()=>{process.env.TRUSTED_CLIENT_IP_HEADER='x-real-ip';assert.notEqual(security.actorKey(new Headers({'x-real-ip':'1.2.3.4'}),'secret'),security.actorKey(new Headers({'x-real-ip':'1.2.3.5'}),'secret'));assert.equal(security.actorKey(new Headers({'x-real-ip':'not an address'}),'secret'),security.actorKey(new Headers(),'secret'));delete process.env.TRUSTED_CLIENT_IP_HEADER});
test('durable slot algorithm handles concurrent unique conflicts (contract stub, not live DB)',async()=>{const keys=new Set();const stub={create:async({data})=>{await new Promise(r=>setImmediate(r));if(keys.has(data.key)){const e=new Error('duplicate key');e.code='23505';throw e}keys.add(data.key);return{id:keys.size}}};const results=await Promise.all(Array.from({length:25},()=>claimRateSlot(stub,'actor','form',8,1700000000000)));assert.equal(results.filter(Boolean).length,8);assert.equal(keys.size,8)});
test('storage outages fail closed',async()=>{await assert.rejects(()=>claimRateSlot({create:async()=>{throw new Error('database unavailable')}},'a','form',8),/database unavailable/)});
test('public CMS access denied for mutations and private reads',()=>{for(const permission of Object.values(privateAccess)){assert.equal(permission({req:{user:null}}),false);assert.equal(permission({req:{user:{id:1}}}),true)}assert.deepEqual(publishedOnly({req:{user:null}}),{_status:{equals:'published'}})});
test('account hook blocks public creation even if access is overridden',()=>{const hook=Users.hooks.beforeChange[0];assert.throws(()=>hook({operation:'create',data:{},req:{user:null,context:{}}}),/Public account registration/);const data={name:'Piotr'};assert.deepEqual(hook({operation:'create',data,req:{user:null,context:{allowBootstrap:true}}}),data)});
test('safe links reject active-content and protocol-relative URLs',()=>{for(const href of ['javascript:alert(1)','data:text/html,hi','//attacker.test'])assert.equal(safeHref(href),'/');assert.equal(safeHref('/realizacje'),'/realizacje');assert.equal(pagePath('en','projects','demo'),'/en/projects/demo')});

const {safeJSON}=load('src/lib/metadata.ts');
test('JSON-LD cannot close its script element',()=>{const dangerous={title:'</script><script>alert(1)</script>',nested:{text:'<img onerror=alert(1)>'}};const serialized=safeJSON(dangerous);assert.equal(serialized.includes('<'),false);assert.deepEqual(JSON.parse(serialized),dangerous)});

const demo=load('src/lib/demo-state.ts');
const base=()=>demo.initialDemo('en');
test('demo: initial state is serializable and validates',()=>assert.deepEqual(demo.parseDemo(JSON.stringify(base())),base()));
test('demo: task addition normalizes text and preserves original state',()=>{const s=base(),next=demo.demoReducer(s,{type:'task.add',id:'new',title:'  New task  '});assert.equal(s.tasks.length,4);assert.equal(next.tasks.length,5);assert.equal(next.tasks[0].title,'New task');assert.equal(next.tasks[0].status,'planned')});
test('demo: task minimum length and duplicate ids rejected',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'task.add',id:'new',title:'a'}),s);assert.equal(demo.demoReducer(s,{type:'task.add',id:'t1',title:'Valid task'}),s)});
test('demo: task limit is bounded at 100',()=>{let s=base();for(let i=0;i<120;i++)s=demo.demoReducer(s,{type:'task.add',id:`new-${i}`,title:'Task '+i});assert.equal(s.tasks.length,100)});
test('demo: status transition changes requested task only',()=>{const s=base(),n=demo.demoReducer(s,{type:'task.status',id:'t2',status:'done'});assert.equal(n.tasks.find(t=>t.id==='t2').status,'done');assert.equal(n.tasks[0],s.tasks[0])});
test('demo: invalid task status rejected',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'task.status',id:'t2',status:'owner'}),s)});
test('demo: decisions are final unless reset',()=>{const s=demo.demoReducer(base(),{type:'proposal.decide',id:'a1',decision:'approved'});assert.equal(s.proposals[0].decision,'approved');assert.equal(demo.demoReducer(s,{type:'proposal.decide',id:'a1',decision:'rejected'}),s)});
test('demo: unknown proposal id has no effect',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'proposal.decide',id:'missing',decision:'approved'}),s)});
test('demo: cart cannot exceed available stock',()=>{const s=demo.demoReducer(base(),{type:'cart.change',id:'p1',delta:1000});assert.equal(s.cart.p1,18);assert.deepEqual(demo.cartSummary(s),{quantity:18,total:142200})});
test('demo: negative and noninteger cart values cannot be created',()=>{let s=demo.demoReducer(base(),{type:'cart.change',id:'p1',delta:-10});assert.equal(s.cart.p1??0,0);assert.equal(demo.demoReducer(s,{type:'cart.change',id:'p1',delta:1.5}),s)});
test('demo: foreign product ids cannot enter the cart',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'cart.change',id:'__proto__',delta:1}),s)});
test('demo: empty cart cannot create an order',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'order.create',id:'o1'}),s)});
test('demo: checkout uses integer cents, reduces stock and clears cart',()=>{let s=demo.demoReducer(base(),{type:'cart.change',id:'p1',delta:2});s=demo.demoReducer(s,{type:'cart.change',id:'p2',delta:1});s=demo.demoReducer(s,{type:'order.create',id:'o1'});assert.equal(s.orders[0].total,28700);assert.equal(s.orders[0].quantity,3);assert.equal(s.products[0].stock,16);assert.deepEqual(s.cart,{})});
test('demo: duplicate order id is idempotent',()=>{let s=demo.demoReducer(base(),{type:'cart.change',id:'p1',delta:1});s=demo.demoReducer(s,{type:'order.create',id:'o1'});s=demo.demoReducer(s,{type:'cart.change',id:'p1',delta:1});assert.equal(demo.demoReducer(s,{type:'order.create',id:'o1'}),s)});
test('demo: dispatch can mark an order shipped',()=>{let s=demo.demoReducer(base(),{type:'cart.change',id:'p1',delta:1});s=demo.demoReducer(s,{type:'order.create',id:'o1'});s=demo.demoReducer(s,{type:'order.ship',id:'o1'});assert.equal(s.orders[0].status,'shipped')});
test('demo: restock is bounded',()=>{let s=base();for(let i=0;i<300;i++)s=demo.demoReducer(s,{type:'stock.add',id:'p1'});assert.equal(s.products[0].stock,999)});
test('demo: feedback reopens approved milestone',()=>{let s=demo.demoReducer(base(),{type:'portal.approve'});assert.equal(s.portalApproved,true);s=demo.demoReducer(s,{type:'note.add',id:'n1',text:'Please update the header.'});assert.equal(s.portalApproved,false);assert.equal(s.notes.length,1)});
test('demo: excessive metadata attachment size rejected',()=>{const s=base();assert.equal(demo.demoReducer(s,{type:'file.add',id:'f',name:'file.pdf',size:5242881}),s);assert.equal(demo.demoReducer(s,{type:'file.add',id:'f',name:'file.pdf',size:-1}),s)});
test('demo: only file name and size retained',()=>{const s=demo.demoReducer(base(),{type:'file.add',id:'f',name:' brief.pdf ',size:123});assert.deepEqual(s.files[0],{id:'f',name:'brief.pdf',size:123})});
test('demo: reset restores defaults without retaining user notes',()=>{let s=demo.demoReducer(base(),{type:'note.add',id:'n1',text:'A note'});s=demo.demoReducer(s,{type:'reset',locale:'en'});assert.deepEqual(s,base())});
for(const value of [null,'','{}','[]','false','not-json','x'.repeat(250001)])test('demo: invalid storage rejected '+String(value).slice(0,18),()=>assert.equal(demo.parseDemo(value),null));
test('demo: incompatible schema version rejected',()=>assert.equal(demo.parseDemo(JSON.stringify({...base(),version:2})),null));
test('demo: unknown cart entry rejected in storage',()=>assert.equal(demo.parseDemo(JSON.stringify({...base(),cart:{unknown:1}})),null));
test('demo: oversold cart rejected in storage',()=>assert.equal(demo.parseDemo(JSON.stringify({...base(),cart:{p1:999}})),null));
test('demo: negative product price rejected in storage',()=>{const s=base();s.products[0].price=-1;assert.equal(demo.parseDemo(JSON.stringify(s)),null)});
test('demo: duplicate entity ids rejected in storage',()=>{const s=base();s.tasks.push(s.tasks[0]);assert.equal(demo.parseDemo(JSON.stringify(s)),null)});
test('demo: prototype-looking user text remains inert data',()=>{const s=demo.demoReducer(base(),{type:'note.add',id:'n',text:'<script>alert(1)</script>'});assert.equal(s.notes[0].text,'<script>alert(1)</script>')});

const {seedContent}=load('src/lib/seed.ts');
function seedStub({initialized=false,existing=0,fail=false}={}){
 const calls=[];let id=0;
 return {calls,logger:{info:()=>{}},findGlobal:async()=>({contentInitializedAt:initialized?'2026-09-28T00:00:00Z':null}),count:async()=>({totalDocs:existing}),
  updateGlobal:async({slug,data})=>{calls.push(['global',slug]);return data},
  create:async({collection})=>{if(fail)throw new Error('Synthetic seed failure');calls.push(['create',collection]);return{id:++id}},update:async()=>({}),
  db:{beginTransaction:async()=>'contract-test',commitTransaction:async()=>calls.push(['commit']),rollbackTransaction:async()=>calls.push(['rollback'])}};
}
test('seed contract: initialization marker prevents resurrecting deleted sample data',async()=>{const cms=seedStub({initialized:true});await seedContent(cms);assert.equal(cms.calls.length,0)});
test('seed contract: existing editorial content is adopted without overwriting',async()=>{const cms=seedStub({existing:1});await seedContent(cms);assert.deepEqual(cms.calls,[['global','installation-state']])});
test('seed contract: empty content is completed and marked in one transaction',async()=>{const cms=seedStub();await seedContent(cms);assert.ok(cms.calls.some(c=>c[0]==='create'));assert.ok(!cms.calls.some(c=>c[1]==='users'));assert.deepEqual(cms.calls.slice(-2),[['global','installation-state'],['commit']])});
test('seed contract: failure rolls back without writing completion marker',async()=>{const cms=seedStub({fail:true});await assert.rejects(()=>seedContent(cms),/Synthetic seed failure/);assert.deepEqual(cms.calls.at(-1),['rollback']);assert.ok(!cms.calls.some(c=>c[1]==='installation-state'))});
