'use client'

import {useRef, useState} from 'react'
import type {ProjectProps} from '../../project-data'
import './aura.css'
import {isCivilDate,localDate,formatCivilDate} from '@/lib/civil-date'
import {parseJourneyPlan} from '@/lib/showcase-validation'

type Copy={pl:string;en:string}
type Journey={id:string;region:'europe'|'americas'|'asia';name:Copy;place:Copy;image:string;days:number;price:number;lead:Copy;route:Copy[];season:Copy}
const journeys:Journey[]=[
 {id:'dolomites',region:'europe',name:{pl:'Dolomity bez pośpiechu',en:'The unhurried Dolomites'},place:{pl:'Włochy / Dolomity',en:'Italy / Dolomites'},image:'/images/showcase/aura-hero.webp',days:7,price:1890,season:{pl:'Czerwiec – wrzesień',en:'June – September'},lead:{pl:'Siedem dni wśród wapiennych szczytów, alpejskich łąk i górskich schronisk. Idziemy dalej, ale nigdy w pośpiechu.',en:'Seven days among limestone peaks, alpine meadows and mountain refuges. We go further, but never in a hurry.'},route:[{pl:'Dzień 1 — Przyjazd do Cortiny, wspólna kolacja i poznanie grupy.',en:'Day 1 — Arrive in Cortina, shared dinner and meet the group.'},{pl:'Dni 2–3 — Ścieżki wokół Tre Cime i noc w górskim schronisku.',en:'Days 2–3 — Trails around Tre Cime and a night in a mountain refuge.'},{pl:'Dni 4–5 — Passo Giau, wysokie łąki i lokalna kuchnia.',en:'Days 4–5 — Passo Giau, high meadows and local cooking.'},{pl:'Dni 6–7 — Wschód słońca nad jeziorem Braies i spokojny powrót.',en:'Days 6–7 — Sunrise at Lake Braies and an unhurried return.'}]},
 {id:'iceland',region:'europe',name:{pl:'Islandia od środka',en:'Inside Iceland'},place:{pl:'Islandia / Interior',en:'Iceland / Highlands'},image:'/images/showcase/aura-iceland.jpg',days:9,price:2740,season:{pl:'Lipiec – sierpień',en:'July – August'},lead:{pl:'Wulkaniczne pustkowia, gorące źródła i dni, w których horyzont należy tylko do nas.',en:'Volcanic wilderness, hot springs and days when the horizon belongs only to us.'},route:[{pl:'Dzień 1 — Reykjavík i powitanie w małej grupie.',en:'Day 1 — Reykjavík and a small-group welcome.'},{pl:'Dni 2–4 — Landmannalaugar: tęczowe góry i naturalne gorące źródła.',en:'Days 2–4 — Landmannalaugar: rhyolite mountains and natural hot springs.'},{pl:'Dni 5–7 — Przeprawa przez interior, lodowce i noclegi na uboczu.',en:'Days 5–7 — Cross the highlands, glaciers and remote overnight stays.'},{pl:'Dni 8–9 — Południowe wybrzeże i powrót do Reykjavíku.',en:'Days 8–9 — South coast and return to Reykjavík.'}]},
 {id:'patagonia',region:'americas',name:{pl:'Patagonia, dalekie południe',en:'Patagonia, far south'},place:{pl:'Chile / Patagonia',en:'Chile / Patagonia'},image:'/images/showcase/aura-patagonia.jpg',days:12,price:3890,season:{pl:'Listopad – marzec',en:'November – March'},lead:{pl:'Granit, wiatr i turkusowe jeziora. Dwanaście dni na końcu świata, z przestrzenią na zachwyt.',en:'Granite, wind and turquoise lakes. Twelve days at the edge of the world, with room for wonder.'},route:[{pl:'Dni 1–2 — Punta Arenas i droga do Torres del Paine.',en:'Days 1–2 — Punta Arenas and the road to Torres del Paine.'},{pl:'Dni 3–6 — Szlaki parku, widok na wieże i noclegi blisko natury.',en:'Days 3–6 — Park trails, tower viewpoints and nights close to nature.'},{pl:'Dni 7–9 — Lodowce, jeziora i wolny dzień na własne odkrycia.',en:'Days 7–9 — Glaciers, lakes and a free day for your own discoveries.'},{pl:'Dni 10–12 — Ostatnie wędrówki i podróż powrotna.',en:'Days 10–12 — Final hikes and the journey home.'}]},
 {id:'japan',region:'asia',name:{pl:'Japońskie Alpy',en:'The Japanese Alps'},place:{pl:'Japonia / Kamikōchi',en:'Japan / Kamikōchi'},image:'/images/showcase/aura-japan.jpg',days:10,price:3280,season:{pl:'Maj – październik',en:'May – October'},lead:{pl:'Górskie doliny, gorące kąpiele i cicha gościnność. Japonia z dala od głównego szlaku.',en:'Mountain valleys, hot baths and quiet hospitality. Japan away from the well-worn path.'},route:[{pl:'Dni 1–2 — Spotkanie w Matsumoto, pierwsze smaki regionu.',en:'Days 1–2 — Meet in Matsumoto, first tastes of the region.'},{pl:'Dni 3–5 — Kamikōchi: rzeka Azusa i ścieżki pod szczytami.',en:'Days 3–5 — Kamikōchi: the Azusa River and trails below the peaks.'},{pl:'Dni 6–8 — Górskie wioski, lokalne zajazdy i onsen.',en:'Days 6–8 — Mountain villages, local inns and onsen.'},{pl:'Dni 9–10 — Spokojne zakończenie podróży w Takayamie.',en:'Days 9–10 — An unhurried finish in Takayama.'}]},
]
const filters=[{id:'all',pl:'Wszystkie',en:'All journeys'},{id:'europe',pl:'Europa',en:'Europe'},{id:'americas',pl:'Ameryki',en:'Americas'},{id:'asia',pl:'Azja',en:'Asia'}] as const
type Filter=typeof filters[number]['id']
type Plan={journeyId:string;date:string;travelers:number;total:number}
const planKey='aura-showcase-plan'
const formatDate=formatCivilDate

export function AuraSite({locale}:ProjectProps){
 const pl=locale==='pl'
 const t=(copy:Copy)=>copy[locale]
 const [filter,setFilter]=useState<Filter>('all')
 const [selected,setSelected]=useState<Journey|null>(null)
 const [mobileOpen,setMobileOpen]=useState(false)
 const dialog=useRef<HTMLDialogElement>(null)
 const [journeyId,setJourneyId]=useState('dolomites')
 const [date,setDate]=useState('')
 const [travelers,setTravelers]=useState('2')
 const [error,setError]=useState('')
 const [plan,setPlan]=useState<Plan|null>(null)
 const [saved,setSaved]=useState(false)
 const today=localDate()
 const journey=journeys.find(item=>item.id===journeyId)??journeys[0]
 const planJourney=journeys.find(item=>item.id===plan?.journeyId)
 const closeNav=()=>setMobileOpen(false)
 const showJourney=(item:Journey)=>{setSelected(item);dialog.current?.showModal()}
 const chooseJourney=(item:Journey)=>{setJourneyId(item.id);setPlan(null);setSaved(false);dialog.current?.close();document.getElementById('aura-plan')?.scrollIntoView({behavior:'smooth'})}
 const createPlan=(event:React.FormEvent<HTMLFormElement>)=>{
  event.preventDefault();setError('');setPlan(null);setSaved(false)
  if(!isCivilDate(date)||date<localDate()){setError(pl?'Wybierz dzisiejszą lub późniejszą datę.':'Choose today or a later departure date.');return}
  const count=Number(travelers)
  if(!Number.isInteger(count)||count<1||count>8){setError(pl?'Wybierz od 1 do 8 podróżujących.':'Choose between 1 and 8 travelers.');return}
  setPlan({journeyId,date,travelers:count,total:journey.price*count})
 }
 const savePlan=()=>{
  if(!plan)return
  try{localStorage.setItem(planKey,JSON.stringify(plan));setSaved(true)}
  catch{setError(pl?'Nie udało się zapisać w tej przeglądarce.':'Could not save in this browser.')}
 }
 const downloadPlan=()=>{
  if(!plan||!planJourney)return
  const text=[`AURA / ${t(planJourney.name)}`,`${t(planJourney.place)} · ${planJourney.days} ${pl?'dni':'days'}`,`${pl?'Planowany wyjazd':'Planned departure'}: ${formatDate(plan.date,locale)}`,`${pl?'Podróżujący':'Travelers'}: ${plan.travelers}`,`${pl?'Cena ilustracyjna':'Illustrative estimate'}: €${plan.total.toLocaleString(locale==='pl'?'pl-PL':'en-GB')}`,'',...planJourney.route.map(t),'',pl?'To prywatny plan demonstracyjny, nie rezerwacja. Cena nie jest ofertą handlową.':'This is a private demonstration plan, not a booking. Pricing is illustrative only.'].join('\n')
  const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}))
  const link=document.createElement('a');link.href=url;link.download=`aura-${plan.journeyId}-plan.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
 }
 const restorePlan=()=>{
  try{const raw=localStorage.getItem(planKey);if(!raw){setError(pl?'Brak zapisanego planu w tej przeglądarce.':'No saved plan in this browser.');return}
   const restored=parseJourneyPlan(raw,journeys)
   if(!restored)throw new Error('Invalid plan')
   setPlan(restored);setJourneyId(restored.journeyId);setDate(restored.date);setTravelers(String(restored.travelers));setSaved(true);setError('')
  }catch{setError(pl?'Nie udało się odczytać zapisanego planu.':'Could not read the saved plan.')}
 }
 return <div className="project-site aura-site" lang={locale}>
  <header className="au-header"><a className="au-logo" href="#aura-top" onClick={closeNav} aria-label="AURA home">AURA</a><button type="button" className="au-menu-toggle" aria-expanded={mobileOpen} aria-controls="au-navigation" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?(pl?'Zamknij':'Close'):'Menu'} {mobileOpen?'×':'+'}</button><nav id="au-navigation" className={`au-nav ${mobileOpen?'is-open':''}`} aria-label={pl?'Nawigacja główna':'Main navigation'}><a href="#aura-journeys" onClick={closeNav}>{pl?'Podróże':'Journeys'}</a><a href="#aura-way" onClick={closeNav}>{pl?'Nasze podejście':'Our way'}</a><a href="#aura-how" onClick={closeNav}>{pl?'Jak podróżujemy':'How it works'}</a><a className="au-nav-cta" href="#aura-plan" onClick={closeNav}>{pl?'Ułóż plan':'Make a plan'} ↗</a></nav></header>
  <main id="aura-top">
   <section className="au-hero" aria-labelledby="au-title"><div className="au-hero-inner"><p className="au-eyebrow">{pl?'Małe grupy. Wielkie przestrzenie.':'Small groups. Wide horizons.'}</p><h1 id="au-title">{pl?<>Dalej niż<br/><em>oczekujesz.</em></>:<>Go beyond<br/><em>the expected.</em></>}</h1><div className="au-hero-description"><p>{pl?'Niezwykłe wyprawy w góry i miejsca, do których chce się wracać myślami.':'Thoughtful journeys into mountains and places that stay with you long after you leave.'}</p><a className="au-round-link" href="#aura-journeys" aria-label={pl?'Odkryj podróże':'Discover journeys'}>↓</a></div></div><span className="au-hero-coordinate">46°41′ N / 12°04′ E</span></section>
   <div className="au-ticker"><span>{pl?'Własne tempo / wspólna droga':'Your pace / shared path'}</span><span>01 — 04 / {pl?'Odkrywaj z AURA':'Explore with AURA'}</span><span>{pl?'Podróże w małych grupach':'Small-group journeys'}</span></div>
   <section className="au-section au-intro"><div><p className="au-section-label">01 / {pl?'Poza utartym szlakiem':'Beyond the familiar'}</p><h2>{pl?<>Mniej pośpiechu.<br/><em>Więcej świata.</em></>:<>Less hurry.<br/><em>More world.</em></>}</h2></div><p>{pl?'Wierzymy, że najlepsze wspomnienia nie mieszczą się w napiętym harmonogramie. Dlatego wybieramy kameralne grupy, lokalne ścieżki i czas, by naprawdę poczuć miejsce.':'We believe the best memories do not fit into a crowded schedule. So we choose intimate groups, local paths and enough time to truly feel a place.'}</p></section>
   <section className="au-section au-collection" id="aura-journeys" aria-labelledby="au-collection-title"><div className="au-collection-head"><div><p className="au-section-label">02 / {pl?'Wybierz kierunek':'Choose your direction'}</p><h2 id="au-collection-title">{pl?'Kolekcja podróży':'The journey collection'}</h2></div><div className="au-filter" role="group" aria-label={pl?'Filtruj podróże':'Filter journeys'}>{filters.map(item=><button type="button" key={item.id} aria-pressed={filter===item.id} onClick={()=>setFilter(item.id)}>{item[locale]}</button>)}</div></div><div className="au-grid">{journeys.filter(item=>filter==='all'||item.region===filter).map(item=><button className="au-card" key={item.id} type="button" onClick={()=>showJourney(item)} aria-label={`${t(item.name)} — ${pl?'zobacz szczegóły':'view details'}`}><div className="au-card-image"><img src={item.image} alt={t(item.place)} loading="lazy"/><span>{item.days} {pl?'dni':'days'} / {pl?'mała grupa':'small group'}</span></div><div className="au-card-content"><div><small>{t(item.place)}</small><strong>{t(item.name)}</strong></div><b aria-hidden="true">↗</b></div></button>)}</div></section>
   <section className="au-section au-philosophy" id="aura-way"><div><p className="au-section-label">03 / {pl?'Nasza droga':'Our way'}</p><h2>{pl?<>Blisko<br/><em>natury.</em><br/>Bliżej siebie.</>:<>Close to<br/><em>nature.</em><br/>Closer to life.</>}</h2></div><div><p>{pl?'Nie zbieramy punktów na mapie. Wybieramy trasy, na których można zatrzymać się bez powodu. Poznać miejscowych. Patrzeć, jak światło zmienia góry. Po prostu być.':'We do not collect pins on a map. We choose routes where you can stop for no reason. Meet local people. Watch the light change the mountains. Simply be there.'}</p><div className="au-philosophy-list"><div><span>01</span>{pl?'Kameralne grupy: przestrzeń na własną przygodę.':'Small groups: room for your own adventure.'}</div><div><span>02</span>{pl?'Przemyślana trasa, ale nigdy wyścig.':'A considered route, never a race.'}</div><div><span>03</span>{pl?'Szacunek dla krajobrazu i lokalnych społeczności.':'Respect for landscapes and local communities.'}</div></div></div></section>
   <section className="au-feature"><div><div><p className="au-section-label" style={{color:'#d7e8c6'}}>04 / {pl?'W centrum uwagi':'In focus'}</p><h2>{pl?<>Dzika strona<br/><em>Islandii.</em></>:<>The wild side<br/><em>of Iceland.</em></>}</h2></div><button type="button" className="au-outline-button" onClick={()=>showJourney(journeys[1])}>{pl?'Odkryj wyprawę':'Explore the journey'} ↗</button></div></section>
   <section className="au-section au-how" id="aura-how"><div className="au-how-header"><div><p className="au-section-label">05 / {pl?'W dobrym rytmie':'At your own rhythm'}</p><h2>{pl?<>Droga zaczyna<br/><em>się tutaj.</em></>:<>It starts<br/><em>right here.</em></>}</h2></div><p>{pl?'Odkrywaj, porównuj i zaplanuj swoją podróż. Ten interaktywny projekt pozwala stworzyć własny szkic wyprawy bez płatności i bez rezerwacji.':'Explore, compare and sketch your journey. This interactive concept lets you create a personal trip plan without payment or a reservation.'}</p></div><div className="au-steps"><div className="au-step"><span>01 / {pl?'ODKRYJ':'DISCOVER'}</span><h3>{pl?'Znajdź swoje miejsce':'Find your place'}</h3><p>{pl?'Przeglądaj kierunki i poznaj rytm każdej wyprawy.':'Browse destinations and get a feel for each journey.'}</p></div><div className="au-step"><span>02 / {pl?'DOPASUJ':'TAILOR'}</span><h3>{pl?'Ułóż własny plan':'Shape your plan'}</h3><p>{pl?'Wybierz datę i liczbę podróżujących, aby zobaczyć orientacyjny koszt.':'Choose a date and group size to see an illustrative estimate.'}</p></div><div className="au-step"><span>03 / {pl?'ZACHOWAJ':'KEEP'}</span><h3>{pl?'Zabierz go ze sobą':'Take it with you'}</h3><p>{pl?'Zapisz plan w przeglądarce lub pobierz go jako plik tekstowy.':'Save it in your browser or download it as a text file.'}</p></div></div></section>
   <section className="au-section au-plan" id="aura-plan"><div className="au-plan-copy"><p className="au-section-label">06 / {pl?'Twoja kolej':'Your turn'}</p><h2>{pl?<>A dokąd<br/><em>teraz?</em></>:<>Where to<br/><em>next?</em></>}</h2><p>{pl?'Kilka wyborów wystarczy, by zobaczyć szkic podróży. Ceny są orientacyjne, a plan pozostaje tylko u Ciebie.':'A few choices are all it takes to see a journey sketch. Prices are illustrative, and your plan stays with you.'}</p></div><form className="au-plan-form" onSubmit={createPlan} noValidate><h3>{pl?'Ułóż swoją wyprawę':'Build your journey'}</h3><div className="au-form-fields"><div className="au-field"><label htmlFor="au-destination">{pl?'Kierunek':'Destination'}</label><select id="au-destination" value={journeyId} onChange={e=>{setJourneyId(e.target.value);setPlan(null);setSaved(false)}}>{journeys.map(item=><option key={item.id} value={item.id}>{t(item.name)} / {item.days} {pl?'dni':'days'}</option>)}</select></div><div className="au-field"><label htmlFor="au-date">{pl?'Planowany wyjazd':'Planned departure'}</label><input type="date" id="au-date" min={today} value={date} onChange={e=>{setDate(e.target.value);setPlan(null);setSaved(false)}} required/></div><div className="au-field"><label htmlFor="au-travelers">{pl?'Podróżujący':'Travelers'}</label><select id="au-travelers" value={travelers} onChange={e=>{setTravelers(e.target.value);setPlan(null);setSaved(false)}}>{Array.from({length:8},(_,i)=>i+1).map(n=><option value={n} key={n}>{n} {pl?(n===1?'osoba':n<5?'osoby':'osób'):(n===1?'traveler':'travelers')}</option>)}</select></div></div><button className="au-plan-button" type="submit">{pl?'Zobacz mój plan':'See my plan'} ↗</button>{error&&<p className="au-error" role="alert">{error}</p>}{plan&&planJourney&&<div className="au-result" role="status"><strong>{t(planJourney.name)}</strong><span>{formatDate(plan.date,locale)} · {plan.travelers} {pl?'os.':plan.travelers===1?'traveler':'travelers'} · {planJourney.days} {pl?'dni':'days'}</span><br/><span>{pl?'Orientacyjnie':'Illustrative total'}: €{plan.total.toLocaleString(pl?'pl-PL':'en-GB')} {pl?'łącznie':'total'}</span><br/><span>{pl?'Szkic podróży, nie oferta ani rezerwacja.':'A journey sketch, not an offer or booking.'}</span><br/><button type="button" onClick={savePlan}>{saved?(pl?'Zapisano lokalnie ✓':'Saved locally ✓'):(pl?'Zapisz w przeglądarce':'Save in browser')}</button> &nbsp; / &nbsp; <button type="button" onClick={downloadPlan}>{pl?'Pobierz plan .txt':'Download plan .txt'}</button></div>}{!plan&&<button type="button" onClick={restorePlan} style={{background:'none',border:0,borderBottom:'1px solid',padding:0,marginTop:20,fontSize:12,color:'#45656a'}}>{pl?'Otwórz zapisany plan':'Open saved plan'}</button>}</form></section>
  </main>
  <footer className="au-footer"><div className="au-footer-top"><h2>AURA<span style={{color:'#d1e682'}}>.</span></h2><p>{pl?'Dobre podróże zostają z nami na długo. Dokąd ruszysz dalej?':'The best journeys stay with us. Where will you go next?'}</p></div><div className="au-footer-bottom"><span>© AURA / {pl?'Autorski projekt pokazowy':'Original showcase concept'}</span><span>{pl?'Bez rezerwacji i płatności':'No bookings or payments'}</span><a href="#aura-top">{pl?'Na górę':'Back to top'} ↑</a></div></footer>
  <dialog className="au-detail" ref={dialog} aria-label={selected?t(selected.name):undefined} onClick={e=>{if(e.target===dialog.current)dialog.current?.close()}}><button type="button" className="au-detail-close" onClick={()=>dialog.current?.close()} aria-label={pl?'Zamknij szczegóły':'Close details'}>×</button>{selected&&<><img className="au-detail-image" src={selected.image} alt={t(selected.place)}/><div className="au-detail-body"><p className="au-section-label">{t(selected.place)} / {selected.days} {pl?'dni':'days'}</p><h3>{t(selected.name)}</h3><p className="au-detail-lead">{t(selected.lead)}</p><div className="au-detail-meta"><span>{pl?'Sezon':'Season'}: {t(selected.season)}</span><span>{pl?'Cena ilustracyjna':'Illustrative from'}: €{selected.price.toLocaleString(pl?'pl-PL':'en-GB')} / {pl?'os.':'person'}</span></div><p className="au-section-label">{pl?'Plan podróży':'The itinerary'}</p><div className="au-itinerary">{selected.route.map((part,index)=><div key={index}><span>{String(index+1).padStart(2,'0')}</span><span style={{font:'inherit',textTransform:'none',color:'inherit'}}>{t(part)}</span></div>)}</div><button className="au-plan-button" type="button" onClick={()=>chooseJourney(selected)}>{pl?'Zaplanuj tę wyprawę':'Plan this journey'} ↗</button></div></>}</dialog>
 </div>
}