import {ContentPagination} from '@/components/common/ContentPagination'
import type {Pagination} from '@/lib/pagination'
import Link from 'next/link'
import Image from 'next/image'
import {ProjectVisual} from '@/components/ProjectVisual'
import {Button} from '@/components/common/Button'
import {Icon} from '@/components/common/Icon'
import {Reveal} from '@/components/animation/Reveal'
import {pagePath,pick} from '@/lib/i18n'
import type {Project,Article,Settings,Locale} from '@/types/site'
function dateLabel(value:string,locale:Locale){const d=new Date(value);return Number.isNaN(d.getTime())?pick(locale,'Wersja robocza','Draft'):new Intl.DateTimeFormat(locale==='pl'?'pl-PL':'en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}
export function ProjectsPage({projects,locale,pagination}:{projects:Project[];locale:Locale;pagination?:Pagination}){
 return <main id="main" className="inner-page"><div className="container"><header id="top" className="page-intro"><p className="eyebrow">CODEMASTER / {pick(locale,'PORTFOLIO','WORK')}</p><h1>{pick(locale,'Od problemu\ndo produktu.','From problem\nto product.')}</h1><p>{pick(locale,'Sposób myślenia o oprogramowaniu, pokazany w konkretnych koncepcjach. Każdy projekt opisuje kontekst, kierunek i zakres prezentacji.','An approach to software made tangible through product concepts. Each project explains its context, direction and demonstration scope.')}</p></header><div className="projects-index">{projects.map((p,i)=><Reveal key={p.id}><article className="project-index-card"><div className="project-index-visual"><ProjectVisual style={p.visualStyle} image={p.image&&typeof p.image==='object'?p.image:null} locale={locale}/></div><div><span className="eyebrow">{String(((pagination?.page||1)-1)*12+i+1).padStart(2,'0')} / {p.category}</span>{p.concept&&<span className="concept-tag">{pick(locale,'KONCEPCJA','CONCEPT')}</span>}<h2><Link href={pagePath(locale,'projects',p.slug)}>{p.title}<Icon name="external" size={28}/></Link></h2><p>{p.summary}</p></div></article></Reveal>)}</div><ContentPagination value={pagination} base={pagePath(locale,'projects')} locale={locale}/>{!projects.length&&<p className="empty-state">{pick(locale,'Brak opublikowanych projektów.','No projects have been published yet.')}</p>}<div className="page-outro"><h2>{pick(locale,'Kolejny projekt?\nPorozmawiajmy o Twoim.','The next project?\nLet’s talk about yours.')}</h2><Button href={pagePath(locale,'contact')}>{pick(locale,'Opowiedz mi o projekcie','Tell me about your project')}</Button></div></div></main>
}
export function CaseStudyPage({project:p,locale}:{project:Project;locale:Locale}){
 return <main id="main" className="inner-page case-study"><div className="container"><header id="top" className="case-intro"><Link href={pagePath(locale,'projects')} className="inline-link"><Icon name="arrow" size={14} style={{transform:'rotate(180deg)'}}/>{pick(locale,'Wszystkie projekty','All projects')}</Link><div className="case-heading"><div><p className="eyebrow">{p.category}</p><h1>{p.title}</h1></div><p>{p.summary}</p></div><div className="case-metadata"><div><small>{pick(locale,'STATUS','STATUS')}</small><span>{p.concept?pick(locale,'Koncepcja CodeMaster','CodeMaster concept'):pick(locale,'Realizacja klienta','Client project')}</span></div><div><small>{pick(locale,'ZAKRES','SCOPE')}</small><span>{pick(locale,'Kierunek · UX/UI · Architektura','Direction · UX/UI · Architecture')}</span></div><div><small>{pick(locale,'PODEJŚCIE','APPROACH')}</small><span>Product first.</span></div></div></header><div className="case-hero-visual"><ProjectVisual style={p.visualStyle} image={p.image&&typeof p.image==='object'?p.image:null} locale={locale}/></div>{p.concept&&<p className="concept-disclosure"><Icon name="layers" size={15}/>{pick(locale,'To autorski projekt koncepcyjny. Wizualizacje i dane są demonstracyjne, nie są dowodem wdrożenia u klienta.','This is an original concept. Visuals and data are illustrative, not evidence of a client deployment.')}</p>}<div className="case-detail-facts">{p.result&&<section><h2>{pick(locale,'Rezultat / cel','Result / goal')}</h2><p>{p.result}</p></section>}{!p.concept&&p.client&&<p><strong>{pick(locale,'Klient: ','Client: ')}</strong>{p.client}</p>}{!!p.technologies?.length&&<ul className="content-tags" aria-label={pick(locale,'Technologie','Technologies')}>{p.technologies.map((t,i)=><li key={i}>{t.name}</li>)}</ul>}</div><div className="case-body"><aside><p className="eyebrow">{pick(locale,'W TYM PROJEKCIE','IN THIS PROJECT')}</p>{p.sections?.map((s,i)=><a key={i} href={`#chapter-${i}`}><small>{String(i+1).padStart(2,'0')}</small>{s.heading}</a>)}</aside><div>{p.sections?.map((s,i)=><section id={`chapter-${i}`} className="case-chapter" key={i}><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><h2>{s.heading}</h2>{(s.body||'').split('\n').filter(Boolean).map((text,j)=><p key={j}>{text}</p>)}</section>)}</div></div><div className="page-outro"><h2>{pick(locale,'Podobny problem\nw Twojej firmie?','A similar challenge\nin your business?')}</h2><Button href={pagePath(locale,'contact')}>{pick(locale,'Porozmawiajmy','Let’s talk')}</Button></div></div></main>
}

function BlogCover({index}:{index:number}){
 const kind=index%3
 return <div className={`blog-cover-ui cover-${kind}`} aria-hidden="true">
  <div className="blog-cover-bar"><span>CodeMaster / product note</span><i>+</i></div>
  {kind===0?<div className="blog-cover-process"><small>PROBLEM / PROCESS</small><div><span>01</span><i/><span>02</span><i/><strong>?</strong></div><p>observe → name → simplify</p></div>:kind===1?<div className="blog-cover-approval"><small>AGENT / CONTROL</small><div><span>INPUT</span><i>→</i><span>CONTEXT</span><i>→</i><strong>APPROVAL</strong></div><p>human decision required</p></div>:<div className="blog-cover-preview"><small>DEMO / FEEDBACK</small><div className="blog-mini-browser"><b/><b/><b/><section><i/><i/><i/></section></div><p>feedback → working version</p></div>}
 </div>
}
export function BlogIndex({articles,locale,pagination}:{articles:Article[];locale:Locale;pagination?:Pagination}){
 return <main id="main" className="inner-page"><div className="container"><header id="top" className="page-intro"><p className="eyebrow">CODEMASTER / {pick(locale,'NOTATKI O PRODUKCIE','PRODUCT NOTES')}</p><h1>{pick(locale,'Dobre pytania.\nLepsze oprogramowanie.','Better questions.\nBetter software.')}</h1><p>{pick(locale,'O projektowaniu rozwiązań, współpracy i decyzjach, które warto podjąć przed pierwszą linią kodu.','On designing solutions, collaboration and decisions worth making before the first line of code.')}</p></header><div className="blog-index">{articles.map((a,i)=><article className="blog-card" key={a.id}><Link href={pagePath(locale,'blog',a.slug)} className="blog-art" aria-label={a.title}>{a.cover&&typeof a.cover==='object'&&a.cover.url?<Image src={a.cover.url} alt={a.cover.alt||a.title} fill sizes="(max-width: 700px) 95vw, 45vw" style={{objectFit:'cover'}}/>:<BlogCover index={i}/>}<span className="blog-art-number">0{i+1}</span><Icon name="external" size={28}/></Link><p className="eyebrow">{dateLabel(a.publishedAt,locale)} · {a.author}</p><h2><Link href={pagePath(locale,'blog',a.slug)}>{a.title}</Link></h2><p>{a.excerpt}</p><Link href={pagePath(locale,'blog',a.slug)} className="inline-link">{pick(locale,'Czytaj dalej','Read the article')}<Icon name="arrow" size={16}/></Link></article>)}</div><ContentPagination value={pagination} base={pagePath(locale,'blog')} locale={locale}/>{!articles.length&&<p className="empty-state">{pick(locale,'Brak opublikowanych artykułów.','No published articles.')}</p>}</div></main>
}
export function ArticlePage({article:a,locale}:{article:Article;locale:Locale}){
 const image=a.cover&&typeof a.cover==='object'?a.cover:null
 return <main id="main" className="inner-page article-page"><article className="article-shell"><Link className="inline-link" href={pagePath(locale,'blog')}><Icon name="arrow" size={14} style={{transform:'rotate(180deg)'}}/>{pick(locale,'Wszystkie notatki','All notes')}</Link><header id="top"><p className="eyebrow">{a.author} / {dateLabel(a.publishedAt,locale)}</p><h1>{a.title}</h1><p className="article-excerpt">{a.excerpt}</p></header>{image?.url&&<Image src={image.url} alt={image.alt||a.title} width={1000} height={600}/>}<div className="article-prose">{a.sections?.map((s,i)=><section key={i}><h2>{s.heading}</h2>{(s.body||'').split('\n').filter(Boolean).map((text,j)=><p key={j}>{text}</p>)}</section>)}</div><div className="article-extras">{!!a.tags?.length&&<ul className="content-tags" aria-label={pick(locale,'Tematy artykułu','Article topics')}>{a.tags.filter(t=>t.name).map((t,i)=><li key={i}>{t.name}</li>)}</ul>}{!!a.relatedPosts?.some(p=>typeof p==='object'&&p&&p.id!==a.id)&&<aside><h2>{pick(locale,'Powiązane artykuły','Related articles')}</h2>{a.relatedPosts.filter((p):p is Article=>typeof p==='object'&&p!==null&&p.id!==a.id).map(p=><p key={p.id}><Link href={pagePath(locale,'blog',p.slug)}>{p.title}</Link></p>)}</aside>}</div><div className="article-cta"><h2>{pick(locale,'Porozmawiajmy o Twoim pomyśle.','Let’s talk about your idea.')}</h2><Button href={pagePath(locale,'contact')}>{pick(locale,'Zacznijmy od rozmowy','Start a conversation')}</Button></div></article></main>
}
export function PrivacyPage({settings:s,locale,cookies=false}:{settings:Settings;locale:Locale;cookies?:boolean}){
 const pl=locale==='pl'
 return <main id="main" className="inner-page legal-page"><article className="article-shell"><header id="top"><p className="eyebrow">CODEMASTER / {pl?'INFORMACJE':'INFORMATION'}</p><h1>{cookies?'Cookies':pl?'Informacja\no prywatności':'Privacy\ninformation'}</h1></header>{cookies?<div className="article-prose">
  <h2>{pl?'Bez reklamowego śledzenia':'No advertising tracking'}</h2><p>{pl?'Publiczna część tej witryny nie instaluje reklamowych ani analitycznych cookies. Nie korzysta z zewnętrznych odtwarzaczy ani trackerów. Czcionki sa udostepniane lokalnie z tego serwera. Formularze korzystaja z Cloudflare Turnstile w celu ochrony przed botami.':'The public website does not set advertising or analytics cookies. It does not use embedded external players or trackers. Fonts are served locally from this server. Forms use Cloudflare Turnstile for bot protection.'}</p>
  <h2>{pl?'Dane demonstracyjne w przeglądarce':'Demo data in your browser'}</h2><p>{pl?'Dema produktów zapisują wybrane mieszkania, statusy lokali, notatki, zadania, decyzje, koszyk i uwagi w localStorage tej przeglądarki. Dane te nie są wysyłane na serwer. Nie wpisuj danych prawdziwych klientów do demonstracji. Rezerwacja lokalu w demo nie jest rzeczywistą rezerwacją. Przycisk przywrócenia danych usuwa Twoje zmiany w wybranym demo; cały zapis można usunąć w ustawieniach danych witryny przeglądarki. W załącznikach demonstracyjnych zapisywana jest jedynie nazwa i rozmiar, nie zawartość pliku.':'Product demos store saved residences, unit statuses, notes, tasks, decisions, cart and feedback in this browser’s localStorage. These data are not sent to the server. Do not enter real customer information in the demos. A demo apartment reservation is not a real reservation. Resetting sample data removes your changes in the selected demo; browser site-data settings can remove all stored data. Demo attachments retain only the file name and size, not file content.'}</p>
  <h2>{pl?'Panel administracyjny':'Administration panel'}</h2><p>{pl?'Logowanie do panelu CMS wymaga technicznych cookies sesji. Służą do uwierzytelnienia administratora i nie są wykorzystywane do reklamy.':'The CMS administration panel requires technical session cookies for authentication. They are not used for advertising.'}</p>
  <h2>{pl?'Ustawienia animacji':'Animation settings'}</h2><p>{pl?'Przycisk pauzy zmienia zachowanie animacji w bieżącej sesji strony. Nie zapisuje identyfikatora użytkownika. Witryna respektuje systemowe ustawienie ograniczenia ruchu.':'The motion pause control affects the current page session without storing a user identifier. The site respects the system reduced-motion preference.'}</p>
 </div>:<div className="article-prose">
  <h2>{pl?'Kto odpowiada za dane':'Who is responsible'}</h2><p>{s.privacyInfo?.legalName||s.founderName}, {s.brandName}. {pl?'Kontakt w sprawach prywatności:':'Privacy contact:'} <a href={`mailto:${s.email}`}>{s.email}</a>.</p>{s.privacyInfo?.legalAddress&&<p>{s.privacyInfo.legalAddress}</p>}
  {s.privacyInfo?.retentionDescription&&<><h2>{pl?'Okres przechowywania':'Retention period'}</h2><p>{s.privacyInfo.retentionDescription}</p></>}{s.privacyInfo?.hostingProvider&&<><h2>Hosting</h2><p>{s.privacyInfo.hostingProvider}</p></>}
  <h2>{pl?'Co przekazujesz w formularzu':'What you submit'}</h2><p>{pl?'Formularz i kreator briefu zbierają dane, które wpisujesz: imię, adres e-mail, opis pomysłu i opcjonalne informacje o firmie, telefonie, terminie, budżecie lub załącznik. Zapytanie służy do odpowiedzi i omówienia współpracy. Nie zapisuje Cię do newslettera.':'The form and brief builder collect the information you enter: your name, email, description and optional company details, phone, timeline, budget or attachment. Your enquiry is used to reply and discuss potential work. It does not subscribe you to a newsletter.'}</p>
  <h2>{pl?'Gdzie trafia wiadomość':'Where your message goes'}</h2><p>{pl?'Wiadomości zapisują się w bazie danych witryny i są dostępne dla uprawnionego administratora. Asystent jest kreatorem formularza, a nie zewnętrznym modelem AI. Nie wysyła treści rozmowy do dostawcy sztucznej inteligencji.':'Messages are stored in this website’s database and are accessible to an authorized administrator. The assistant is a guided form, not an external AI model. It does not send the conversation to an AI provider.'}</p>
  <h2>{pl?'Kontrola i kontakt':'Control and contact'}</h2><p>{pl?'Możesz napisać, aby zapytać o swoje dane, poprosić o ich poprawienie lub usunięcie. Nie przesyłaj haseł, kluczy dostępu, dokumentów tożsamości ani danych szczególnie wrażliwych. Zakres przetwarzania związany z realizacją projektu ustalamy osobno przy nawiązaniu współpracy.':'You can contact us to ask about your data, request a correction or ask for deletion. Do not send passwords, access keys, identity documents or particularly sensitive data. Data processing for an actual project is agreed separately when the collaboration begins.'}</p>
  <h2>{pl?'Bezpieczeństwo formularza':'Form security'}</h2><p>{pl?'W celu ograniczenia spamu witryna stosuje czasowe limity zapytań i krótkotrwałe tokeny formularza. Ochrona antyspamowa nie służy profilowaniu reklamowemu.':'The website uses temporary request limits and short-lived form tokens to reduce spam. These controls are not used for advertising profiles.'}</p>
 </div>}</article></main>
}
