'use client'

import {useRef,useState} from 'react'
import type {ProjectProps} from '../../project-data'
import './nora.css'

type Category='all'|'cleanse'|'hydrate'|'finish'
type Product={id:string;name:string;category:Exclude<Category,'all'>;kind:'bottle'|'jar'|'mist';color:string;price:number;volume:string;summary:{pl:string;en:string};description:{pl:string;en:string};ingredients:{pl:string;en:string};use:{pl:string;en:string}}
const products:Product[]=[
 {id:'dew',name:'Dew Cleanser',category:'cleanse',kind:'bottle',color:'#d2ddc9',price:89,volume:'150 ml',summary:{pl:'Delikatny żel do codziennego oczyszczania.',en:'A gentle gel for everyday cleansing.'},description:{pl:'Miękki żel, który usuwa codzienne zanieczyszczenia i pozostawia skórę komfortową w dotyku. Pierwszy spokojny krok rytuału.',en:'A soft gel that lifts away the day and leaves skin comfortable to the touch. A quiet first step to your ritual.'},ingredients:{pl:'Hydrolat z róży, gliceryna roślinna, ekstrakt z owsa.',en:'Rose hydrosol, plant glycerin, oat extract.'},use:{pl:'Wmasuj w wilgotną skórę twarzy i spłucz letnią wodą.',en:'Massage into damp facial skin and rinse with lukewarm water.'}},
 {id:'veil',name:'Veil Milk',category:'cleanse',kind:'bottle',color:'#e0d8c5',price:94,volume:'120 ml',summary:{pl:'Kremowa emulsja do łagodnego demakijażu.',en:'A creamy milk for gentle makeup removal.'},description:{pl:'Otulająca mleczna konsystencja rozpuszcza makijaż bez uczucia ściągnięcia. Stworzona dla tych, którzy lubią wolniejszy początek.',en:'A comforting milky texture melts away makeup without a tight feeling. For those who prefer a slower beginning.'},ingredients:{pl:'Olej z pestek moreli, owies, skwalan roślinny.',en:'Apricot kernel oil, oat, plant-derived squalane.'},use:{pl:'Wmasuj w suchą skórę, następnie zmyj ciepłą wodą.',en:'Massage onto dry skin, then rinse with warm water.'}},
 {id:'still',name:'Still Serum',category:'hydrate',kind:'bottle',color:'#ced9c7',price:145,volume:'30 ml',summary:{pl:'Lekka warstwa nawilżenia na każdy poranek.',en:'A light layer of hydration for every morning.'},description:{pl:'Szybko wchłaniające się serum o wodnej teksturze. Daje skórze przyjemne, świeże wykończenie bez ciężkości.',en:'A fast-absorbing serum with a watery texture. Leaves a fresh, comfortable finish without heaviness.'},ingredients:{pl:'Kwas hialuronowy, aloes, ekstrakt z ogórka.',en:'Hyaluronic acid, aloe, cucumber extract.'},use:{pl:'Nałóż 2–3 krople na oczyszczoną, lekko wilgotną skórę.',en:'Apply 2–3 drops to clean, slightly damp skin.'}},
 {id:'moss',name:'Moss Cream',category:'hydrate',kind:'jar',color:'#c7d2bd',price:129,volume:'50 ml',summary:{pl:'Bogaty krem na chwile, gdy potrzeba otulenia.',en:'A rich cream for when you want extra comfort.'},description:{pl:'Krem o aksamitnej konsystencji, który domyka codzienny rytuał. Pielęgnacja, do której chce się wracać.',en:'A velvety cream that completes your everyday ritual. Care you will want to return to.'},ingredients:{pl:'Masło shea, ceramidy, olej z nasion konopi.',en:'Shea butter, ceramides, hemp seed oil.'},use:{pl:'Rozgrzej niewielką ilość w dłoniach i delikatnie rozprowadź na twarzy.',en:'Warm a small amount between your hands and gently smooth over the face.'}},
 {id:'light',name:'Light Lotion',category:'hydrate',kind:'bottle',color:'#e5dfcf',price:119,volume:'60 ml',summary:{pl:'Codzienny lekki krem o jedwabistym wykończeniu.',en:'An everyday lightweight moisturiser with a silky finish.'},description:{pl:'Lekka emulsja dla osób, które cenią nawilżenie bez obciążenia. Łatwo łączy się z resztą porannej pielęgnacji.',en:'An airy emulsion for those who want moisture without weight. Sits easily within a morning routine.'},ingredients:{pl:'Skwalan roślinny, gliceryna, ekstrakt z zielonej herbaty.',en:'Plant-derived squalane, glycerin, green tea extract.'},use:{pl:'Nałóż po serum, delikatnie wklepując w skórę.',en:'Apply after serum, gently pressing into the skin.'}},
 {id:'morning',name:'Morning Mist',category:'finish',kind:'mist',color:'#d3ded8',price:76,volume:'100 ml',summary:{pl:'Odświeżająca mgiełka na dowolny moment dnia.',en:'A refreshing mist for any moment of the day.'},description:{pl:'Delikatna mgiełka, która przynosi chwilę świeżości przy biurku, w podróży i po porannym rytuale.',en:'A fine mist for a moment of freshness at your desk, on the go, or after your morning ritual.'},ingredients:{pl:'Hydrolat z kwiatu pomarańczy, aloes, gliceryna.',en:'Orange blossom hydrosol, aloe, glycerin.'},use:{pl:'Rozpyl na twarz z odległości około 20 cm, omijając oczy.',en:'Mist over the face from around 20 cm away, avoiding the eyes.'}},
]
const text={
 pl:{nav:['Kolekcja','Nasza filozofia','Twój rytuał'],headerAction:'Odkryj swój rytuał',menu:'Menu',close:'Zamknij',heroEyebrow:'BOTANICZNA PIELĘGNACJA / CODZIENNIE',heroA:'Mniej',heroB:'pośpiechu.',heroC:'Więcej',heroD:'siebie.',heroText:'Małe rytuały mają wielką moc. Poznaj pielęgnację, przy której możesz na chwilę zwolnić.',heroLink:'Poznaj kolekcję',heroCaption:'Światło, rośliny i czas tylko dla siebie.',marquee:'Powoli. Naturalnie. Po swojemu.',introLabel:'01 / W CO WIERZYMY',intro:'Dobrze jest zacząć dzień ',introEm:'od siebie.',introText:'NŌRA to pielęgnacja, która nie goni za tempem świata. Czerpiemy inspirację z roślin, prostych składów i poranków, w których można zostać ze sobą odrobinę dłużej.',collectionLabel:'02 / CODZIENNE PRZEDMIOTY',collection:'Rzeczy dobre dla skóry.',collectionText:'Sześć prostych formuł. Wybierz tę, która pasuje do Twojego rytmu.',filters:{all:'Wszystkie',cleanse:'Oczyszczanie',hydrate:'Nawilżanie',finish:'Na koniec'},details:'Poznaj produkt',storyLabel:'03 / MAŁE RYTUAŁY',story:'Pielęgnacja to chwila, nie zadanie.',storyText:'Kilka minut rano. Ciepła woda. Zapach świeżych liści. Nie potrzebujesz idealnego planu — wystarczy miejsce na oddech.',storyLink:'Znajdź swój rytuał',ingredientsLabel:'04 / Z BLISKA',ingredients:'To, co wybieramy.',ingredientsText:'Znane, przyjemne w użyciu składniki, wybrane dla ich roli w codziennej pielęgnacji.',ingredientsList:[['01','Owies','Dla miękkiego, przyjemnego odczucia po oczyszczaniu.'],['02','Aloes','Dla lekkiej, odświeżającej konsystencji.'],['03','Skwalan','Dla gładkiego wykończenia bez tłustego filmu.']],routineLabel:'05 / DLA CIEBIE',routine:'Znajdź swój rytuał.',routineText:'Trzy krótkie pytania. Prosta, kosmetyczna propozycja do Twojego poranka.',step:'KROK',questions:['Jaką konsystencję lubisz najbardziej?','Czego szukasz w porannym rytuale?','Ile czasu masz zwykle dla siebie?'],choices:[['Lekką i wodną','Bogatszą i otulającą'],['Świeżości i prostoty','Chwili odprężenia'],['2 minuty','5 minut lub więcej']],next:'Dalej →',back:'Wróć',resultLabel:'TWÓJ RYTUAŁ',resultTitle:'Poranek po Twojemu.',resultText:'Oto prosta propozycja na podstawie Twoich preferencji kosmetycznych. To inspiracja, nie porada dermatologiczna.',reset:'Zacznij od nowa',resultSteps:['Oczyść','Nawilż','Dokończ'],productLabel:'PRODUKT / NŌRA',ingredientsIn:'Wybrane składniki',howTo:'Jak używać',volume:'Pojemność',closeDialog:'Zamknij szczegóły',endLabel:'NAJPIERW CHWILA DLA SIEBIE',end:'Niech poranek należy do Ciebie.',endText:'Wybierz swoją małą chwilę. Reszta może poczekać.',endLink:'Odkryj swój rytuał',footerNote:'Botaniczna pielęgnacja codzienności.',backTop:'Do góry ↑',demo:'Koncepcyjna kolekcja demonstracyjna. Bez możliwości zakupu.',price:'zł'},
 en:{nav:['The collection','Our philosophy','Your ritual'],headerAction:'Find your ritual',menu:'Menu',close:'Close',heroEyebrow:'BOTANICAL SKINCARE / EVERY DAY',heroA:'Less',heroB:'hurry.',heroC:'More',heroD:'you.',heroText:'Small rituals make room for something bigger. Meet skincare that lets you slow down for a moment.',heroLink:'Explore the collection',heroCaption:'Light, living plants, and time to yourself.',marquee:'Slowly. Naturally. Your way.',introLabel:'01 / WHAT WE BELIEVE',intro:'A good day begins ',introEm:'with yourself.',introText:'NŌRA does not keep pace with the rest of the world. We find inspiration in plants, straightforward formulas, and mornings with a little more time to yourself.',collectionLabel:'02 / EVERYDAY OBJECTS',collection:'Good things for skin.',collectionText:'Six considered formulas. Find the ones that fit your rhythm.',filters:{all:'All',cleanse:'Cleanse',hydrate:'Hydrate',finish:'Finish'},details:'Meet the product',storyLabel:'03 / SMALL RITUALS',story:'Skincare is a moment, not a task.',storyText:'A few minutes in the morning. Warm water. The scent of fresh leaves. You do not need a perfect plan — just room to breathe.',storyLink:'Find your ritual',ingredientsLabel:'04 / A CLOSER LOOK',ingredients:'What we choose.',ingredientsText:'Familiar, satisfying ingredients, chosen for their place in everyday skincare.',ingredientsList:[['01','Oat','For a soft, comfortable feel after cleansing.'],['02','Aloe','For a light and refreshing texture.'],['03','Squalane','For a smooth finish without a greasy feel.']],routineLabel:'05 / JUST FOR YOU',routine:'Find your ritual.',routineText:'Three small questions. A simple cosmetic suggestion for your morning.',step:'STEP',questions:['What texture do you enjoy most?','What are you looking for in the morning?','How much time do you usually have?'],choices:[['Light and watery','Rich and comforting'],['Freshness and simplicity','A moment to unwind'],['2 minutes','5 minutes or more']],next:'Continue →',back:'Back',resultLabel:'YOUR RITUAL',resultTitle:'A morning of your own.',resultText:'A simple suggestion based on your cosmetic preferences. For inspiration only, not dermatological advice.',reset:'Start again',resultSteps:['Cleanse','Hydrate','Finish'],productLabel:'PRODUCT / NŌRA',ingredientsIn:'Selected ingredients',howTo:'How to use',volume:'Volume',closeDialog:'Close details',endLabel:'A MOMENT FOR YOURSELF FIRST',end:'Let the morning be yours.',endText:'Make space for your little moment. The rest can wait.',endLink:'Find your ritual',footerNote:'Botanical care for the everyday.',backTop:'Back to top ↑',demo:'Concept demonstration collection. Not available for purchase.',price:'PLN'}
}

function Bottle({product}:{product:Product}){return <div className={`n-bottle ${product.kind==='jar'?'n-jar':product.kind==='mist'?'n-mist':''}`} aria-hidden="true"><div className="n-bottle-label">NŌRA<small>{product.name}</small></div></div>}

export function NoraSite({locale}:ProjectProps){
 const lang=locale==='pl'?'pl':'en', t=text[lang]
 const [menuOpen,setMenuOpen]=useState(false)
 const [filter,setFilter]=useState<Category>('all')
 const [selected,setSelected]=useState<Product|null>(null)
 const [step,setStep]=useState(0)
 const [answers,setAnswers]=useState<(number|null)[]>([null,null,null])
 const dialogRef=useRef<HTMLDialogElement>(null)
 const showProduct=(product:Product)=>{setSelected(product);dialogRef.current?.showModal()}
 const closeProduct=()=>{dialogRef.current?.close();setSelected(null)}
 const result=[answers[0]===1?'veil':'dew',answers[0]===1?'moss':'light',answers[1]===0||answers[2]===0?'morning':'still'].map(id=>products.find(p=>p.id===id)!)
 return <main className="project-site nora-site">
  <header className="n-header" id="nora-top"><a href="#nora-top" className="n-logo" aria-label="NŌRA — top">NŌRA</a><button className="n-menu" type="button" aria-controls="nora-nav" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?t.close:t.menu} {menuOpen?'×':'+'}</button><nav className="n-nav" id="nora-nav" data-open={menuOpen} aria-label={lang==='pl'?'Nawigacja główna':'Main navigation'}><a href="#nora-collection" onClick={()=>setMenuOpen(false)}>{t.nav[0]}</a><a href="#nora-story" onClick={()=>setMenuOpen(false)}>{t.nav[1]}</a><a href="#nora-routine" onClick={()=>setMenuOpen(false)}>{t.nav[2]}</a></nav><a className="n-header-action" href="#nora-routine">{t.headerAction} ↗</a></header>
  <section className="n-hero"><div className="n-hero-copy"><span className="n-label n-hero-eyebrow">{t.heroEyebrow}</span><div><h1 className="n-serif n-hero-title">{t.heroA}<br/><em>{t.heroB}</em><br/>{t.heroC}<br/><em>{t.heroD}</em></h1><p>{t.heroText}</p><a href="#nora-collection" className="n-text-link">{t.heroLink}<span aria-hidden="true">↗</span></a></div><span className="n-label">NŌRA / EST. IN THE EVERYDAY</span></div><div className="n-hero-image"><img src="/images/showcase/nora-hero.webp" alt={lang==='pl'?'Butelki botanicznych kosmetyków na wapieniu w porannym świetle':'Botanical skincare bottles on limestone in morning light'} /><span className="n-image-caption n-label">{t.heroCaption}</span></div></section>
  <div className="n-marquee" aria-hidden="true">{t.marquee} &nbsp; ✳ &nbsp; {t.marquee}</div>
  <section className="n-intro n-wrap"><span className="n-label">{t.introLabel}</span><div><h2 className="n-serif">{t.intro}<em>{t.introEm}</em></h2><p>{t.introText}</p></div></section>
  <section className="n-collection" id="nora-collection"><div className="n-wrap"><div className="n-section-heading"><div><span className="n-label">{t.collectionLabel}</span><h2 className="n-serif">{t.collection}</h2></div><p>{t.collectionText}</p></div><div className="n-filters" role="group" aria-label={lang==='pl'?'Filtruj produkty':'Filter products'}>{(['all','cleanse','hydrate','finish'] as Category[]).map(cat=><button type="button" className="n-filter" key={cat} aria-pressed={filter===cat} onClick={()=>setFilter(cat)}>{t.filters[cat]}</button>)}</div><div className="n-product-grid">{products.filter(product=>filter==='all'||product.category===filter).map((product,index)=><article className="n-product" key={product.id}><div className="n-product-art" style={{'--n-product-bg':product.color} as React.CSSProperties}><span className="n-art-index n-label">N / 0{index+1}</span><Bottle product={product}/></div><div className="n-product-info"><div className="n-product-meta"><span>{t.filters[product.category]}</span><span>{product.volume}</span></div><h3>{product.name}</h3><p>{product.summary[lang]}</p><button type="button" className="n-product-link" onClick={()=>showProduct(product)}>{t.details} ↗</button></div></article>)}</div></div></section>
  <section className="n-story" id="nora-story"><div className="n-story-image" role="img" aria-label={lang==='pl'?'Botaniczny rytuał pielęgnacyjny w porannym świetle':'Botanical skincare ritual in morning light'}/><div className="n-story-copy"><span className="n-label">{t.storyLabel}</span><h2 className="n-serif">{t.story}</h2><p>{t.storyText}</p><a className="n-text-link" href="#nora-routine">{t.storyLink}<span aria-hidden="true">↗</span></a></div></section>
  <section className="n-ingredients"><div className="n-wrap"><div className="n-section-heading"><div><span className="n-label">{t.ingredientsLabel}</span><h2 className="n-serif">{t.ingredients}</h2></div><p>{t.ingredientsText}</p></div><div className="n-ingredient-grid">{t.ingredientsList.map(([number,title,description])=><div className="n-ingredient" key={number}><span className="n-label">{number} / BOTANICAL NOTES</span><span className="n-symbol" aria-hidden="true">✳</span><div><h3>{title}</h3><p>{description}</p></div></div>)}</div></div></section>
  <section className="n-routine" id="nora-routine"><div className="n-wrap"><div className="n-section-heading"><div><span className="n-label">{t.routineLabel}</span><h2 className="n-serif">{t.routine}</h2></div><p>{t.routineText}</p></div>{step<3?<div className="n-quiz"><div><span className="n-label">{t.step} 0{step+1} / 03</span><div className="n-quiz-progress" aria-hidden="true">{[0,1,2].map(i=><span key={i} data-active={i<=step}/>)}</div></div><div><h3>{t.questions[step]}</h3><div className="n-quiz-options" role="group" aria-label={t.questions[step]}>{t.choices[step].map((choice,index)=><button key={choice} className="n-quiz-choice" type="button" aria-pressed={answers[step]===index} onClick={()=>setAnswers(previous=>previous.map((value,i)=>i===step?index:value))}>{choice}</button>)}</div><div className="n-quiz-actions">{step>0&&<button type="button" className="n-quiz-back" onClick={()=>setStep(step-1)}>← {t.back}</button>}<button type="button" className="n-quiz-next" disabled={answers[step]===null} onClick={()=>setStep(step+1)}>{t.next}</button></div></div></div>:<div className="n-result" aria-live="polite"><span className="n-label">{t.resultLabel}</span><h3>{t.resultTitle}</h3><p>{t.resultText}</p><div className="n-result-steps">{result.map((product,i)=><div className="n-result-step" key={`${i}-${product.id}`}><span className="n-label">0{i+1} / {t.resultSteps[i]}</span><strong>{product.name}</strong><button type="button" className="n-product-link" style={{color:'#f0eee3',borderColor:'#f0eee3'}} onClick={()=>showProduct(product)}>{t.details} ↗</button></div>)}</div><button type="button" className="n-quiz-next" onClick={()=>{setAnswers([null,null,null]);setStep(0)}}>{t.reset} ↗</button></div>}</div></section>
  <section className="n-end"><span className="n-label">{t.endLabel}</span><h2 className="n-serif">{t.end}</h2><p>{t.endText}</p><a className="n-text-link" href="#nora-routine">{t.endLink}<span aria-hidden="true">↗</span></a></section>
  <footer className="n-footer"><div className="n-footer-top"><div><a href="#nora-top" className="n-logo">NŌRA</a><p style={{fontSize:13,marginTop:18}}>{t.footerNote}</p></div><div className="n-footer-links"><a href="#nora-collection">{t.nav[0]}</a><a href="#nora-story">{t.nav[1]}</a><a href="#nora-routine">{t.nav[2]}</a></div></div><div className="n-footer-bottom n-label"><span>© NŌRA 2026 · {t.demo}</span><a href="#nora-top">{t.backTop}</a></div></footer>
  <dialog className="n-dialog" ref={dialogRef} onClose={()=>setSelected(null)} aria-label={selected?.name}><div className="n-dialog-inner">{selected&&<><div className="n-dialog-art" style={{background:selected.color}}><Bottle product={selected}/></div><div className="n-dialog-copy"><button type="button" className="n-dialog-close" aria-label={t.closeDialog} onClick={closeProduct}>×</button><span className="n-label">{t.productLabel}</span><h2>{selected.name}</h2><p>{selected.description[lang]}</p><dl><dt>{t.ingredientsIn}</dt><dd>{selected.ingredients[lang]}</dd><dt>{t.howTo}</dt><dd>{selected.use[lang]}</dd><dt>{t.volume}</dt><dd>{selected.volume} · {selected.price} {t.price}</dd></dl></div></>}</div></dialog>
 </main>
}