'use client'
import Link from 'next/link'
import {useState} from 'react'
import Image from 'next/image'
import {Icon} from './common/Icon'
import {pick} from '@/lib/i18n'
import type {Locale,Media,VisualStyle} from '@/types/site'

function WindowChrome({label,status='LIVE UI'}:{label:string;status?:string}){return <div className="pv-chrome"><span><i/><i/><i/></span><small>{label}</small><em><i/>{status}</em></div>}

function Operations({locale}:{locale:Locale}){
 const [view,setView]=useState(0)
 const items=locale==='pl'?['Overview','Projekty','Dokumenty','Zespół']:['Overview','Projects','Documents','Team']
 return <div className="pv-app pv-operations"><WindowChrome label="workspace / operations"/><div className="pv-shell"><aside><strong>CM / OS</strong><small>WORKSPACE</small>{items.map((x,i)=><button key={x} className={view===i?'active':''} onClick={()=>setView(i)}><Icon name={(['grid','layers','file','chat'] as const)[i]} size={13}/>{x}</button>)}<div className="pv-user"><span>PM</span><div>Piotr M.<small>Admin</small></div></div></aside><div className="pv-content"><div className="pv-page-head"><div><small>{items[view]} / 2026</small><h4>{view===0?pick(locale,'Wszystko pod kontrolą.','Everything in view.'):items[view]}</h4></div><Link className="preview-action" href={`${locale==='en'?'/en':''}/demos/operations`}><Icon name="plus" size={12}/>{pick(locale,'Dodaj','Add')}</Link></div><div className="pv-kpis"><div><span>{pick(locale,'Aktywne','Active')}</span><strong>{12+view*4}</strong><small>+2</small></div><div><span>{pick(locale,'Do decyzji','To review')}</span><strong>{8-view}</strong><small>{pick(locale,'dzisiaj','today')}</small></div><div><span>{pick(locale,'Postęp','Progress')}</span><strong>{68+view*6}%</strong><small>↑</small></div></div><div className="pv-dashboard-grid"><div className="pv-chart"><div className="pv-card-head"><span>{pick(locale,'Aktywność procesu','Process activity')}</span><small>7 DAYS</small></div><svg viewBox="0 0 420 130" preserveAspectRatio="none"><path d="M0 108 C40 95 55 105 92 73 S150 92 185 57 S243 70 282 45 S338 52 420 13" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M0 108 C40 95 55 105 92 73 S150 92 185 57 S243 70 282 45 S338 52 420 13 V130 H0Z" fill="currentColor" opacity=".07"/></svg></div><div className="pv-queue"><div className="pv-card-head"><span>{pick(locale,'Ostatnie','Recent')}</span><small>{4+view}</small></div>{Array.from({length:4},(_,i)=><div key={i}><span className={`row-dot row-${i%3}`}/><div><b>{items[(view+i)%items.length]}</b><small>{pick(locale,'zaktualizowano','updated')}</small></div><em>{i===0?'NEW':'OK'}</em></div>)}</div></div></div></div></div>
}

function Approval({locale}:{locale:Locale}){
 const [approved,setApproved]=useState(false),[selected,setSelected]=useState(0)
 const queue=locale==='pl'?['Odpowiedź do klienta','Aktualizacja CRM','Raport tygodniowy']:['Customer reply','CRM update','Weekly report']
 return <div className="pv-app pv-approval"><WindowChrome label="agent / approval-console" status="HUMAN FIRST"/><div className="approval-shell"><aside><div className="approval-brand"><Icon name="spark" size={16}/>Agent Queue</div><small>DO SPRAWDZENIA</small>{queue.map((x,i)=><button key={x} className={selected===i?'active':''} onClick={()=>{setSelected(i);setApproved(false)}}><span className={`row-dot row-${i}`}/><div><b>{x}</b><small>{i===0?'2 min':'12 min'}</small></div></button>)}</aside><div className="pv-content"><div className="approval-head"><div><small>{pick(locale,'PROPOZYCJA DZIAŁANIA','PROPOSED ACTION')}</small><h4>{queue[selected]}</h4></div><span><Icon name="shield" size={13}/>{pick(locale,'Wymaga decyzji','Needs approval')}</span></div><div className="approval-context"><small>CONTEXT</small><p>{pick(locale,'Agent odczytał wiadomość, sprawdził dane klienta i przygotował bezpieczną propozycję. Nic nie zostanie wykonane bez zatwierdzenia.','The agent read the message, checked customer context and prepared a safe proposal. Nothing is executed before approval.')}</p><div><span>Inbox</span><b>→</b><span>Context</span><b>→</b><span>Proposal</span><b>→</b><span className="active">Approval</span></div></div><div className="approval-action"><div><small>{pick(locale,'PROPONOWANA AKCJA','PROPOSED ACTION')}</small><strong>{selected===1?pick(locale,'Zmień etap szansy na „Review”','Move opportunity to “Review”'):pick(locale,'Przygotuj wersję roboczą i zapisz do kolejki','Prepare a draft and save it to the queue')}</strong><span><Icon name="file" size={13}/> sample decision / local UI</span></div><button className={approved?'approved':''} onClick={()=>setApproved(v=>!v)}><Icon name={approved?'check':'shield'} size={15}/>{approved?pick(locale,'Zatwierdzono','Approved'):pick(locale,'Zatwierdź','Approve')}</button></div></div></div></div>
}

function Commerce({locale}:{locale:Locale}){
 const [tab,setTab]=useState(0),[order,setOrder]=useState(0)
 const tabs=locale==='pl'?['Zamówienia','Produkty','Stock','Fulfillment']:['Orders','Products','Stock','Fulfillment']
 return <div className="pv-app pv-commerce"><WindowChrome label="commerce / operations"/><div className="commerce-shell"><aside><strong>CM / Commerce</strong>{tabs.map((x,i)=><button key={x} className={tab===i?'active':''} onClick={()=>setTab(i)}><Icon name={(['cart','layers','grid','check'] as const)[i]} size={13}/>{x}</button>)}</aside><div className="pv-content"><div className="commerce-head"><div><small>COMMERCE OPS</small><h4>{tabs[tab]}</h4></div><Link className="preview-action" href={`${locale==='en'?'/en':''}/demos/commerce`}><Icon name="plus" size={12}/>{pick(locale,'Nowe','New')}</Link></div><div className="commerce-kpis"><div><small>{pick(locale,'Dzisiaj','Today')}</small><strong>{tab===0?'48':'124'}</strong><span>+12%</span></div><div><small>{pick(locale,'Do wysyłki','To fulfill')}</small><strong>16</strong><span>4h</span></div><div><small>Stock</small><strong>98.4%</strong><span>OK</span></div></div><div className="commerce-table"><div className="commerce-table-head"><span>ID</span><span>{pick(locale,'Klient','Customer')}</span><span>Status</span><span>{pick(locale,'Wartość','Value')}</span></div>{['#1048','#1047','#1046','#1045'].map((id,i)=><button key={id} className={order===i?'active':''} onClick={()=>setOrder(i)}><span>{id}</span><b>{['North Studio','Forma Lab','Atelier 17','Noma Works'][i]}</b><em>{i<2?pick(locale,'Do wysyłki','To fulfill'):pick(locale,'Opłacone','Paid')}</em><strong>{[1290,840,2110,660][i]} PLN</strong></button>)}</div></div><div className="commerce-side-preview"><small>ORDER</small><strong>{['#1048','#1047','#1046','#1045'][order]}</strong><span>{pick(locale,'Płatność','Payment')} <b>✓</b></span><span>{pick(locale,'Magazyn','Stock')} <b>✓</b></span><span>{pick(locale,'Wysyłka','Fulfillment')} <b>→</b></span><Link className="preview-action" href={`${locale==='en'?'/en':''}/demos/commerce`}>{pick(locale,'Otwórz zamówienie','Open order')} ↗</Link></div></div></div>
}

function ClientPortal({locale}:{locale:Locale}){
 const [active,setActive]=useState(0)
 const tabs=locale==='pl'?['Oś czasu','Pliki','Feedback','Odbiór']:['Timeline','Files','Feedback','Approval']
 return <div className="pv-app pv-portal"><WindowChrome label="client / project-workspace"/><div className="portal-shell"><header><strong>CodeMaster.</strong><span>{pick(locale,'Twój projekt / Portal','Your project / Portal')}</span><em><i/> LIVE PREVIEW</em></header><nav>{tabs.map((x,i)=><button key={x} className={active===i?'active':''} onClick={()=>setActive(i)}><span>0{i+1}</span>{x}</button>)}</nav><div className="pv-content"><section><small>{pick(locale,'WERSJA 08 · DZISIAJ','VERSION 08 · TODAY')}</small><h4>{active===0?pick(locale,'Kolejna wersja jest gotowa.','The next version is ready.'):tabs[active]}</h4><p>{pick(locale,'Zobacz zmiany, dodaj uwagę i zatwierdź kierunek bez szukania informacji w wiadomościach.','Review changes, leave feedback and approve the direction without searching through messages.')}</p><Link className="portal-input" href={`${locale==='en'?'/en':''}/demos/client-portal`}><span>{pick(locale,'Dodaj komentarz do tej wersji…','Comment on this version…')}</span><Icon name="arrow" size={13}/></Link></section><aside><div className="portal-preview-card"><div className="preview-nav"><i/><i/><i/></div><div className="preview-hero"><span>CLIENT PORTAL</span><strong>{pick(locale,'Twoja firma.\nJeden widok.','Your company.\nOne view.')}</strong><i/></div></div></aside></div></div></div>
}

export function ProjectVisual({style='dashboard',locale='pl',image,className=''}:{style?:VisualStyle;locale?:Locale;image?:Media|null;className?:string}){
 return <div className={`project-visual visual-${style} ${className}`}>{image?.url?<Image src={image.url} alt={image.alt||''} fill sizes="(max-width: 700px) 95vw, 70vw" style={{objectFit:'cover'}}/>:<div className="visual-content">{style==='mobile'?<Commerce locale={locale}/>:style==='ai'?<Approval locale={locale}/>:style==='web'?<ClientPortal locale={locale}/>:<Operations locale={locale}/>}</div>}</div>
}
