'use client'
import {useEffect,useRef,useState,type FormEvent} from 'react'
import Link from 'next/link'
import {Dialog} from './common/Dialog'
import {Icon} from './common/Icon'
import {RobotMark} from './common/RobotMark'
import {useMotion} from './animation/MotionProvider'
import {topicLabels,validateLead,validateLeadField,type Topic} from '@/lib/lead-validation'
import {createContactSubmission} from '@/lib/contact-client'
import {pagePath,pick} from '@/lib/i18n'
import {trackEvent} from '@/lib/analytics'
import type {Locale} from '@/types/site'
import './robot-identity.css'
type Field='name'|'email'|'company'|'message'|'timeline'|'budget'
const fields:Field[]=['name','email','company','message','timeline','budget']
type Message={side:'assistant'|'user';text:string}
export function RobotChat({locale='pl',email}:{locale?:Locale;email:string}) {
 const [open,setOpen]=useState(false),[topic,setTopic]=useState<Topic|null>(null),[step,setStep]=useState(0),[values,setValues]=useState<Record<string,string>>({}),[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([]),[error,setError]=useState(''),[sending,setSending]=useState(false),[done,setDone]=useState(false),[accepted,setAccepted]=useState(false),[pending,setPending]=useState(false)
 const log=useRef<HTMLDivElement>(null),entry=useRef<HTMLInputElement|HTMLTextAreaElement>(null),session=useRef(createContactSubmission()),{enabled}=useMotion()
 const labels=topicLabels(locale)
 const questions:Record<Field,string>=locale==='pl'?{name:'Jak masz na imię?',email:'Na jaki adres e-mail Piotr może odpisać?',company:'Jak nazywa się Twoja firma? Możesz pominąć.',message:'Co chcesz usprawnić? Opisz problem lub pomysł w kilku zdaniach.',timeline:'Czy masz preferowany termin? Możesz pominąć.',budget:'Masz orientacyjny budżet? Możesz pominąć.'}:{name:'What is your name?',email:'Which email address can Piotr reply to?',company:'What is your company called? You can skip this.',message:'What would you like to improve? Describe your idea in a few sentences.',timeline:'Do you have a preferred timeline? You can skip this.',budget:'Do you have an approximate budget? You can skip this.'}
 const intro=pick(locale,'Cześć, jestem asystentem CodeMaster. Pomogę Ci uporządkować pomysł i przygotować brief dla Piotra.','Hello, I am the CodeMaster assistant. I will help you organize your idea and prepare a brief for Piotr.')
 useEffect(()=>{if(open)trackEvent('assistant_open')},[open])
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(!done&&(pending||Object.values(values).some(Boolean))){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[done,pending,values])
 useEffect(()=>{if(open)log.current?.scrollTo({top:log.current.scrollHeight,behavior:enabled?'smooth':'auto'})},[messages,open,step,enabled])
 useEffect(()=>{if(topic&&step<fields.length)entry.current?.focus()},[topic,step])
 function choose(t:Topic){setTopic(t);setMessages([{side:'user',text:labels[t]},{side:'assistant',text:questions.name}]);setStep(0);setInput(values.name||'');setAccepted(false);setError('')}
 function next(e?:FormEvent,skip=false){
  e?.preventDefault();const field=fields[step],text=skip?'':input.trim();setError('');if(!field)return
  const problem=validateLeadField(field,text,locale);if(problem){setError(problem);return}
  setValues(v=>({...v,[field]:text}));setInput(values[fields[step+1]]||'');setMessages(m=>[...m,{side:'user',text:text||pick(locale,'Pomińmy na razie.','Let’s skip this for now.')},...(step<fields.length-1?[{side:'assistant' as const,text:questions[fields[step+1]]}]:[])]);setStep(s=>s+1)
 }
 async function send(){
  if(sending)return
  const data={...values,topic,locale,source:'chat',privacyAccepted:accepted}
  const result=validateLead(data);if(!result.ok){const invalid=fields.findIndex(f=>Boolean(result.errors[f]));if(invalid>=0){setStep(invalid);setInput(values[fields[invalid]]||'');setMessages(m=>m.slice(0,2+2*invalid))}setError(Object.values(result.errors)[0]);return}
  setSending(true);setError('')
  try{const form=new FormData();for(const [key,value] of Object.entries(result.data))form.set(key,String(value));form.set('website','');const response=await session.current.submit(form);if(!response.ok)throw new Error(response.error||pick(locale,'Nie udało się zapisać briefu. Spróbuj ponownie.','Could not save the brief. Try again.'));setDone(true);trackEvent('assistant_complete')}
  catch(err){setError(err instanceof Error&&!['CONTACT_UNAVAILABLE','RECEIPT_UNAVAILABLE','CHALLENGE_UNAVAILABLE','Failed to fetch','The operation was aborted due to timeout','The operation was aborted.'].includes(err.message)&&err.name!=='TimeoutError'&&err.name!=='AbortError'?err.message: pick(locale,'Nie udało się połączyć z formularzem. Spróbuj ponownie lub napisz e-mail.','The form is unavailable. Please try again or contact us by email.'))}finally{setSending(false);setPending(session.current.pending)}
 }
 return <><button className="robot-launcher robot-launcher--bot" data-animated={enabled} onClick={()=>setOpen(true)} aria-label={pick(locale,'Otwórz czat CodeMaster','Open the CodeMaster chat')} aria-haspopup="dialog" aria-expanded={open}><span className="robot-glyph"><RobotMark/></span><span className="robot-spark" aria-hidden="true"/><span className="robot-tooltip">{pick(locale,'Porozmawiajmy','Let’s talk')}</span></button><Dialog open={open} onClose={()=>setOpen(false)} label={pick(locale,'Asystent CodeMaster — kreator briefu','CodeMaster assistant — brief builder')} className="robot-dialog"><div className="robot-dialog-header"><span className="robot-small robot-small--bot" aria-hidden="true"><span className="robot-glyph"><RobotMark/></span></span><div><strong>CodeMaster Assistant</strong><small><span className="status-dot"/>{pick(locale,'KREATOR BRIEFU · 6 PYTAŃ','BRIEF BUILDER · 6 QUESTIONS')}</small></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label={pick(locale,'Zamknij asystenta','Close assistant')}><Icon name="close" size={18}/></button></div>
 <div className="robot-log" ref={log} role="log" aria-live="polite"><p className="assistant-bubble">{intro}</p>{messages.map((m,i)=><p key={i} className={`${m.side}-bubble`}>{m.text}</p>)}
 {!topic&&<div className="robot-options">{(['system','web','website','automation','commerce','modernization','unknown'] as Topic[]).map(t=><button key={t} onClick={()=>choose(t)}>{labels[t]}<Icon name="arrow" size={15}/></button>)}</div>}
 {topic&&step===fields.length&&!done&&<div className="brief-review"><p className="eyebrow">{pick(locale,'TWÓJ BRIEF','YOUR BRIEF')}</p><h3>{pick(locale,'Wysłać go do Piotra?','Send this to Piotr?')}</h3><dl><dt>{pick(locale,'Temat','Topic')}</dt><dd>{labels[topic]}</dd>{fields.map(field=><div key={field}><dt>{({name:pick(locale,'Imię','Name'),email:'Email',company:pick(locale,'Firma','Company'),message:pick(locale,'Pomysł','Idea'),timeline:pick(locale,'Termin','Timeline'),budget:pick(locale,'Budżet','Budget')} as Record<Field,string>)[field]}</dt><dd>{values[field]||'—'}</dd></div>)}</dl><label className="checkbox-label"><input type="checkbox" disabled={sending||pending} checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>{pick(locale,'Znam','I have read the')} <Link href={pagePath(locale,'privacy')} target="_blank" rel="noopener">{pick(locale,'informację o prywatności','privacy information')}</Link>.</span></label><button className="button button-primary" onClick={send} disabled={sending}>{sending?pick(locale,'Wysyłam…','Sending…'):pick(locale,'Wyślij brief','Send brief')}<Icon name="arrow" size={16}/></button><button className="brief-reset" disabled={sending||pending} onClick={()=>{setStep(0);setInput(values.name||'');setMessages([{side:'user',text:labels[topic]},{side:'assistant',text:questions.name}]);setAccepted(false);setError('')}}>{pick(locale,'Popraw odpowiedzi','Edit your answers')}</button></div>}
 {done&&<div className="robot-success"><span className="success-mark"><Icon name="check" size={28}/></span><h3>{pick(locale,'Brief zapisany.','Your brief is saved.')}</h3><p>{pick(locale,'Dziękuję! Masz dodatkowe materiały? Napisz bezpośrednio:','Thank you! Have additional material? Email:')}</p><a href={`mailto:${email}`}>{email}</a></div>}</div>
 {pending&&<p className="robot-error" role="status">{pick(locale,'Ponowienie sprawdzi poprzedni zapis i zachowa ten sam brief.','Retrying will check the previous submission and preserve the same brief.')}</p>}
 {error&&<p id="robot-field-error" className="robot-error" role="alert">{error}</p>}
 {topic&&step<fields.length&&<form onSubmit={e=>next(e)} className="robot-compose"><label className="sr-only" htmlFor="robot-answer">{questions[fields[step]]}</label>{fields[step]==='message'?<textarea ref={node=>{entry.current=node}} aria-invalid={Boolean(error)} aria-describedby={error?'robot-field-error':undefined} id="robot-answer" value={input} onChange={e=>setInput(e.target.value)} rows={3} maxLength={5000} placeholder={pick(locale,'Napisz kilka zdań…','Write a few sentences…')}/>:<input id="robot-answer" ref={node=>{entry.current=node}} aria-invalid={Boolean(error)} aria-describedby={error?'robot-field-error':undefined} type={fields[step]==='email'?'email':'text'} autoComplete={fields[step]==='email'?'email':fields[step]==='name'?'given-name':fields[step]==='company'?'organization':'off'} value={input} onChange={e=>setInput(e.target.value)} maxLength={fields[step]==='email'?254:['name','budget'].includes(fields[step])?100:160} placeholder={pick(locale,'Twoja odpowiedź…','Your answer…')}/>}<div><span>{step+1} / {fields.length}</span>{['company','timeline','budget'].includes(fields[step])&&<button type="button" className="skip-answer" onClick={()=>next(undefined,true)}>{pick(locale,'Pomiń','Skip')}</button>}<button type="submit" className="send-answer" aria-label={pick(locale,'Dalej','Next')}><Icon name="arrow" size={19}/></button></div></form>}
 <div className="robot-disclosure">{pick(locale,'Kreator briefu prowadzi przez kilka pytań i zapisuje zgłoszenie w formularzu.','The brief builder guides you through a few questions and submits the enquiry form.')}</div></Dialog></>
}
