'use client'

import {useEffect, useState} from 'react'
import type {FormEvent} from 'react'
import type {ProjectProps} from '../../project-data'
import './maison.css'
import {isCivilDate,localDate,calendarDays,formatCivilDate} from '@/lib/civil-date'
import {parseStayPlan,SUITE_RATES} from '@/lib/showcase-validation'

type Suite='garden'|'terrace'
type Plan={arrival:string;departure:string;guests:number;suite:Suite;nights:number;rate:number;total:number}
const rates=SUITE_RATES
const image=(name:string)=>`/images/showcase/maison-${name}`
const euro=(value:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value)

export function MaisonSite({locale}:ProjectProps){
 const pl=locale==='pl'
 const today=localDate()
 const [menuOpen,setMenuOpen]=useState(false)
 const [arrival,setArrival]=useState('')
 const [departure,setDeparture]=useState('')
 const [guests,setGuests]=useState(2)
 const [suite,setSuite]=useState<Suite>('garden')
 const [plan,setPlan]=useState<Plan|null>(null)
 const [error,setError]=useState('')
 const [saved,setSaved]=useState(false)
 const [restored,setRestored]=useState(false)
 useEffect(()=>{try{const raw=localStorage.getItem('maison-demo-plan');if(!raw)return;const item=parseStayPlan(raw);if(item){setPlan(item);setArrival(item.arrival);setDeparture(item.departure);setGuests(item.guests);setSuite(item.suite);setRestored(true)}}catch{/* Ignore unavailable or malformed local storage */}},[])
 const suiteName=(value:Suite)=>value==='garden'?(pl?'Pokój Ogrodowy':'Garden Room'):(pl?'Apartament Tarasowy':'Terrace Suite')
 const closeMenu=()=>setMenuOpen(false)
 const chooseSuite=(value:Suite)=>{setSuite(value);setPlan(null);setSaved(false);setError('')}
 const calculate=(event:FormEvent<HTMLFormElement>)=>{
  event.preventDefault();setSaved(false);setRestored(false)
  if(!isCivilDate(arrival)||!isCivilDate(departure)){setError(pl?'Wybierz datę przyjazdu i wyjazdu.':'Choose both your arrival and departure dates.');setPlan(null);return}
  const count=calendarDays(arrival,departure)
  if(arrival<localDate()){setError(pl?'Data przyjazdu nie może być w przeszłości.':'Arrival cannot be in the past.');setPlan(null);return}
  if(!Number.isFinite(count)||count<1){setError(pl?'Wyjazd musi nastąpić po przyjeździe.':'Departure must be after arrival.');setPlan(null);return}
  if(count>21){setError(pl?'Plan może obejmować maksymalnie 21 nocy.':'The planner supports stays of up to 21 nights.');setPlan(null);return}
  if(!Number.isInteger(guests)||guests<1||guests>4){setError(pl?'Wybierz od 1 do 4 gości.':'Choose between 1 and 4 guests.');setPlan(null);return}
  if(suite==='garden'&&guests>2){setError(pl?'Pokój Ogrodowy jest dla maksymalnie 2 osób. Wybierz Apartament Tarasowy.':'The Garden Room sleeps up to 2. Choose the Terrace Suite for your group.');setPlan(null);return}
  setError('');setPlan({arrival,departure,guests,suite,nights:count,rate:rates[suite],total:count*rates[suite]})
 }
 const savePlan=()=>{if(!plan)return;try{localStorage.setItem('maison-demo-plan',JSON.stringify(plan));setSaved(true)}catch{setError(pl?'Nie udało się zapisać lokalnie. Możesz pobrać plan.':'Local saving is unavailable. You can download your plan instead.')}}
 const downloadPlan=()=>{
  if(!plan)return
  const text=[`MAISON — ${pl?'Plan pobytu':'Stay plan'}`,`${pl?'Apartament':'Suite'}: ${suiteName(plan.suite)}`,`${pl?'Przyjazd':'Arrival'}: ${plan.arrival}`,`${pl?'Wyjazd':'Departure'}: ${plan.departure}`,`${pl?'Goście':'Guests'}: ${plan.guests}`,`${pl?'Noce':'Nights'}: ${plan.nights}`,`${pl?'Stawka ilustracyjna / noc':'Illustrative rate / night'}: ${euro(plan.rate)}`,`${pl?'Suma ilustracyjna':'Illustrative total'}: ${euro(plan.total)}`,'',pl?'To autorskie demo. To nie jest rezerwacja ani potwierdzenie dostępności.':'This is an authored demo. It is not a booking or availability confirmation.'].join('\n')
  const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='maison-stay-plan.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
 }
 const formatDate=(value:string)=>formatCivilDate(value,locale)
 return <div className="project-site maison-site" id="top">
  <header className="ms-nav ms-shell"><a href="#top" className="ms-logo" onClick={closeMenu}>MAISON</a><button className="ms-menu" type="button" aria-controls="maison-navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?(pl?'Zamknij':'Close'):'Menu'}</button><nav className="ms-links" id="maison-navigation" data-open={menuOpen} aria-label={pl?'Nawigacja główna':'Main navigation'}><a href="#story" onClick={closeMenu}>{pl?'Nasza historia':'Our story'}</a><a href="#rooms" onClick={closeMenu}>{pl?'Pokoje':'Rooms'}</a><a href="#moments" onClick={closeMenu}>{pl?'Chwile':'Moments'}</a><a href="#planner" className="ms-link-cta" onClick={closeMenu}>{pl?'Zaplanuj pobyt':'Plan your stay'} <span aria-hidden="true">↗</span></a></nav></header>
  <main>
   <section className="ms-hero" aria-labelledby="ms-hero-heading"><img src={image('hero.webp')} alt={pl?'Kameralny dom w ciepłym popołudniowym świetle, otoczony drzewami':'Intimate country house in warm afternoon light, surrounded by trees'} fetchPriority="high"/><div className="ms-shell ms-hero-content"><span className="ms-eyebrow">{pl?'MAŁY DOM. WIĘCEJ CZASU.':'A SMALL HOUSE. MORE TIME.'}</span><h1 id="ms-hero-heading">{pl?<>Pobądź<br/><i>trochę dłużej.</i></>:<>Stay a<br/><i>little longer.</i></>}</h1><p>{pl?'Miejsce na powolne poranki, otwarte okna i plany, których nie trzeba robić.':'A place for slow mornings, open windows and plans you don’t have to make.'}</p><a href="#rooms" className="ms-solid-cta">{pl?'Odkryj pokoje':'Explore the rooms'} <span aria-hidden="true">↗</span></a></div><div className="ms-shell ms-hero-bottom"><span>MAISON / {pl?'DOM Z DALA OD POŚPIECHU':'A HOME AWAY FROM HURRY'}</span><span>{pl?'PRZEWIŃ W DÓŁ ↓':'SCROLL TO EXPLORE ↓'}</span></div></section>
   <section className="ms-welcome ms-shell" id="story"><aside><span className="ms-eyebrow">01 / {pl?'Witaj w Maison':'Welcome to Maison'}</span><span></span><p>{pl?'Nie wszystko, co wyjątkowe, musi być wielkie. Czasem wystarczy otwarte okno i jeszcze jedna filiżanka kawy.':'Not everything wonderful needs to be grand. Sometimes an open window and one more cup of coffee are enough.'}</p></aside><div><h2>{pl?<>Nie musisz nic robić.<br/><em>Po prostu bądź.</em></>:<>Nothing to do.<br/><em>Every reason to stay.</em></>}</h2><p className="ms-body">{pl?'Maison to wyobrażenie niewielkiego domu gościnnego, w którym dzień nie dzieli się na atrakcje. Śniadanie może trwać długo. Ścieżka za ogrodem może prowadzić donikąd. I właśnie o to chodzi.':'Maison imagines a small guesthouse where a day is not divided into attractions. Breakfast can take its time. The path beyond the garden may lead nowhere in particular. That is precisely the point.'}</p></div></section>
   <section className="ms-suites ms-shell" id="rooms"><div className="ms-section-title"><span className="ms-eyebrow">02 / {pl?'Pokoje':'The rooms'}</span><h2>{pl?'Miejsce dla Ciebie.':'Room to be.'}</h2><p>{pl?'Dwa różne sposoby na to samo: zamknąć drzwi i poczuć, że jesteś dokładnie tam, gdzie trzeba.':'Two different ways to do the same thing: close the door and feel exactly where you need to be.'}</p></div>
    <article className="ms-suite-feature"><img src={image('suite.jpg')} alt={pl?'Pokój Ogrodowy: lniane łóżko, ciepłe tkaniny i widok na drzewa':'Garden Room with linen bed, warm textiles and a view of the trees'} loading="lazy"/><div className="ms-suite-copy"><span className="ms-no">01</span><span className="ms-eyebrow">{pl?'DLA DWOJGA':'FOR TWO'}</span><h3>{pl?'Pokój Ogrodowy':'The Garden Room'}</h3><p>{pl?'Miękkie światło rano. Len, ceramika, kilka ulubionych książek. Otwórz okno i pozwól, by dzień sam zdecydował, co dalej.':'Soft morning light. Linen, ceramics, a few favourite books. Open the window and let the day decide what comes next.'}</p><span className="ms-details">{pl?'DO 2 GOŚCI · OD 185 € / NOC':'UP TO 2 GUESTS · FROM €185 / NIGHT'}</span><button type="button" onClick={()=>{chooseSuite('garden');document.getElementById('planner')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>{pl?'Zaplanuj ten pokój →':'Plan this room →'}</button></div></article>
    <article className="ms-suite-secondary"><img src={image('bath.jpg')} alt={pl?'Apartament Tarasowy: kamienna wanna przy oknie w ciepłym wnętrzu':'Terrace Suite with a stone bath by a sunlit window'} loading="lazy"/><div className="ms-suite-copy"><span className="ms-no">02</span><span className="ms-eyebrow">{pl?'PRZESTRZEŃ DLA BLISKICH':'ROOM TO SHARE'}</span><h3>{pl?'Apartament Tarasowy':'The Terrace Suite'}</h3><p>{pl?'Dłuższy poranek, miejsce na wspólny stół i chwila tylko dla siebie. Więcej przestrzeni na to, co przyniesiesz ze sobą.':'A longer morning, room for a shared table, and a moment to yourself. More space for whatever you bring along.'}</p><span className="ms-details">{pl?'DO 4 GOŚCI · OD 245 € / NOC':'UP TO 4 GUESTS · FROM €245 / NIGHT'}</span><button type="button" onClick={()=>{chooseSuite('terrace');document.getElementById('planner')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}>{pl?'Zaplanuj ten apartament →':'Plan this suite →'}</button></div></article>
   </section>
   <section className="ms-moment" id="moments"><div className="ms-shell ms-moment-grid"><div><span className="ms-eyebrow">03 / {pl?'Małe rytuały':'Small rituals'}</span><h2>{pl?<>Dni bez<br/><i>pośpiechu.</i></>:<>Days with<br/><i>no hurry.</i></>}</h2><p>{pl?'Chwile, których nie trzeba planować z wyprzedzeniem. Czas na smak, rozmowę i ciszę między nimi.':'Moments that need no advance planning. Time for flavour, conversation and the quiet in between.'}</p><ul><li>{pl?'Śniadanie, kiedy masz ochotę':'Breakfast when you feel like it'}</li><li>{pl?'Długa chwila przy stole':'A long moment at the table'}</li><li>{pl?'Spacer bez wyznaczonej trasy':'A walk without a route'}</li></ul></div><img src={image('table.jpg')} alt={pl?'Śniadanie w zacienionym ogrodzie: owoce, pieczywo i kawa':'Breakfast in a shaded garden with fruit, bread and coffee'} loading="lazy"/></div></section>
   <section className="ms-note ms-shell"><div className="ms-ornament" aria-hidden="true">M.</div><span className="ms-eyebrow">04 / {pl?'Mała przypominajka':'A gentle reminder'}</span><blockquote>{pl?'„Najlepsze wspomnienia rzadko zaczynają się od napiętego planu.”':'“The best memories rarely begin with a full itinerary.”'}</blockquote><p>{pl?'Myśl przewodnia Maison — nie opinia gościa.':'A thought from Maison — not a guest review.'}</p></section>
   <section className="ms-planner" id="planner"><div className="ms-shell ms-planner-grid"><div className="ms-planner-intro"><span className="ms-eyebrow">05 / {pl?'Twój czas':'Your time'}</span><h2>{pl?<>Zostań<br/><i>na chwilę.</i></>:<>Stay<br/><i>awhile.</i></>}</h2><p>{pl?'Ułóż przykładowy plan pobytu. Daty i ceny służą wyłącznie ilustracji — nie sprawdzamy dostępności ani nie przyjmujemy rezerwacji.':'Create an illustrative stay plan. Dates and prices are for demonstration only — no availability is checked and no booking is made.'}</p></div><div className="ms-planner-card"><form onSubmit={calculate} noValidate><div className="ms-form-grid"><div className="ms-field"><label htmlFor="ms-arrival">{pl?'Przyjazd':'Arrival'}</label><input id="ms-arrival" type="date" required min={today} value={arrival} onChange={event=>{setArrival(event.target.value);setPlan(null);setError('')}}/></div><div className="ms-field"><label htmlFor="ms-departure">{pl?'Wyjazd':'Departure'}</label><input id="ms-departure" type="date" required min={arrival||today} value={departure} onChange={event=>{setDeparture(event.target.value);setPlan(null);setError('')}}/></div></div><div className="ms-field"><label htmlFor="ms-guests">{pl?'Liczba gości':'Guests'}</label><select id="ms-guests" value={guests} onChange={event=>{setGuests(Number(event.target.value));setPlan(null);setError('')}}><option value={1}>1 {pl?'osoba':'guest'}</option><option value={2}>2 {pl?'osoby':'guests'}</option><option value={3}>3 {pl?'osoby':'guests'}</option><option value={4}>4 {pl?'osoby':'guests'}</option></select></div><span className="ms-select-label">{pl?'Wybierz pokój':'Choose your room'}</span><div className="ms-suite-options"><button type="button" aria-pressed={suite==='garden'} onClick={()=>chooseSuite('garden')}><strong>{pl?'Ogrodowy':'Garden'}</strong><span>{euro(rates.garden)} / {pl?'noc':'night'} · {pl?'do 2 osób':'up to 2'}</span></button><button type="button" aria-pressed={suite==='terrace'} onClick={()=>chooseSuite('terrace')}><strong>{pl?'Tarasowy':'Terrace'}</strong><span>{euro(rates.terrace)} / {pl?'noc':'night'} · {pl?'do 4 osób':'up to 4'}</span></button></div>{error&&<p className="ms-error" role="alert">{error}</p>}<button type="submit" className="ms-solid-cta">{pl?'Zobacz przykładowy plan':'See illustrative plan'} <span aria-hidden="true">↗</span></button></form>
     {plan&&<div className="ms-plan-summary" aria-live="polite"><h3>{restored?(pl?'Twój zapisany plan':'Your saved plan'):(pl?'Twój mały plan':'Your little plan')}</h3><dl><dt>{pl?'Pokój':'Room'}</dt><dd>{suiteName(plan.suite)}</dd><dt>{pl?'Terminy':'Dates'}</dt><dd>{formatDate(plan.arrival)} – {formatDate(plan.departure)}</dd><dt>{pl?'Goście':'Guests'}</dt><dd>{plan.guests}</dd><dt>{pl?'Noce':'Nights'}</dt><dd>{plan.nights} × {euro(plan.rate)}</dd><dt className="ms-total">{pl?'Suma ilustracyjna':'Illustrative total'}</dt><dd className="ms-total">{euro(plan.total)}</dd></dl><p>{pl?'To tylko osobisty szkic pobytu. Nie jest rezerwacją, ofertą ani potwierdzeniem dostępności.':'This is a personal stay sketch only. It is not a booking, offer or availability confirmation.'}</p><div className="ms-plan-actions"><button type="button" onClick={savePlan}>{pl?'Zapisz w przeglądarce':'Save in browser'}</button><button type="button" onClick={downloadPlan}>{pl?'Pobierz plan .txt':'Download plan .txt'}</button></div>{saved&&<p className="ms-saved" role="status">{pl?'Zapisano wyłącznie w tej przeglądarce.':'Saved in this browser only.'}</p>}</div>}</div></div></section>
  </main>
  <footer className="ms-footer"><div className="ms-shell"><div className="ms-footer-grid"><div><span className="ms-eyebrow">MAISON / {pl?'PO PROSTU BĄDŹ':'SIMPLY BE HERE'}</span><h2>{pl?'Do zobaczenia<br/>w wyobraźni.':'See you in<br/>the daydream.'}</h2><p>{pl?'Maison to autorska koncepcja doświadczenia gościnności stworzona na potrzeby portfolio.':'Maison is an authored hospitality concept created for a portfolio experience.'}</p></div><div className="ms-footer-links"><a href="#rooms">{pl?'Odkryj pokoje ↗':'Explore the rooms ↗'}</a><a href="#planner">{pl?'Ułóż plan pobytu ↗':'Plan a stay ↗'}</a><a href="#top">{pl?'Wróć na górę ↑':'Back to top ↑'}</a></div></div><div className="ms-footer-bottom"><span>MAISON — {pl?'AUTORSKIE DEMO':'AN AUTHORED DEMO'}</span><span>{pl?'ŻADNE REZERWACJE NIE SĄ PRZYJMOWANE':'NO BOOKINGS ARE ACCEPTED'}</span></div></div></footer>
 </div>
}